# -*- coding: utf-8 -*-
"""Morphology_exporter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZGUdLMHw1jrObSaYZJ--XHk3ke23rHx
"""

# %% CELL 1 -- (deleted) ----------------------------------------------------
# Nothing to upload: every module and suite lives in CODE_DIR on Drive. The
# upload step was itself the hazard -- Colab RENAMES on collision, so a fresh
# alignment.py landed as 'alignment (1).py' while `import alignment` kept
# loading the stale /content copy, and the whole bank passed against code that
# was not being shipped. Reading from ONE pinned directory removes the failure
# mode instead of guarding against it.

# %% CELL 2 -- environment, one pinned source directory, NEURON -------------
import importlib
import os
import shutil
import sys

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# neuron and LFPy are needed at CELL 6, not CELL 7: the propagation gate builds
# an LFPy.Cell before anything is committed. Install them later and every cell
# fails the gate with 'qc_raised:ModuleNotFoundError'.
get_ipython().system("pip install -q plotly neuron LFPy")          # noqa: F821

# ---- THE one place the code lives. Edit this line and nothing else. ----
CODE_DIR = "/content/drive/MyDrive/Colab Notebooks/New algorithms/Stage 1"

REQUIRED_MODULES = [
    "spine_density.py", "spine_cap.py", "spine_cap_plots.py",
    "node_classify.py", "soma_enforce.py",
    "morphology_exporter.py", "spine_labeller.py",
    "alignment.py", "alignment_plots.py", "hoc_qc.py",
    "synapse_redirect_audit.py",
]
REQUIRED_TESTS = [
    "test_node_classify.py", "test_soma_enforce.py", "test_spine_density.py",
    "test_phi_pipeline.py", "test_morphology_exporter.py",
    "smoke_spine_cap.py", "test_spine_cap_plots.py",
    "smoke_synapse_redirect_audit.py", "smoke_alignment.py",
    "smoke_alignment_plots.py", "test_hoc_qc.py", "test_align_gate.py",
]

if not os.path.isdir(CODE_DIR):
    raise FileNotFoundError(
        "CODE_DIR does not exist: %r\nDrive paths are case-sensitive and "
        "spaces count. Check the exact folder name." % CODE_DIR)

missing = [f for f in REQUIRED_MODULES + REQUIRED_TESTS
           if not os.path.isfile(os.path.join(CODE_DIR, f))]
if missing:
    raise FileNotFoundError(
        "not in %r:\n  %s\n\nEverything must be in ONE directory. Files split "
        "across folders is how a stale copy of one module ends up shadowing a "
        "fresh copy of another." % (CODE_DIR, "\n  ".join(missing)))

# Remove any leftover .py in /content from an earlier upload-based run. With
# '' (the CWD) ahead of CODE_DIR on sys.path such a file WINS, and importing a
# module you did not edit is the failure that looks like a passing test suite.
stale = [os.path.join("/content", f) for f in os.listdir("/content")
         if f.endswith(".py") and os.path.isfile(os.path.join("/content", f))]
for p in stale:
    os.remove(p)
shutil.rmtree("/content/__pycache__", ignore_errors=True)
if stale:
    print("removed %d stale .py from /content (would have shadowed "
          "CODE_DIR)" % len(stale))

sys.path = [CODE_DIR] + [p for p in sys.path
                         if os.path.abspath(p or ".") != os.path.abspath(CODE_DIR)]

# Drop anything already imported. Without this, editing a module on Drive and
# re-running the notebook silently keeps testing the version from the FIRST
# run of the session.
for name in [f[:-3] for f in REQUIRED_MODULES]:
    sys.modules.pop(name, None)
importlib.invalidate_caches()

print("CODE_DIR = %s\n" % CODE_DIR)
for f in REQUIRED_MODULES:
    m = importlib.import_module(f[:-3])
    src = os.path.abspath(getattr(m, "__file__", ""))
    if os.path.dirname(src) != os.path.abspath(CODE_DIR):
        raise ImportError(
            "%s was imported from %r, NOT from CODE_DIR -- something is still "
            "shadowing it." % (f, src))
    print("OK  %-30s %s" % (f, getattr(m, "MODULE_VERSION", "")))

try:
    import LFPy
    import neuron
    print("\nNEURON %s, LFPy %s" % (
        neuron.__version__, getattr(LFPy, "__version__", "?")))
except Exception as exc:                                     # noqa: BLE001
    raise RuntimeError(
        "NEURON/LFPy did not import (%r). The propagation gate cannot run "
        "without them, and every cell would be reported as failing to "
        "conduct." % exc)

print("\nall %d modules imported from CODE_DIR" % len(REQUIRED_MODULES))

# =========================================================================== #
# CELL 3b -- NEW. Paste immediately after CELL 3.                             #
# =========================================================================== #
# CELL 3's pass/fail matcher looks for the string "N / N" in a suite's stdout.
# The S1 suites do not print that; they print "  PASS  <name>" per check and
# "ALL CHECKS PASSED" at the end. Adding them to CELL 3's SUITES list would
# therefore mark them FAILED even when green. They get their own cell, which
# calls their own runner -- which additionally does the HPC transfer-safety
# checks (non-ASCII AND carriage-return bytes: different bugs, different byte
# ranges, an ASCII scan will never find CRLF) before running anything.
#
# The runner is located EXPLICITLY rather than by relative name. A bare
# "run_all_tests.py" resolves against the notebook's cwd (/content), not
# against CODE_DIR on Drive, and the interpreter then exits 2 with its message
# on stderr -- which, if only stdout is printed, looks like an empty run.

import os
import subprocess
import sys

# CODE_DIR is defined in CELL 1/2. Fall back to searching sys.path so this
# cell also works in the upload-to-/content layout.
_runner = None
for _d in ([CODE_DIR] if "CODE_DIR" in dir() else []) + sys.path + [os.getcwd()]:
    if _d and os.path.exists(os.path.join(_d, "run_all_tests.py")):
        _runner = os.path.join(_d, "run_all_tests.py")
        break
if _runner is None:
    raise FileNotFoundError(
        "run_all_tests.py not found in CODE_DIR, on sys.path, or in cwd. "
        "Put the S1 files next to the other S1 modules.")
print("runner: %s" % _runner)

# A fresh interpreter does not inherit sys.path entries added at runtime, so
# forward the live path or the runner cannot import modules kept on Drive.
_env = dict(os.environ)
_env["PYTHONPATH"] = os.pathsep.join(p for p in sys.path if p) + (
    os.pathsep + _env["PYTHONPATH"] if _env.get("PYTHONPATH") else "")

_r = subprocess.run([sys.executable, _runner], capture_output=True,
                    text=True, env=_env)
print(_r.stdout)
if _r.stderr.strip():
    print("--- stderr ---")
    print(_r.stderr[-3000:])

if _r.returncode == 3:
    raise RuntimeError(
        "S1 dependencies not importable -- see the list above. They are "
        "existing project modules; check CODE_DIR is on sys.path.")
if _r.returncode == 4:
    raise RuntimeError(
        "one or more suite FILES are missing from CODE_DIR -- see the "
        "directory listing and the closest-name suggestions above. This is a "
        "setup problem, not a test failure; nothing is wrong with the code.")
if _r.returncode != 0:
    raise RuntimeError(
        "S1 suites not green (exit %d) -- stop" % _r.returncode)
print("S1 modules green")

# %% CELL 4 -- EDIT THIS CELL -----------------------------------------------
# Bank source. Two ways to supply the id list -- use ONE:
#   (a) NEURON_IDS_CSV points at a CSV with an id column (e.g. an L3_exc list
#       you maintain elsewhere). This is the normal path once a bank is more
#       than a handful of cells -- hand-typing 20-100 ids invites transcription
#       errors that show up as silent 'file not found' skips three cells in.
#   (b) leave NEURON_IDS_CSV = None and edit the literal NEURON_IDS list below,
#       as before. Fine for a handful of cells.
NEURON_IDS_CSV = None
# e.g. "/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons/L3_exc_ids.csv"
NEURON_IDS_COLUMN = "nid"
NEURON_IDS = [1302789404, 1317492596, 1333261412, 1376890291]

METADATA_CSV = ("/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons/"
                "alignment_metadata_L3.csv")      #################### CHANGEEEEEE
SKELETONS_DIR = "/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons"
# Synapse export per neuron: neuron_{id}_synapses.csv, H01 format (location_x/
# y/z in VOXEL units, optional direction/synapse_type columns). Same directory
# as the skeletons unless you keep them separately -- edit if so.
SYNAPSES_DIR = "/content/drive/MyDrive/Colab Notebooks/Synapse database"
# 'incoming' keeps only postsynaptic sites ON this cell -- the ones that matter
# for a single-cell passive model. None disables the filter.
SYNAPSE_DIRECTION = "incoming"
VOXEL_RES_NM = (8.0, 8.0, 33.0)          # H01 default; anisotropic z-sampling
# False restores the pre-redirect behaviour: export + align + gate only, no
# synapse loading, no C-09. A cell whose synapse file is simply MISSING (not
# unusual across a real bank) is not an error either way -- CELL 6 proceeds
# without the redirect for that cell alone and says so.
RUN_SYNAPSE_REDIRECT = True

OUTPUT_DIR = "/content/drive/MyDrive/Colab Notebooks/Aligned Neurons HOC/temp/New/L3_exc" #################### CHANGEEEEEE
FIGURE_DIR = OUTPUT_DIR + "/figures"

# Skip a neuron whose neuron_{id}_alignment.json already exists in OUTPUT_DIR
# rather than re-exporting it. This is what makes a bank run resumable across
# a Colab disconnect: re-running the notebook from CELL 6 picks up where it
# left off instead of redoing every already-committed cell. A gate FAILURE
# commits nothing (see align_and_export's staging design), so a previously
# failed cell is correctly NOT skipped and gets retried.
CHECKPOINT = True

# EVERY neuron gets the full treatment: export, align, gate, redirect, hoc
# validation, its own four figures. Nothing is sampled. The loop is STREAMING
# instead: one neuron is processed to completion, every artefact written to
# OUTPUT_DIR, its summary row appended to BANK_SUMMARY_CSV, and then every
# large object it created is deleted before the next neuron is loaded. Peak
# RAM is therefore one neuron's worth regardless of bank size, and only a
# ~1 KB scalar record per neuron is retained in memory for the batch plots.
#
# The rigidity control re-exports each cell a SECOND time without alignment, so
# it roughly doubles per-cell cost. It is the check that alignment never leaks
# into a phi-affecting quantity, so it stays ON for every cell; set False only
# if wall-clock forces it.
RUN_RIGIDITY_CONTROL = True

# Save per-neuron figures. Each is written to disk and the figure object freed
# immediately. False skips figure generation entirely (faster, less I/O) while
# still processing every neuron.
SAVE_PER_NEURON_FIGURES = False

K_NEIGHBORS = 3          # local alignment, settled 25 July 2026

# Segmentation. These fix the lfpy_idx index space and are stamped into
# provenance. Eyal 2016 for human L2/3 pyramidal; for INTERNEURONS use
# alignment.RA_YAO_INTERNEURON (100.0) with the subtype's cm instead.
CM_BASE = 0.50           # uF/cm2, intrinsic and shaft-referenced (contract C-14)
RA = 268.5               # ohm cm

# QC-only. Rm enters NOTHING downstream: it is the passive leak used to make a
# transient decay during the gate, and is discarded afterwards. cm and Ra are
# NOT QC-only -- they fix nseg, so the gate must run at the same discretisation
# the bank will be used with, which is why they are shared above.
# 24000 ohm cm2 = tau_m 12.03 ms (Deitcher 2017) / cm 0.5 uF/cm2 (Eyal 2016).
RM_QC = 24000.0

# Distal tip closure (spine_cap). The H01 skeletons were "eroded back from
# endpoints by 100 nm" (Shapson-Coe 2024 supplement), so every skeleton LEAF --
# spine head, dendritic tip, axon tip alike -- is an open tube in the frustum
# chain. CAP_TIPS closes each with a spherical cap of pole height CAP_H_UM,
# passing through the rim circle of radius r_t:
#
#     A_cap = pi (r_t^2 + h^2)          [Archimedes hat-box; see spine_cap]
#
# Applied SYMMETRICALLY to spine and shaft leaves: capping only the spine side
# would raise F by construction.
#
# CAP_TIPS selects which mode f_implied / F_lit / A_spine_um2 report. The FULL
# BRACKET (no cap / flat disc / cap) is written to the summary either way, so
# switching this flag changes which column is canonical, never what is known.
#
# Leave False until you have read s1_tip_audit.png and s1_spine_gallery.png:
# a large label-boundary count means the labeller truncates spines
# mid-structure, and the correction would then be applied to nodes that saw
# no erosion.
CAP_TIPS = False
CAP_H_UM = 0.100         # um; the documented H01 endpoint erosion

MAX_SEGMENTS_INTERACTIVE = 30000
MAX_SEGMENTS_STATIC = 20000
# Inline Plotly rendering keeps every figure ALIVE in the notebook's output,
# which defeats the streaming design: the browser accumulates what the kernel
# just freed. Leave False for a bank run. Figures are always saved to disk.
SHOW_INLINE = False

# %% CELL 5 -- imports + the metadata bank + neuron id list -----------------
import json
import time

import numpy as np
import pandas as pd

import morphology_exporter as mx
import spine_labeller as sl
import node_classify as nc
import alignment as al
import alignment_plots as ap
import hoc_qc as hq
import synapse_redirect_audit as sra

os.makedirs(FIGURE_DIR, exist_ok=True)
metadata_df = al.load_alignment_metadata(METADATA_CSV)
print("bank %s: %d references" % (os.path.basename(METADATA_CSV),
                                  len(metadata_df)))
print("gate: Rm %.0f ohm cm2 -> g_pas %.3e S/cm2, step %.2f nA for %.0f ms" % (
    RM_QC, 1.0 / RM_QC, hq.DEFAULT_AMP_NA, hq.DEFAULT_DUR_MS))

if NEURON_IDS_CSV:
    if not os.path.isfile(NEURON_IDS_CSV):
        raise FileNotFoundError(
            "NEURON_IDS_CSV does not exist: %r" % NEURON_IDS_CSV)
    _ids_df = pd.read_csv(NEURON_IDS_CSV)
    if NEURON_IDS_COLUMN not in _ids_df.columns:
        raise ValueError(
            "column %r not in %r -- has: %s" % (
                NEURON_IDS_COLUMN, NEURON_IDS_CSV, list(_ids_df.columns)))
    NEURON_IDS = _ids_df[NEURON_IDS_COLUMN].dropna().astype(np.int64).tolist()
    _dupes = len(NEURON_IDS) - len(set(NEURON_IDS))
    if _dupes:
        print("WARNING: %d duplicate id(s) in %s -- each will be (re)processed "
              "once, per CHECKPOINT" % (_dupes, NEURON_IDS_CSV))

if not NEURON_IDS:
    raise ValueError("NEURON_IDS is empty -- nothing to run")

print("bank to process: %d neuron ids" % len(NEURON_IDS))


BANK_SUMMARY_CSV = os.path.join(FIGURE_DIR, "bank_summary.csv")

# Every scalar the batch plots need. alignment_plots._records_frame reads 11
# fields and rigidity() compares 6 keys, ALL of them scalars -- so a compact
# record keeps every batch plot working while holding nothing large.
COMPACT_DROP = ("frames", "files", "propagation_qc", "hoc_validation")


def _compact(res):
    """Strip a per-neuron record to scalars, for the in-memory batch list.

    Removes: `frames` (a full labelled DataFrame), `files` (paths, re-derivable
    from disk), `propagation_qc` (nested per-criterion reports with violation
    lists) and `hoc_validation` (a geometry dict carrying section-name lists).
    All four are ALREADY persisted -- propagation_qc and the rest inside
    neuron_{nid}_alignment.json, the geometry inside
    neuron_{nid}_hoc_validation.json -- so dropping them from memory loses
    nothing recoverable.

    `alignment` is KEPT: it is a 3-vector, a 3x3 matrix and a few scalars, and
    _records_frame reads det/orthonormality_error/pairwise_angle_deg_max and
    neighbour_distance_um straight out of it.
    """
    out = {k: v for k, v in res.items() if k not in COMPACT_DROP}
    qc = res.get("propagation_qc") or {}
    out["gate_status"] = qc.get("qc_status")
    out["gate_dv_soma_mV"] = qc.get("C4_soma", {}).get("dv_soma_mV")
    out["gate_dv_min_mV"] = qc.get("dv_min_mV")
    out["gate_monotone_violations"] = (
        qc.get("C3_monotone", {}).get("n_violations"))
    out["totnsegs"] = res.get("totnsegs", qc.get("totnsegs"))
    hv = res.get("hoc_validation") or {}
    geo = hv.get("geometry") or {}
    out["hoc_verdict"] = hv.get("verdict")
    out["soma_diameter_um"] = geo.get("soma_diameter_um")
    out["largest_diameter_um"] = geo.get("largest_diameter_um")
    out["largest_diameter_section"] = geo.get("largest_diameter_section")
    out["total_length_um"] = geo.get("total_length_um")
    return out


def _summary_row(rec):
    """One flat row for BANK_SUMMARY_CSV. Scalars only, no nesting."""
    d = rec.get("alignment", {}) or {}
    nd = d.get("neighbour_distance_um") or [float("nan")]
    return {
        "nid": rec.get("nid"), "qc_status": rec.get("qc_status"),
        "reasons": ";".join(rec.get("reasons", [])),
        "n_sections": rec.get("n_sections"),
        "n_branches": rec.get("n_branches"),
        "f_implied": rec.get("f_implied"), "F_lit": rec.get("F_lit"),
        "A_shaft_um2": rec.get("A_shaft_um2"),
        "A_spine_um2": rec.get("A_spine_um2"),
        # the cap bracket, always written regardless of CAP_TIPS: the cap is
        # an assumption, and one number would hide that
        "cap_tips": rec.get("cap_tips"), "cap_h_um": rec.get("cap_h_um"),
        "f_implied_nocap": rec.get("f_implied_nocap"),
        "f_implied_disc": rec.get("f_implied_disc"),
        "f_implied_cap": rec.get("f_implied_cap"),
        "F_lit_nocap": rec.get("F_lit_nocap"),
        "F_lit_disc": rec.get("F_lit_disc"),
        "F_lit_cap": rec.get("F_lit_cap"),
        "A_spine_um2_nocap": rec.get("A_spine_um2_nocap"),
        "A_spine_um2_cap": rec.get("A_spine_um2_cap"),
        "total_spine_cap_um2": rec.get("total_spine_cap_um2"),
        "total_shaft_cap_um2": rec.get("total_shaft_cap_um2"),
        "n_spine_true_leaf": (rec.get("tip_audit") or {}).get(
            "spine_n_true_leaf"),
        "n_spine_label_boundary_end": (rec.get("tip_audit") or {}).get(
            "spine_n_label_boundary_end"),
        "mean_r_tip_um": (rec.get("tip_audit_summary") or {}).get(
            "spine_mean_r_tip_um"),
        "nearest_ref_um": round(float(np.min(nd)), 1),
        "pairwise_spread_deg": d.get("pairwise_angle_deg_max"),
        "angle_from_z_deg": rec.get("angle_from_z_deg"),
        "totnsegs": rec.get("totnsegs"),
        "gate_status": rec.get("gate_status"),
        "gate_dv_soma_mV": rec.get("gate_dv_soma_mV"),
        "gate_dv_min_mV": rec.get("gate_dv_min_mV"),
        "gate_monotone_violations": rec.get("gate_monotone_violations"),
        "hoc_verdict": rec.get("hoc_verdict"),
        "soma_diameter_um": rec.get("soma_diameter_um"),
        "largest_diameter_um": rec.get("largest_diameter_um"),
        "largest_diameter_section": rec.get("largest_diameter_section"),
        "total_length_um": rec.get("total_length_um"),
        "n_synapses": rec.get("n_synapses"),
        "n_on_pruned_spine": rec.get("n_on_pruned_spine"),
        "n_redirected": rec.get("n_redirected"),
        "n_unresolved_spine_bases": rec.get("n_unresolved_spine_bases"),
        "n_unknown_type": rec.get("n_unknown_type"),
        "rigidity_identical": rec.get("rigidity_identical"),
        "exporter_id": rec.get("exporter_id"),
        "cm": CM_BASE, "Ra": RA, "Rm_qc": RM_QC, "k_neighbors": K_NEIGHBORS,
    }


def _append_summary_row(rec):
    """Append ONE row to BANK_SUMMARY_CSV immediately, header on first write.

    Written per neuron rather than once at the end so that a kernel death at
    neuron 60 of 80 still leaves 59 complete rows on disk. This file, not the
    in-memory list, is the bank's record of itself.
    """
    row = pd.DataFrame([_summary_row(rec)])
    header = not os.path.isfile(BANK_SUMMARY_CSV)
    row.to_csv(BANK_SUMMARY_CSV, mode="a", header=header, index=False)


RUN_LOG_PATH = os.path.join(OUTPUT_DIR, "run_log.jsonl")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def _log_run(entry):
    """Append one JSON line per cell. Not the source of truth -- each cell's
    own alignment.json/hoc_validation.json is -- but gives a flat, greppable
    per-cell history of a bank run across possibly several sessions, without
    having to re-derive it from directory listings."""
    entry = dict(entry)
    entry["ts"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with open(RUN_LOG_PATH, "a", newline="\n") as fh:
        fh.write(json.dumps(entry, default=str) + "\n")


def _reconstruct_committed_files(output_dir, nid):
    """Rebuild a res['files']-shaped dict from what is ACTUALLY on disk, for
    RESUME only. Never trusts a path string inside an old JSON -- a Drive
    folder can be renamed after the fact -- every path is re-derived from
    output_dir + nid and checked to exist before being included."""
    files = {}
    hoc_path = os.path.join(output_dir, "neuron_%s_aligned.hoc" % nid)
    if os.path.isfile(hoc_path):
        files["hoc"] = hoc_path
    for name in ("phi", "segment_map", "section_table", "spine_bases",
                "synapses", "mapped_synapses"):
        p = os.path.join(output_dir, "neuron_%s_%s.csv" % (nid, name))
        if os.path.isfile(p):
            files[name] = p
    for name in ("provenance", "hoc_validation"):
        p = os.path.join(output_dir, "neuron_%s_%s.json" % (nid, name))
        if os.path.isfile(p):
            files[name] = p
    prov_path = os.path.join(output_dir, "neuron_%s_alignment.json" % nid)
    if os.path.isfile(prov_path):
        files["alignment_provenance"] = prov_path
    return files



# %% CELL 6a -- helpers: structural audit, quarantine, per-neuron figures ---
# Definitions only; nothing runs here. They are used INSIDE the CELL 6 loop so
# each neuron is fully judged and fully drawn before its artefacts are freed.
#
# The structural audit is COMPLEMENTARY to the propagation gate, not a
# duplicate. The gate asks "does a transient reach every compartment"; this
# asks "is the FILE a well-formed NEURON model". They overlap (a detached
# section fails both) but neither contains the other: the gate cannot see two
# somatic sections or a wrong root, and the audit cannot see an inverted
# connection. Neither promotes -- align_and_export already committed -- so the
# audit's job is to quarantine what the electrical test did not catch.
import gc
import re
import shutil

from IPython.display import display

# Every figure path written across the whole bank run.
saved = []

STRUCTURAL, SOFT = "structural", "soft"
MIN_SOMA_DIAM_UM = 4.0


def audit_hoc_geometry(path):
    """Structural audit of an emitted .hoc. No NEURON needed."""
    txt = open(path, "r", encoding="ascii").read()

    arrays = {m[0]: int(m[1]) for m in re.findall(r"create (\w+)\[(\d+)\]", txt)}
    secs = {"%s[%d]" % (a, n) for a, k in arrays.items() for n in range(k)}

    conn = re.findall(
        r"connect\s+(\w+\[\d+\])\(([\d.]+)\),\s*(\w+\[\d+\])\(([\d.]+)\)", txt)
    child_of = {c: p for c, _, p, _ in conn}
    kids = {}
    for c, _, p, _ in conn:
        kids.setdefault(p, []).append(c)

    roots = sorted(secs - set(child_of))
    somatic = sorted(s for s in secs if s.startswith("soma"))

    start = "soma[0]" if "soma[0]" in secs else (roots[0] if roots else None)
    seen, stack = set(), ([start] if start else [])
    while stack:
        s = stack.pop()
        if s in seen:
            continue
        seen.add(s)
        stack.extend(kids.get(s, []))
    orphans = sorted(secs - seen)

    cur, pts, n_declared, unparsable = None, {}, {}, []
    for line in txt.splitlines():
        m = re.match(r"\s*(\w+\[\d+\])\s*\{", line)
        if m:
            cur = m.group(1)
            pts.setdefault(cur, [])
        # Permissive token capture, then explicit float conversion. A strict
        # numeric regex would FAIL TO MATCH 'pt3dadd(nan, ...)' and drop the
        # point silently, which is worse than a loud failure.
        m2 = re.search(r"pt3dadd\(\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^)]+)\)",
                       line)
        if m2 and cur is not None:
            n_declared[cur] = n_declared.get(cur, 0) + 1
            try:
                pts[cur].append([float(g.strip()) for g in m2.groups()])
            except ValueError:
                unparsable.append(cur)

    zero_len, bad_diam, few_pts, nonfinite, lengths = [], [], [], [], {}
    for s in sorted(secs):
        P = pts.get(s, [])
        if len(P) < 2:
            few_pts.append(s)
            continue
        A = np.asarray(P, dtype=float)
        if not np.isfinite(A).all():
            nonfinite.append(s)
            continue
        L = float(np.sum(np.linalg.norm(np.diff(A[:, :3], axis=0), axis=1)))
        lengths[s] = L
        if L <= 1e-9:
            zero_len.append(s)
        if A[:, 3].min() <= 0.0:
            bad_diam.append(s)

    dropped = sorted(s for s, n in n_declared.items() if len(pts.get(s, [])) != n)
    diam_max = {s: float(np.asarray(P)[:, 3].max()) for s, P in pts.items() if P}
    biggest = max(diam_max, key=diam_max.get) if diam_max else None

    return {"path": str(path), "n_sections": len(secs), "arrays": arrays,
            "n_connect": len(conn), "roots": roots, "somatic_sections": somatic,
            "n_reachable": len(seen), "orphans": orphans,
            "zero_length": zero_len, "nonpositive_diam": bad_diam,
            "few_pt3d": few_pts, "nonfinite": nonfinite,
            "unparsable_pt3d": sorted(set(unparsable)), "dropped_pt3d": dropped,
            "total_length_um": float(sum(lengths.values())),
            "largest_diameter_section": biggest,
            "largest_diameter_um": (float(diam_max[biggest]) if biggest
                                    else float("nan")),
            "soma_diameter_um": float(diam_max.get("soma[0]", float("nan")))}


def classify_violations(geo, neuron_rep=None, min_soma_diam_um=MIN_SOMA_DIAM_UM):
    """Q6 ladder: STRUCTURAL -> fail, SOFT -> pass_low_confidence."""
    v = {STRUCTURAL: [], SOFT: []}

    if len(geo["roots"]) != 1:
        v[STRUCTURAL].append("I-15: %d root sections %r" % (
            len(geo["roots"]), geo["roots"][:6]))
    if len(geo["somatic_sections"]) != 1:
        v[STRUCTURAL].append("I-15: %d somatic sections" % (
            len(geo["somatic_sections"]),))
    if geo["roots"] and geo["somatic_sections"] and (
            geo["roots"][0] != geo["somatic_sections"][0]):
        v[STRUCTURAL].append("I-15: root %s is not the soma" % geo["roots"][0])
    if geo["orphans"]:
        v[STRUCTURAL].append("debris: %d of %d sections unreachable, e.g. %r" % (
            len(geo["orphans"]), geo["n_sections"], geo["orphans"][:5]))
    if geo["n_connect"] != geo["n_sections"] - 1:
        v[STRUCTURAL].append("not a tree: %d connect for %d sections" % (
            geo["n_connect"], geo["n_sections"]))

    for key, msg in (("zero_length", "zero-length sections (NaN nseg)"),
                     ("nonpositive_diam", "non-positive diameters"),
                     ("few_pt3d", "sections with fewer than 2 pt3d points"),
                     ("nonfinite", "non-finite coordinates"),
                     ("unparsable_pt3d", "unparsable pt3dadd coordinates"),
                     ("dropped_pt3d", "pt3d points lost during parsing")):
        if geo[key]:
            v[STRUCTURAL].append("%s: %d %r" % (msg, len(geo[key]), geo[key][:5]))

    # apic_dend / basal_dend must never appear: the split is retired and
    # node_classify.assert_domain_collapsed guards it at emission. Checking the
    # FILE too means a hand-edited .hoc cannot smuggle one past.
    retired = sorted(set(geo["arrays"]) & set(nc.RETIRED_DOMAIN_ARRAYS))
    if retired:
        v[STRUCTURAL].append("retired domain arrays present: %r" % retired)

    if geo["largest_diameter_section"] != "soma[0]":
        v[SOFT].append("I-18: largest-calibre section is %s (%.3f um), not the "
                       "soma (%.3f um)" % (geo["largest_diameter_section"],
                                           geo["largest_diameter_um"],
                                           geo["soma_diameter_um"]))
    if not (geo["soma_diameter_um"] >= float(min_soma_diam_um)):
        v[SOFT].append("I-18: soma diameter %.3f um is below the %.2f um floor" % (
            geo["soma_diameter_um"], float(min_soma_diam_um)))

    if neuron_rep is not None and neuron_rep.get("neuron_available"):
        if neuron_rep.get("I16_no_synapse_sections") is False:
            v[STRUCTURAL].append("I-16: synapse label in the section vocabulary")
        if neuron_rep.get("I13a_vocabulary_admissible") is False:
            v[STRUCTURAL].append("I-13a: inadmissible arrays %r" % (
                neuron_rep.get("arrays"),))
        if neuron_rep.get("I15_single_soma_is_root") is False:
            v[STRUCTURAL].append("I-15 (NEURON): roots=%r" % (
                neuron_rep.get("root_sections"),))
        n_sec = neuron_rep.get("n_sections")
        if n_sec is not None and n_sec != geo["n_sections"]:
            v[STRUCTURAL].append("NEURON loaded %d sections, file declares %d" % (
                n_sec, geo["n_sections"]))
    return v


def _verdict(v):
    if v[STRUCTURAL]:
        return "fail"
    return "pass_low_confidence" if v[SOFT] else "pass"


def _merge_qc(existing, hoc_verdict):
    """The emitted file can only lower confidence, never raise it."""
    order = {"pass": 0, "pass_low_confidence": 1, "fail": 2}
    return max([existing, hoc_verdict], key=lambda s: order.get(s, 2))


# NEURON is loaded in a SUBPROCESS. h.load_file() is global and cumulative:
# validating several cells in one kernel leaves earlier sections in h.allsec(),
# so the second cell would report the sum of both and fail on n_sections. An
# isolated interpreter per file is the only clean way, and a NEURON segfault
# then cannot take the notebook down.
_NEURON_SNIPPET = r"""
import json, sys
sys.path[:0] = %r
import morphology_exporter as mx
print("@@@" + json.dumps(mx.validate_hoc(%r, min_soma_diam_um=%r), default=str))
"""


def neuron_validate(hoc_path, timeout=300):
    code = _NEURON_SNIPPET % ([p for p in sys.path if p], str(hoc_path),
                              float(MIN_SOMA_DIAM_UM))
    try:
        r = subprocess.run([sys.executable, "-c", code], capture_output=True,
                           text=True, timeout=timeout, env=_env)
        for line in r.stdout.splitlines():
            if line.startswith("@@@"):
                return json.loads(line[3:])
        return {"neuron_available": False, "import_error": (r.stderr or "")[-300:]}
    except Exception as exc:                                 # noqa: BLE001
        return {"neuron_available": False, "import_error": repr(exc)}



def _merge_hoc_verdict(existing, hoc_verdict):
    """The emitted file can only LOWER confidence, never raise it."""
    order = {"pass": 0, "pass_low_confidence": 1, "fail": 2}
    return max([existing, hoc_verdict], key=lambda x: order.get(x, 2))


def _write_validation_json(dest_dir, nid, validation):
    os.makedirs(dest_dir, exist_ok=True)
    path = os.path.join(dest_dir, "neuron_%s_hoc_validation.json" % nid)
    with open(path, "w", newline="\n") as fh:
        fh.write(json.dumps(validation, indent=2, sort_keys=True, default=str))
    return path


def _quarantine(output_dir, nid, res):
    """Move every artefact of a structurally invalid cell out of the bank.

    Matches on the neuron_{nid} prefix rather than res['files'], so an artefact
    the exporter wrote but did not register travels too and nothing is left
    behind to be mistaken for a valid bank member. Also rewrites res['files']
    to the new location, so the record stays truthful about where things are.
    """
    qdir = os.path.join(output_dir, "_quarantine")
    os.makedirs(qdir, exist_ok=True)
    prefix = "neuron_%s" % nid
    for f in sorted(os.listdir(output_dir)):
        src_p = os.path.join(output_dir, f)
        if f.startswith(prefix) and os.path.isfile(src_p):
            shutil.move(src_p, os.path.join(qdir, f))
    for k, val in list(res.get("files", {}).items()):
        pth = val if isinstance(val, str) else (
            val.get("path") if isinstance(val, dict) else None)
        if not pth:
            continue
        newp = os.path.join(qdir, os.path.basename(pth))
        if isinstance(val, str):
            res["files"][k] = newp
        else:
            val["path"] = newp
    return qdir


def _save_neuron_figures(nid, df_lab, df_ali, soma_pos, diag):
    """Write this neuron's four figures and release every figure object.

    Plotly figures are NOT closed by ap.save_figure (only matplotlib is), so
    they are deleted explicitly here -- an interactive arbour figure carries
    the full coordinate arrays and would otherwise survive the iteration.
    """
    written = []
    fig = ap.arbour_comparison(df_lab, df_ali, nid, raw_units="nm",
                               aligned_units="nm",
                               max_segments=MAX_SEGMENTS_INTERACTIVE)
    written.append(ap.save_figure(fig, "%s/neuron_%s_arbour.html" % (
        FIGURE_DIR, nid)))
    if SHOW_INLINE:
        display(fig)
    del fig

    fig = ap.arbour_static(df_lab, df_ali, nid,
                           max_segments=MAX_SEGMENTS_STATIC)
    written.append(ap.save_figure(fig, "%s/neuron_%s_arbour.png" % (
        FIGURE_DIR, nid)))
    del fig

    fig = ap.depth_profile(df_ali, nid, units="nm")
    written.append(ap.save_figure(fig, "%s/neuron_%s_depth.png" % (
        FIGURE_DIR, nid)))
    del fig

    fig = ap.neighbourhood(soma_pos, metadata_df, diag, nid)
    written.append(ap.save_figure(fig, "%s/neuron_%s_neighbourhood.png" % (
        FIGURE_DIR, nid)))
    del fig

    saved.extend(written)
    return written


# %% CELL 6 -- export + align + GATE, one cell at a time --------------------
# STREAMING: one neuron processed to completion, persisted, then every large
# object it created is released before the next is read. Peak RAM is one
# neuron's worth regardless of how many are in the bank.
import traceback


def make_label_fn(nid):
    """In-memory adapter around the verbatim L1653 labeller, which is
    disk-based. Bound per neuron because the labeller keys on the filename."""
    def label_fn(df, threshold_nm):
        import shutil
        import tempfile
        tmp = tempfile.mkdtemp()
        try:
            df.to_csv(os.path.join(tmp, "neuron_%s.csv" % nid), index=False)
            out = sl.label_dendritic_spines_robust(
                [nid], input_dir=tmp, output_dir=None,
                spine_length_threshold_nm=threshold_nm)
            return out[nid] if isinstance(out, dict) else out
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    return label_fn


# Only SCALAR records are retained across iterations. Everything large is
# written to disk and deleted before the next neuron is loaded.
records, regression_records, failures, gated_out, quarantined = [], [], [], [], []
n_resumed = 0
_t_loop_start = time.time()
_durations = []          # fresh cells only -- resumed cells would skew the ETA

for _i, nid in enumerate(NEURON_IDS):
    print("\n" + "=" * 70)
    print("neuron %s  [%d/%d]" % (nid, _i + 1, len(NEURON_IDS)))
    if _durations:
        eta_s = np.mean(_durations) * (len(NEURON_IDS) - _i)
        print("  elapsed %.0f min, avg %.0f s/fresh cell, ETA ~%.0f min" % (
            (time.time() - _t_loop_start) / 60.0, np.mean(_durations),
            eta_s / 60.0))
    t0 = time.time()

    prov_path = os.path.join(OUTPUT_DIR, "neuron_%s_alignment.json" % nid)
    if CHECKPOINT and os.path.isfile(prov_path):
        with open(prov_path) as fh:
            res = json.load(fh)
        committed = _reconstruct_committed_files(OUTPUT_DIR, nid)
        if "hoc" in committed:
            n_resumed += 1
            print("  resumed from %s (qc=%s) -- skipping re-export" % (
                os.path.basename(prov_path), res.get("qc_status")))
            hv_path = os.path.join(OUTPUT_DIR,
                                   "neuron_%s_hoc_validation.json" % nid)
            if os.path.isfile(hv_path):
                with open(hv_path) as fh:
                    res["hoc_validation"] = json.load(fh)
            rec = _compact(res)
            records.append(rec)
            _log_run({"nid": nid, "event": "resumed",
                      "qc_status": rec.get("qc_status")})
            del res, committed, rec
            continue
        print("  checkpoint found but no committed .hoc -- reprocessing")
        del res, committed

    # Names bound inside the try, so `finally` must tolerate their absence.
    df_raw = syn_raw = syn_df = res = ctl = df_lab = df_ali = None
    try:
        path = "%s/neuron_%s.csv" % (SKELETONS_DIR, nid)
        if not os.path.isfile(path):
            raise FileNotFoundError(path)
        df_raw = pd.read_csv(path)
        label_fn = make_label_fn(nid)

        if RUN_SYNAPSE_REDIRECT:
            syn_path = "%s/neuron_%s_synapses.csv" % (SYNAPSES_DIR, nid)
            if not os.path.isfile(syn_path):
                print("  no synapse file at %s -- proceeding WITHOUT the "
                      "redirect for this cell" % syn_path)
            else:
                syn_raw = pd.read_csv(syn_path)
                syn_df = sra.map_synapses_to_nodes_raw(
                    syn_raw, df_raw, voxel_res=VOXEL_RES_NM,
                    direction=SYNAPSE_DIRECTION)
                del syn_raw
                syn_raw = None
                labels = syn_df["synapse_label"].value_counts().to_dict()
                print("  %d synapses mapped to nodes (%s), median snap "
                      "%.1f nm, by label %s" % (
                          len(syn_df), SYNAPSE_DIRECTION or "all",
                          syn_df["snap_distance_nm"].median(), labels))
                # An all-unknown result is an upstream schema mismatch, not
                # data: H01 codes synapse_type as int 2=exc / 1=inh, so a fully
                # unclassified batch means the column is absent or renamed.
                if labels.get("unknown_syn", 0) == len(syn_df):
                    print("  WARNING: every synapse is unknown_syn -- check "
                          "the synapse CSV's type column name against "
                          "map_synapses_to_nodes_raw(type_column=...)")

        # Staging is INTERNAL: export + alignment go to a scratch dir, the gate
        # runs there, and OUTPUT_DIR is written only if the cell conducts.
        res = al.align_and_export(
            df_raw, nid, OUTPUT_DIR, metadata_df,
            cm=CM_BASE, Ra=RA, Rm=RM_QC, label_fn=label_fn,
            k_neighbors=K_NEIGHBORS, syn_df=syn_df,
            return_frames=True, verbose=True,
            cap_tips=CAP_TIPS, cap_h_um=CAP_H_UM)

        qc = res.get("propagation_qc", {})
        if qc:
            print("  gate: %s  dv soma %.3f mV, min %.3g mV, %d segs" % (
                qc.get("qc_status"),
                qc.get("C4_soma", {}).get("dv_soma_mV", float("nan")),
                qc.get("dv_min_mV", float("nan")),
                qc.get("totnsegs", -1)))
            for r in qc.get("reasons", []):
                print("        %s" % r)

        if syn_df is not None and "n_synapses" in res:
            print("  redirect: %d synapses, %d on pruned spines, %d "
                  "redirected, %d unresolved bases, %d unclassified" % (
                      res["n_synapses"], res["n_on_pruned_spine"],
                      res["n_redirected"], res["n_unresolved_spine_bases"],
                      res.get("n_unknown_type", 0)))

        if res["qc_status"] == "fail":
            gated_out.append({"nid": nid, "reasons": res.get("reasons", [])})
            print("  NOT WRITTEN to %s" % OUTPUT_DIR)
            _log_run({"nid": nid, "event": "gated_out",
                      "reasons": res.get("reasons", [])})
            _durations.append(time.time() - t0)
            continue

        # ---- rigidity control, every cell ---------------------------------- #
        if RUN_RIGIDITY_CONTROL:
            # The cap setting MUST match the aligned run. export step 7 emits
            # f_implied / A_spine_um2, which are regression keys; running the
            # control uncapped against a capped `res` would report a spurious
            # "alignment moved a quantity" on every cell.
            ctl = mx.export_neuron(df_raw, "%s_unaligned" % nid, OUTPUT_DIR,
                                   label_fn=label_fn, align_fn=None,
                                   write_files=False, verbose=False,
                                   cap_tips=CAP_TIPS, cap_h_um=CAP_H_UM)
            # COMPARE LIKE WITH LIKE. regression_check compares qc_status (it
            # is in al.REGRESSION_KEYS), but `ctl` is a bare export_neuron call
            # that never runs the propagation gate, while `res` has been
            # through it. Using res["qc_status"] here reports a spurious
            # "alignment moved a quantity" on every cell the GATE downgraded --
            # a false rigidity failure with identical geometry. The geometric
            # keys are all computed at export step 7, before align_fn is
            # applied at step 9, so they cannot differ; qc_status was the only
            # key that ever could.
            res_rigid = dict(res)
            res_rigid["qc_status"] = res.get("exporter_qc_status",
                                             res["qc_status"])
            chk = al.regression_check(ctl, res_rigid)
            res["rigidity_identical"] = bool(chk["identical"])
            print("  rigidity: %s" % ("IDENTICAL" if chk["identical"] else
                                      "*** MOVED *** %s" % chk["diffs"]))
            # Keep the six scalars rigidity() plots AND the diffs -- the diffs
            # are what make a failure diagnosable at the point it is raised,
            # instead of sending you back through 80 cells of scrollback.
            regression_records.append({
                "nid": nid,
                "unaligned": {k: ctl.get(k) for k in ap.REGRESSION_LABELS},
                "aligned": {k: res.get(k) for k in ap.REGRESSION_LABELS},
                "check": {"identical": bool(chk["identical"]),
                          "diffs": dict(chk["diffs"])}})
            del ctl, chk, res_rigid
            ctl = None

        # ---- structural validation of the committed .hoc ------------------- #
        # Moved INTO the loop (was CELL 6b): a cell must be fully judged before
        # its artefacts are released, or a quarantine decision would need the
        # record resurrected later.
        entry = res["files"]["hoc"]
        hoc_path = entry if isinstance(entry, str) else entry["path"]
        geo = audit_hoc_geometry(hoc_path)
        nrep = neuron_validate(hoc_path)
        viol = classify_violations(geo, nrep)
        hoc_verdict = _verdict(viol)
        res["hoc_validation"] = {"geometry": geo, "neuron": nrep,
                                 "violations": viol, "verdict": hoc_verdict}
        res["qc_status"] = _merge_hoc_verdict(res["qc_status"], hoc_verdict)
        print("  hoc: %s  %d sections, %d orphans, %.1f um cable, "
              "soma %.3f um" % (
                  hoc_verdict.upper(), geo["n_sections"], len(geo["orphans"]),
                  geo["total_length_um"], geo["soma_diameter_um"]))
        for level in (STRUCTURAL, SOFT):
            for msg in viol[level]:
                print("    [%s] %s" % (level, msg))

        if hoc_verdict == "fail":
            dest = _quarantine(OUTPUT_DIR, nid, res)
            quarantined.append(nid)
            failures.append({
                "nid": nid,
                "error": "hoc validation FAILED: %s" % "; ".join(
                    viol[STRUCTURAL])})
            _write_validation_json(dest, nid, res["hoc_validation"])
            print("  QUARANTINED -> %s (excluded from bank)" % dest)
            _log_run({"nid": nid, "event": "quarantined",
                      "reasons": viol[STRUCTURAL]})
            _durations.append(time.time() - t0)
            continue
        _write_validation_json(os.path.dirname(hoc_path), nid,
                               res["hoc_validation"])

        # ---- angle from +z (ALWAYS), then optional figures, then free ------ #
        # angle_from_z_deg is NOT a plotting by-product. It is the input to
        # ap.orientation_consistency, which its own docstring calls the acid
        # test of alignment across cells: a bank whose arbours do not cluster
        # near +z has an alignment problem no per-cell check can see. Computing
        # it only when figures were requested silently emptied that plot for
        # every figure-less run. The frame is transient either way -- it is
        # built, used, and freed inside this block -- so asking for it
        # unconditionally costs nothing in the streaming design.
        if "frames" in res:
            soma_pos = np.asarray(res["alignment"]["soma_pos_nm"], float)
            mean_matrix = np.asarray(res["alignment"]["mean_matrix"], float)
            df_lab = res.pop("frames")["labelled"]
            df_ali = al.make_align_fn(soma_pos, mean_matrix)(df_lab, nid)

            res["angle_from_z_deg"] = ap.angle_from_z_deg(
                ap.arbour_direction(df_ali))
            print("  aligned arbour is %.1f deg from +z" %
                  res["angle_from_z_deg"])

            if SAVE_PER_NEURON_FIGURES:
                _save_neuron_figures(nid, df_lab, df_ali, soma_pos,
                                     res["alignment"])

            del df_lab, df_ali, soma_pos, mean_matrix
            df_lab = df_ali = None
        else:
            # align_and_export withheld the frame -- angle stays absent rather
            # than being silently filled with a wrong value.
            res.pop("frames", None)
            print("  WARNING: no labelled frame returned; angle_from_z_deg "
                  "unavailable for this cell")

        # ---- persist the summary row, keep only scalars -------------------- #
        rec = _compact(res)
        _append_summary_row(rec)
        records.append(rec)

        dt = time.time() - t0
        _durations.append(dt)
        print("  done in %.1f s" % dt)
        _log_run({"nid": nid, "event": "processed",
                  "qc_status": rec.get("qc_status"), "duration_s": dt})
        del rec
    except Exception as exc:                                 # noqa: BLE001
        failures.append({"nid": nid, "error": repr(exc)})
        print("  FAILED: %r" % exc)
        traceback.print_exc()
        _log_run({"nid": nid, "event": "error", "error": repr(exc)})
    finally:
        # THE point of the streaming design: whatever happened above -- success,
        # gate failure, quarantine or exception -- every large object this
        # iteration created is released before the next neuron is read. Peak
        # RAM is one neuron's worth, not the bank's.
        for _name in ("df_raw", "syn_raw", "syn_df", "res", "ctl",
                      "df_lab", "df_ali", "geo", "nrep", "viol", "labels"):
            globals().pop(_name, None)
        gc.collect()

print("\n%d in hand (%d resumed, %d freshly processed), %d gated out, "
      "%d quarantined, %d errored" % (
          len(records), n_resumed, len(records) - n_resumed, len(gated_out),
          len(quarantined), len(failures)))
for g in gated_out:
    print("  gated out %s: %s" % (g["nid"], "; ".join(g["reasons"])))
if quarantined:
    print("  quarantined: %s" % quarantined)
if not records:
    raise RuntimeError("no cell survived -- nothing to aggregate")
print("\nbank summary: %s" % BANK_SUMMARY_CSV)

# Commented out IPython magic to ensure Python compatibility.


# =========================================================================== #
# CELL 6c -- NEW. Paste immediately after CELL 6.                             #
# =========================================================================== #
# Reads `frames`, which CELL 6 has already populated. Touches nothing else.
# Runs in two passes because the truncation boundary estimate is POOLED: it
# needs every cell's extent before it can judge any single cell's tips.

import json

import numpy as np
import pandas as pd

import spine_cap as spc
import spine_cap_plots as scp
import spine_density as sd
import spine_geometry as sg
import truncation_flag as tf

try:
    import phi_pipeline_colab as ppc
    _HAVE_RADIUS_REPORT = True
except ImportError:
    _HAVE_RADIUS_REPORT = False
    print("WARNING: phi_pipeline_colab not uploaded -- the authoritative "
          "radius gate is unavailable, and every resistance printed below "
          "must be treated as unverified. Upload it and re-run this cell.")

# CELL 6 must have run in THIS kernel: `frames` is what it leaves behind, and
# it is the only input this cell has. A bare NameError here is unhelpful --
# it points at line 26 of this cell rather than at the cell you actually need
# to run.
_missing_globals = [g for g in ("frames", "OUTPUT_DIR") if g not in dir()]
if _missing_globals:
    raise RuntimeError(
        "CELL 6c needs %s, which CELL 6 defines. Run CELL 6 first (and CELL 4"
        " and 5 before it if the kernel restarted). Nothing here is broken."
         % " and ".join("`%s`" % g for g in _missing_globals))
if not frames:                                                  # noqa: F821
    raise RuntimeError(
        "CELL 6 ran but `frames` is empty -- no cell survived the gate, so "
        "there is no labelled frame to measure. Fix the gate failures first; "
        "CELL 6 printed the reasons per cell.")

S1_DIR = OUTPUT_DIR + "/s1"                             # noqa: F821
os.makedirs(S1_DIR, exist_ok=True)

RHO_A_SWEEP = (100.0, 200.0, 300.0, 400.0)

# ---- pass 1: per-cell spine geometry, and the pooled boundary -------------
spine_frames, s1_records = {}, []
tip_audits, spine_profiles, f_bracket_by_mode = {}, {}, {}

for nid, fr in frames.items():                                  # noqa: F821
    df_lab = fr["raw"]                       # pre-prune, raw nm, head/neck
    spine_df = sg.build_spine_geometry(df_lab, nid=nid, input_units="nm",
                                       cap_tips=CAP_TIPS,   # noqa: F821
                                       cap_h_um=CAP_H_UM)   # noqa: F821
    spine_frames[nid] = spine_df

    # Gate 1 + the meridian profiles for the gallery. Both are recorded
    # whether or not the cap is enabled: the audit is what tells you whether
    # enabling it would be legitimate, so it has to come first.
    _node, _children, _root = sd._prepare_nodes(
        df_lab, sd.SHAFT_REGEX, sd.SPINE_LABELS, sd.DEFAULT_RADIUS_NM, "nm")
    tip_audits[nid] = spc.audit_tips(_node, _children, root=_root)
    spine_profiles[nid] = spc.spine_profiles(
        _node, _children, h_um=(CAP_H_UM if CAP_TIPS else None),  # noqa: F821
        max_n=20, sort_by="area")

    # the F bracket, per cell. Three build_phi calls; they differ only in the
    # tip closure, so any other difference between them is a bug.
    f_bracket_by_mode.setdefault("no cap", {})
    f_bracket_by_mode.setdefault("flat disc", {})
    f_bracket_by_mode.setdefault("cap h=%.0fnm" % (CAP_H_UM * 1000), {})  # noqa: F821
    for _lab, _kw in (("no cap", dict(cap_tips=False)),
                      ("flat disc", dict(cap_tips=True, cap_h_um=0.0)),
                      ("cap h=%.0fnm" % (CAP_H_UM * 1000),               # noqa: F821
                       dict(cap_tips=True, cap_h_um=CAP_H_UM))):         # noqa: F821
        f_bracket_by_mode[_lab][nid] = float(sd.cell_f_implied_from_phi(
            sd.build_phi(df_lab, nid=nid, input_units="nm", **_kw)))

    _ta = spc.summarise_audit(tip_audits[nid], h_um=CAP_H_UM)  # noqa: F821
    print("  tips: %d true leaf (capped), %d label-boundary (NOT capped), "
          "mean r_t %.3f um" % (_ta["spine_n_capped"],
                                _ta["spine_n_label_boundary_end"],
                                _ta["spine_mean_r_tip_um"]))
    print("       cap would add %.2f um2 spine / %.2f um2 shaft"
          % (_ta["spine_total_cap_um2"], _ta["other_total_cap_um2"]))

    rq = ppc.radius_report(df_lab) if _HAVE_RADIUS_REPORT else None
    summ = sg.cell_spine_summary(spine_df, rho_a_ohm_cm=RHO_A_SWEEP,
                                 radius_report=rq)
    summ["nid"] = nid
    s1_records.append(summ)

    path = "%s/neuron_%s_spine_geometry.csv" % (S1_DIR, nid)
    spine_df.to_csv(path, index=False)

    trust = summ.get("resistance_trustworthy")
    flag = "" if trust is not False else "   [!] RADII SUSPECT"
    print("neuron %s: %d spines, %.0f%% with a labelled neck%s"
           % (nid, summ["n_spines"], 100.0 * summ.get("frac_with_neck", 0.0),
             flag))
    if summ.get("n_with_neck"):
        print("    L_neck median %.3f um, d_neck_equiv median %.3f um"
               % (summ["L_neck_median_um"], summ["d_neck_equiv_median_um"]))
        for rho in RHO_A_SWEEP:
            k = "R_neck_MOhm_rho%d" % int(rho)
            print("    R_neck at rho=%3.0f ohm cm:  p05 %7.1f  median %7.1f  "
                  "p95 %7.1f MOhm"
                   % (rho, summ[k + "_p05"], summ[k + "_median"],
                     summ[k + "_p95"]))

# ---- pass 2: pooled bounds, then per-cell truncation ---------------------
_frames_for_bounds = [(nid, fr["raw"]) for nid, fr in frames.items()]  # noqa: F821
bounds = tf.pool_axis_bounds(_frames_for_bounds, input_units="nm")

print("\npooled boundary over %d cell(s), %d nodes"
       % (bounds["n_cells"], bounds["n_nodes"]))
print("  x %s   y %s   z %s   (um)"
       % tuple(tuple(round(v, 1) for v in bounds[a]) for a in "xyz"))
print("  z_range_fraction_of_slab = %.3f" % bounds["z_range_fraction_of_slab"])
if bounds["z_range_fraction_of_slab"] < 0.5:
    print("  [!] the pooled cells span less than half the ~170 um H01 depth, "
          "so the z bound is an underestimate of the true slab face and the "
          "z-boundary signal will UNDER-report truncation. Pool more cells "
          "before trusting it; the taper signal is unaffected.")

trunc_frames = {}
for nid, fr in frames.items():                                  # noqa: F821
    trunc = tf.build_truncation_table(fr["raw"], bounds, nid=nid,
                                      input_units="nm")
    trunc_frames[nid] = trunc
    tsumm = tf.cell_truncation_summary(trunc)
    trunc.to_csv("%s/neuron_%s_truncation.csv" % (S1_DIR, nid),
                 index=False)
    for rec in s1_records:
        if rec["nid"] == nid:
            rec["n_tips"] = tsumm["n_tips"]
            rec["n_truncated"] = tsumm["n_truncated"]
            rec["frac_truncated"] = tsumm["frac_truncated"]
            rec["truncation_basis_counts"] = json.dumps(
                tsumm["basis_counts"], sort_keys=True)
    print("neuron %s: %d tips, %d truncated (%.0f%%), basis %s"
           % (nid, tsumm["n_tips"], tsumm["n_truncated"],
             100.0 * tsumm["frac_truncated"], tsumm["basis_counts"]))

s1_df = pd.DataFrame(s1_records)
s1_df.to_csv("%s/s1_summary.csv" % S1_DIR, index=False)
print("\nwrote %s/s1_summary.csv  (%d cells)"
       % (S1_DIR, len(s1_df)))

# Commented out IPython magic to ensure Python compatibility.

# =========================================================================== #
# CELL 6c -- NEW. Paste immediately after CELL 6.                             #
# =========================================================================== #
# Reads `frames` from CELL 6, or rebuilds it from the skeletons if absent.
# Runs in two passes because the truncation boundary estimate is POOLED: it
# needs every cell's extent before it can judge any single cell's tips.

import json

import numpy as np
import pandas as pd

import spine_cap as spc
import spine_cap_plots as scp
import spine_density as sd
import spine_geometry as sg
import truncation_flag as tf

try:
    import phi_pipeline_colab as ppc
    _HAVE_RADIUS_REPORT = True
except ImportError:
    _HAVE_RADIUS_REPORT = False
    print("WARNING: phi_pipeline_colab not uploaded -- the authoritative "
          "radius gate is unavailable, and every resistance printed below "
          "must be treated as unverified. Upload it and re-run this cell.")

# CELL 6c gets its labelled frames from CELL 6, which parks them in `frames`.
# If that is not available -- kernel restarted, CELL 6 modified, or CELL 6 run
# without return_frames=True -- this cell REBUILDS them from the skeletons
# rather than failing. Rebuilding is the same operation CELL 6 performs
# (read the CSV, run the labeller at the exporter's threshold); it costs one
# labeller pass per cell and needs nothing from CELL 6's namespace.
#
# Note `records` cannot substitute for `frames`: CELL 6 does
# res.pop("frames"), which REMOVES the labelled frame from the record, so the
# labelled geometry survives only in `frames`.

import os
import sys

_ns = globals()          # not dir(): explicit, and correct inside a
                         # comprehension on every Python version

def _s1_have(name):
    return name in _ns and _ns[name] is not None

if not _s1_have("OUTPUT_DIR"):
    raise RuntimeError(
        "CELL 6c needs OUTPUT_DIR, which CELL 4 defines. Run CELL 4 first.")

_frames = _ns.get("frames") if _s1_have("frames") else None

if not _frames:
    # -- diagnose before deciding, so a surprising namespace is visible ------
    _relevant = sorted(k for k in _ns
                       if not k.startswith("_")
                       and ("frame" in k.lower() or k in
                            ("records", "NEURON_IDS", "SKELETONS_DIR",
                             "gated_out", "failures")))
    print("`frames` is not available. Related names in the namespace: %s"
           % (_relevant if _relevant else "none"))

    _can_rebuild = _s1_have("NEURON_IDS") and _s1_have("SKELETONS_DIR")
    if not _can_rebuild:
        raise RuntimeError(
            "`frames` is missing and it cannot be rebuilt either, because "
            "NEURON_IDS and/or SKELETONS_DIR are not defined. Run CELL 4, "
            "then CELL 6 -- or set those two and re-run this cell to rebuild "
            "from the skeletons directly.")

    import pandas as _pd
    import spine_labeller as _sl
    import morphology_exporter as _mx

    _thr = _mx.SPINE_LENGTH_THRESHOLD_NM
    print("rebuilding labelled frames from %s (threshold %.0f nm, the "
          "exporter's own value) for %d cell(s)..."
           % (SKELETONS_DIR, _thr, len(NEURON_IDS)))                # noqa: F821

    _frames = {}
    for _nid in NEURON_IDS:                                        # noqa: F821
        _path = "%s/neuron_%s.csv" % (SKELETONS_DIR, _nid)         # noqa: F821
        if not os.path.isfile(_path):
            print("   skipping %s: no skeleton at %s" % (_nid, _path))
            continue
        _out = _sl.label_dendritic_spines_robust(
            [_nid], input_dir=SKELETONS_DIR, output_dir=None,      # noqa: F821
            spine_length_threshold_nm=_thr)
        _df = _out[_nid] if isinstance(_out, dict) else _out
        _frames[_nid] = {"raw": _df}
    if not _frames:
        raise RuntimeError(
            "rebuild produced nothing -- no skeleton CSV was found in %s for "
            "any id in NEURON_IDS." % SKELETONS_DIR)               # noqa: F821
    print("rebuilt %d labelled frame(s)" % len(_frames))
    print("NOTE these are labelled but NOT gated: CELL 6's propagation gate "
          "has not been applied, so cells that would have been gated out are "
          "included here. For a bank run, prefer re-running CELL 6.")

frames = _frames          # from CELL 6, or rebuilt above

S1_DIR = OUTPUT_DIR + "/s1"                             # noqa: F821
os.makedirs(S1_DIR, exist_ok=True)

RHO_A_SWEEP = (100.0, 200.0, 300.0, 400.0)

# ---- pass 1: per-cell spine geometry, and the pooled boundary -------------
spine_frames, s1_records = {}, []
tip_audits, spine_profiles, f_bracket_by_mode = {}, {}, {}

for nid, fr in frames.items():                                  # noqa: F821
    df_lab = fr["raw"]                       # pre-prune, raw nm, head/neck
    spine_df = sg.build_spine_geometry(df_lab, nid=nid, input_units="nm",
                                       cap_tips=CAP_TIPS,   # noqa: F821
                                       cap_h_um=CAP_H_UM)   # noqa: F821
    spine_frames[nid] = spine_df

    # Gate 1 + the meridian profiles for the gallery. Both are recorded
    # whether or not the cap is enabled: the audit is what tells you whether
    # enabling it would be legitimate, so it has to come first.
    _node, _children, _root = sd._prepare_nodes(
        df_lab, sd.SHAFT_REGEX, sd.SPINE_LABELS, sd.DEFAULT_RADIUS_NM, "nm")
    tip_audits[nid] = spc.audit_tips(_node, _children, root=_root)
    spine_profiles[nid] = spc.spine_profiles(
        _node, _children, h_um=(CAP_H_UM if CAP_TIPS else None),  # noqa: F821
        max_n=20, sort_by="area")

    # the F bracket, per cell. Three build_phi calls; they differ only in the
    # tip closure, so any other difference between them is a bug.
    f_bracket_by_mode.setdefault("no cap", {})
    f_bracket_by_mode.setdefault("flat disc", {})
    f_bracket_by_mode.setdefault("cap h=%.0fnm" % (CAP_H_UM * 1000), {})  # noqa: F821
    for _lab, _kw in (("no cap", dict(cap_tips=False)),
                      ("flat disc", dict(cap_tips=True, cap_h_um=0.0)),
                      ("cap h=%.0fnm" % (CAP_H_UM * 1000),               # noqa: F821
                       dict(cap_tips=True, cap_h_um=CAP_H_UM))):         # noqa: F821
        f_bracket_by_mode[_lab][nid] = float(sd.cell_f_implied_from_phi(
            sd.build_phi(df_lab, nid=nid, input_units="nm", **_kw)))

    _ta = spc.summarise_audit(tip_audits[nid], h_um=CAP_H_UM)  # noqa: F821
    print("  tips: %d true leaf (capped), %d label-boundary (NOT capped), "
          "mean r_t %.3f um" % (_ta["spine_n_capped"],
                                _ta["spine_n_label_boundary_end"],
                                _ta["spine_mean_r_tip_um"]))
    print("       cap would add %.2f um2 spine / %.2f um2 shaft"
          % (_ta["spine_total_cap_um2"], _ta["other_total_cap_um2"]))

    rq = ppc.radius_report(df_lab) if _HAVE_RADIUS_REPORT else None
    summ = sg.cell_spine_summary(spine_df, rho_a_ohm_cm=RHO_A_SWEEP,
                                 radius_report=rq)
    summ["nid"] = nid
    s1_records.append(summ)

    path = "%s/neuron_%s_spine_geometry.csv" % (S1_DIR, nid)
    spine_df.to_csv(path, index=False)

    trust = summ.get("resistance_trustworthy")
    flag = "" if trust is not False else "   [!] RADII SUSPECT"
    print("neuron %s: %d spines, %.0f%% with a labelled neck%s"
           % (nid, summ["n_spines"], 100.0 * summ.get("frac_with_neck", 0.0),
             flag))
    if summ.get("n_with_neck"):
        print("    L_neck median %.3f um, d_neck_equiv median %.3f um"
               % (summ["L_neck_median_um"], summ["d_neck_equiv_median_um"]))
        for rho in RHO_A_SWEEP:
            k = "R_neck_MOhm_rho%d" % int(rho)
            print("    R_neck at rho=%3.0f ohm cm:  p05 %7.1f  median %7.1f  "
                  "p95 %7.1f MOhm"
                   % (rho, summ[k + "_p05"], summ[k + "_median"],
                     summ[k + "_p95"]))

# ---- pass 2: pooled bounds, then per-cell truncation ---------------------
_frames_for_bounds = [(nid, fr["raw"]) for nid, fr in frames.items()]  # noqa: F821
bounds = tf.pool_axis_bounds(_frames_for_bounds, input_units="nm")

print("\npooled boundary over %d cell(s), %d nodes"
       % (bounds["n_cells"], bounds["n_nodes"]))
print("  x %s   y %s   z %s   (um)"
       % tuple(tuple(round(v, 1) for v in bounds[a]) for a in "xyz"))
print("  z_range_fraction_of_slab = %.3f" % bounds["z_range_fraction_of_slab"])
if bounds["z_range_fraction_of_slab"] < 0.5:
    print("  [!] the pooled cells span less than half the ~170 um H01 depth, "
          "so the z bound is an underestimate of the true slab face and the "
          "z-boundary signal will UNDER-report truncation. Pool more cells "
          "before trusting it; the taper signal is unaffected.")

trunc_frames = {}
for nid, fr in frames.items():                                  # noqa: F821
    trunc = tf.build_truncation_table(fr["raw"], bounds, nid=nid,
                                      input_units="nm")
    trunc_frames[nid] = trunc
    tsumm = tf.cell_truncation_summary(trunc)
    trunc.to_csv("%s/neuron_%s_truncation.csv" % (S1_DIR, nid),
                 index=False)
    for rec in s1_records:
        if rec["nid"] == nid:
            rec["n_tips"] = tsumm["n_tips"]
            rec["n_truncated"] = tsumm["n_truncated"]
            rec["frac_truncated"] = tsumm["frac_truncated"]
            rec["truncation_basis_counts"] = json.dumps(
                tsumm["basis_counts"], sort_keys=True)
    print("neuron %s: %d tips, %d truncated (%.0f%%), basis %s"
           % (nid, tsumm["n_tips"], tsumm["n_truncated"],
             100.0 * tsumm["frac_truncated"], tsumm["basis_counts"]))

s1_df = pd.DataFrame(s1_records)
s1_df.to_csv("%s/s1_summary.csv" % S1_DIR, index=False)
print("\nwrote %s/s1_summary.csv  (%d cells)"
       % (S1_DIR, len(s1_df)))

# ---- READ THIS BEFORE QUOTING ANY NUMBER ABOVE --------------------------
# 1. resistance_trustworthy False  ->  every R_neck above is a function of
#    length alone, because the radii are flat or overwhelmingly at the 50 nm
#    fallback. The numbers are arithmetic, not measurement. Nothing else in
#    the output will tell you this.
# 2. frac_with_neck low  ->  the labeller assigns everything to 'head' when a
#    spine path has fewer than 3 distinct nodes. Those spines get G = 0 and
#    are EXCLUDED from the statistics (not counted as zero-resistance), so a
#    low fraction means the quantiles rest on a minority of spines.
# 3. The R_neck spread across the rho_a sweep is the point, not any single
#    row. Published spine-neck resistances span a wide range partly because
#    rho_a is assumed rather than measured, so a result that survives the
#    whole sweep is worth more than one that holds at a single rho_a.
# 4. truncation_basis 'unresolved' means the tip was too short to judge taper
#    AND not near the z bound. It is absence of evidence, not evidence of a
#    real ending -- those tips are left unflagged deliberately.



# %% CELL 8 -- batch plots --------------------------------------------------
# Built from the COMPACT scalar records (and, for rigidity, the six scalars per
# cell kept in CELL 6). No morphology is reloaded and nothing large was held to
# get here -- alignment_plots' three batch functions read only scalars.
if records:
    fig = ap.batch_quality(records)
    saved.append(ap.save_figure(fig, "%s/batch_quality.png" % FIGURE_DIR))
    del fig

    # Guard the exact failure this plot had: every angle NaN produces a valid
    # but EMPTY figure and no error anywhere. Say so loudly instead.
    n_ang = sum(1 for r in records if r.get("angle_from_z_deg") is not None
                and not pd.isna(r.get("angle_from_z_deg")))
    if n_ang == 0:
        print("WARNING: angle_from_z_deg missing on ALL %d records -- the "
              "orientation plot would be empty. Every cell here was resumed "
              "from a checkpoint written before this was computed; delete "
              "those neuron_*_alignment.json files to recompute." % len(
                  records))
    else:
        if n_ang < len(records):
            print("note: angle_from_z_deg present on %d/%d records (the rest "
                  "were resumed from older checkpoints)" % (n_ang, len(records)))
        fig = ap.orientation_consistency(records)
        saved.append(ap.save_figure(fig,
                                    "%s/batch_orientation.png" % FIGURE_DIR))
        del fig

if regression_records:
    fig = ap.rigidity(regression_records)
    saved.append(ap.save_figure(fig, "%s/batch_rigidity.png" % FIGURE_DIR))
    del fig
    bad = [r for r in regression_records if not r["check"]["identical"]]
    if bad:
        detail = "\n".join(
            "  %s: %s" % (r["nid"], r["check"].get("diffs") or "(not recorded)")
            for r in bad)
        raise AssertionError(
            "alignment moved a section 7 quantity on %d cell(s) -- the "
            "transform is not rigid or was applied at the wrong step. Do not "
            "use this bank.\n%s" % (len(bad), detail))
    print("rigidity: every cell bit-identical (%d cells)" % len(
        regression_records))


gc.collect()
print("\n%d figures written to %s" % (len(saved), FIGURE_DIR))



# =========================================================================== #
# CELL 8b -- NEW. Paste after CELL 8 (batch plots), before CELL 9.            #
# =========================================================================== #
# Follows the CELL 7/8 pattern exactly: build a figure, hand it to
# ap.save_figure, append the path to `saved` so it lands in the manifest.
# s1_plots computes nothing -- it only draws what CELL 6c already
# produced, so these figures cannot disagree with s1_summary.csv.
#
# READ THEM IN THIS ORDER. The first is a gate on the other four: if the
# radii are the fallback, everything downstream is describing an artefact.

import s1_plots as s0p
import spine_cap_plots as scp

if "spine_frames" not in dir() or not spine_frames:              # noqa: F821
    print("CELL 6c has not run (or produced nothing) -- no S1 figures to "
          "draw. Run CELL 6c first; it is what builds `spine_frames`.")
else:
    _figs = [
        # 1. GATE. Are the measured dimensions plausible, and are the radii
        #    real? Panel 4 is the one that matters: a single spike at the
        #    fallback means every resistance below is length alone.
        ("s1_neck_geometry",
         s0p.neck_geometry(spine_frames)),                       # noqa: F821

        # 2. Does spine density peak near the ~90 um the literature reports
        #    for human temporal basal dendrites? A peak in the wrong place
        #    points at the labeller, not the biology.
        ("s1_spine_profile",
         s0p.spine_distance_profile(spine_frames)),              # noqa: F821

        # 3. RESULT. R_neck across the rho_a sweep, against the published
        #    range. The width matters more than agreement with any one
        #    source: three of the five references are rodent and they
        #    disagree with each other by ~an order of magnitude.
        ("s1_neck_resistance",
         s0p.neck_resistance_sweep(spine_frames,                 # noqa: F821
                                   rho_a_ohm_cm=RHO_A_SWEEP)),   # noqa: F821

        # 4. RESULT, and the decision figure for assumption A2. If median
        #    kappa is ~1 across the whole grid, relocating spine synapses to
        #    the shaft is close to exact and the spine-resolved export is not
        #    worth building. If it is not, this says by how much.
        ("s1_attenuation",
         s0p.attenuation_factor(spine_frames,                    # noqa: F821
                                rho_a_ohm_cm=RHO_A_SWEEP)),      # noqa: F821
    ]

    if "trunc_frames" in dir() and trunc_frames:                 # noqa: F821
        # 5. Is the taper threshold defensible? Panel 1 is the evidence:
        #    bimodal means the trough calibrates it, unimodal means no
        #    threshold separates the populations and frac_truncated should be
        #    read as a ranking rather than a count.
        _figs.append(("s1_truncation",
                      s0p.truncation_diagnostics(
                          trunc_frames,                          # noqa: F821
                          ratio_threshold=tf.DEFAULT_TAPER_RATIO_THRESHOLD,
                          margin_um=tf.DEFAULT_MARGIN_UM)))      # noqa: F821

    # ---- S1.3 tip-cap figures ------------------------------------------- #
    # READ 7 AND 8 BEFORE 9-12. The audit says whether the correction is
    # legitimate at all; the gallery says whether the reconstruction is.
    if "tip_audits" in dir() and tip_audits:                     # noqa: F821
        # 7. GATE ON THE CAP. True skeleton leaves (which saw the 100 nm
        #    erosion, and are capped) against label-boundary ends (which did
        #    not, and are not). A large boundary count means the labeller
        #    truncates spines mid-structure -- a different problem, and one
        #    that would make the cap wrong rather than approximate.
        _figs.append(("s1_tip_audit",
                      scp.tip_audit(tip_audits)))               # noqa: F821

        # 9. r_t is the ONLY free input: A_cap = pi (r_t^2 + h^2). A spike at
        #    the 50 nm fallback means those caps are an artefact of a missing
        #    radius, not a measurement.
        _figs.append(("s1_tip_radius",
                      scp.tip_radius_distribution(
                          tip_audits, h_um=CAP_H_UM)))          # noqa: F821

        # 10. How much of the answer is h. A_cap / A_disc = 1 + (h/r_t)^2, so
        #     for r_t >> h the cap SHAPE barely matters and r_t dominates.
        _figs.append(("s1_cap_area_curve",
                      scp.cap_area_curve(tip_audits)))          # noqa: F821

    if "spine_profiles" in dir() and spine_profiles:             # noqa: F821
        # 8. GATE ON THE RECONSTRUCTION. Meridian outlines of the 20 largest
        #    spines: exactly the surface whose lateral area is integrated.
        #    Check the "base %" in each panel title -- the base segment runs
        #    from the FULL shaft radius down to the neck and is attributed
        #    wholly to the spine, so it can dominate A_spine.
        _all_prof = [q for v in spine_profiles.values() for q in v]  # noqa: F821
        _all_prof.sort(key=lambda d: -d["A_spine_um2"])
        _figs.append(("s1_spine_gallery",
                      scp.spine_gallery(_all_prof, n_cols=5, n_max=20)))

    if CAP_TIPS and spine_frames:                        # noqa: F821
        # 11. The size of the correction, per spine. Only meaningful with the
        #     cap on; with it off every A_cap_um2 is zero by construction.
        _figs.append(("s1_cap_contribution",
                      scp.cap_contribution(spine_frames)))      # noqa: F821

    if "f_bracket_by_mode" in dir() and f_bracket_by_mode:       # noqa: F821
        # 12. THE DECISION FIGURE. F per cell under all three tip models,
        #     against the published human bands. Report the bracket, never a
        #     point estimate: the cap is an assumption, not a measurement.
        _figs.append(("s1_f_bracket",
                      scp.f_bracket(f_bracket_by_mode)))        # noqa: F821

    if "s1_df" in dir() and len(s1_df) > 1:              # noqa: F821
        # 13. Per-cell rollup. Only worth drawing for more than one cell.
        _figs.append(("s1_batch", s0p.s1_batch(s1_df)))  # noqa: F821

    for _name, _fig in _figs:
        _p = ap.save_figure(_fig, "%s/%s.png" % (FIGURE_DIR, _name))  # noqa: F821
        saved.append(_p)                                         # noqa: F821
        print("  %s" % _p)
        if SHOW_INLINE:                                          # noqa: F821
            from IPython.display import Image, display
            display(Image(filename=_p))

    print("\n%d S1 figure(s) written" % len(_figs))

# WHAT TO LOOK FOR, in one line each:
#   neck_geometry     panel 4 a spike at 0.05 um  -> stop, radii are synthetic
#   spine_profile     peak far from ~90 um        -> suspect the labeller
#   neck_resistance   the SPREAD across rho_a     -> how much is assumption
#   attenuation       median kappa near 1.000     -> A2 is close to exact
#   truncation        panel 1 bimodal             -> threshold is calibratable
#   tip_audit         many red bars               -> STOP, labeller truncates
#   spine_gallery     base % above ~40            -> base attribution dominates
#   tip_radius        spike at 0.05 um            -> those caps are artefacts
#   cap_area_curve    middle panel near 1.0       -> h barely matters, r_t does
#   cap_contribution  median far above ~15%       -> the cap is doing too much
#   f_bracket         bracket wider than the gap  -> cap cannot settle F
#   batch             red bars                    -> those cells are unusable

# Commented out IPython magic to ensure Python compatibility.


# =========================================================================== #
# CELL 9 -- REPLACE. Full rewrite of the existing summary/manifest cell.       #
# =========================================================================== #
# Changes relative to the current CELL 9:
#   * the S1 columns are merged in, guarded so the cell still runs if
#     CELL 6c was skipped;
#   * the merge key is dtype-checked before it is used;
#   * S1 module versions, the pooled boundary, and the syn_uid reports
#     go into the manifest, so a bank can be reproduced from it;
#   * cells whose radii are suspect are called out explicitly at the end,
#     because that is the one condition under which the R_neck columns are
#     arithmetic rather than measurement.
#
# The DataFrame is called `summary` (not `summary_df`). Everything below is a
# drop-in replacement for lines 701-768 of colab_run_s1_full.py.

rows = []
for r in records:                                               # noqa: F821
    d = r.get("alignment", {})
    nd = d.get("neighbour_distance_um", [np.nan])
    qc = r.get("propagation_qc", {})
    rows.append({
        "nid": r["nid"], "qc_status": r["qc_status"],
        "reasons": ";".join(r.get("reasons", [])),
        "n_sections": r.get("n_sections"), "n_branches": r.get("n_branches"),
        "f_implied": r.get("f_implied"), "F_lit": r.get("F_lit"),
        "nearest_ref_um": round(float(np.min(nd)), 1),
        "pairwise_spread_deg": round(
            float(d.get("pairwise_angle_deg_max", np.nan)), 1),
        "angle_from_z_deg": round(float(r.get("angle_from_z_deg", np.nan)), 1),
        "totnsegs": r.get("totnsegs", qc.get("totnsegs")),
        "gate_status": qc.get("qc_status"),
        "gate_dv_soma_mV": qc.get("C4_soma", {}).get("dv_soma_mV"),
        "gate_dv_min_mV": qc.get("dv_min_mV"),
        "gate_monotone_violations": qc.get("C3_monotone", {}).get("n_violations"),
        "n_synapses": r.get("n_synapses"),
        "n_on_pruned_spine": r.get("n_on_pruned_spine"),
        "n_redirected": r.get("n_redirected"),
        "n_unresolved_spine_bases": r.get("n_unresolved_spine_bases"),
        "n_unknown_type": r.get("n_unknown_type"),
        "cm": CM_BASE, "Ra": RA, "Rm_qc": RM_QC,                # noqa: F821
        "k_neighbors": K_NEIGHBORS,                             # noqa: F821
    })

summary = pd.DataFrame(rows)

# --- S1 merge ------------------------------------------------------- #
# Guarded on the NAME, not on a try/except around the merge: a NameError from
# a skipped CELL 6c and a genuine merge bug should not produce the same
# silence.
_S1_COLS = [
    "n_spines", "n_with_neck", "frac_with_neck",
    "A_spine_total_um2", "A_head_total_um2", "A_neck_total_um2",
    "L_neck_median_um", "d_neck_equiv_median_um", "A_head_median_um2",
    "resistance_trustworthy", "radius_frac_at_default_r",
    "radius_radius_suspect",
    "n_tips", "n_truncated", "frac_truncated", "truncation_basis_counts",
]

if "s1_df" in dir() and len(s1_df):                     # noqa: F821
    _s0 = s1_df                                             # noqa: F821

    # R_neck columns depend on RHO_A_SWEEP, so pick them up by pattern rather
    # than hard-coding a rho. Median only here; p05/p95 stay in
    # s1_summary.csv, which carries the full per-cell detail.
    _rcols = sorted(c for c in _s0.columns
                    if c.startswith("R_neck_MOhm_rho") and c.endswith("_median"))
    _want = [c for c in (_S1_COLS + _rcols) if c in _s0.columns]

    # A silent all-NaN merge from an int64/object key mismatch is the single
    # most likely way this goes wrong, and it looks exactly like "CELL 6c
    # produced nothing". Check it rather than discover it later.
    _lk, _rk = summary["nid"].dtype, _s0["nid"].dtype
    if _lk != _rk:
        print("  merge key dtype mismatch: summary.nid is %s, s1_df.nid "
              "is %s -- coercing both to str" % (_lk, _rk))
        summary["nid"] = summary["nid"].astype(str)
        _s0 = _s0.copy()
        _s0["nid"] = _s0["nid"].astype(str)

    # Re-running this cell must not produce _x/_y suffixed duplicates.
    _dupes = [c for c in _want if c in summary.columns]
    if _dupes:
        summary = summary.drop(columns=_dupes)

    summary = summary.merge(_s0[["nid"] + _want], how="left", on="nid")

    _missing = summary.loc[summary["n_spines"].isna(), "nid"].tolist()
    if _missing:
        print("  %d cell(s) passed the gate but have no S1 row: %s"
               % (len(_missing), _missing))
    print("  S1 merge: %d column(s) added" % len(_want))
else:
    print("  S1 columns NOT merged (CELL 6c not run, or it produced no "
          "rows). The summary is still valid; it simply carries no spine "
          "geometry or truncation evidence.")

summary_path = "%s/alignment_summary.csv" % FIGURE_DIR           # noqa: F821
summary.to_csv(summary_path, index=False)
print(summary.to_string(index=False))

# --- manifest ------------------------------------------------------------ #
_module_versions = {"alignment": al.MODULE_VERSION,              # noqa: F821
                    "alignment_plots": ap.MODULE_VERSION,        # noqa: F821
                    "morphology_exporter": mx.MODULE_VERSION,    # noqa: F821
                    "hoc_qc": hq.MODULE_VERSION,                 # noqa: F821
                    "node_classify": nc.MODULE_VERSION,          # noqa: F821
                    "synapse_redirect_audit": sra.MODULE_VERSION}  # noqa: F821
for _name, _mod in (("spine_geometry", "sg"), ("truncation_flag", "tf"),
                    ("syn_uid", "su"), ("spine_density", "sd"),
                    ("spine_cap", "spc"), ("spine_cap_plots", "scp")):
    if _mod in dir():
        _module_versions[_name] = eval(_mod).MODULE_VERSION      # noqa: S307

_s1_manifest = None
if "s1_df" in dir() and len(s1_df):                      # noqa: F821
    _s1_manifest = {
        "n_cells": int(len(s1_df)),                          # noqa: F821
        "summary_csv": "%s/s1_summary.csv" % S1_DIR,      # noqa: F821
        "rho_a_sweep_ohm_cm": list(RHO_A_SWEEP),                  # noqa: F821
        "pooled_bounds_um": {k: list(bounds[k]) for k in "xyz"},  # noqa: F821
        "pooled_n_cells": bounds["n_cells"],                      # noqa: F821
        "pooled_n_nodes": bounds["n_nodes"],                      # noqa: F821
        "z_range_fraction_of_slab": bounds["z_range_fraction_of_slab"],  # noqa: F821, E501
        "taper_ratio_threshold": tf.DEFAULT_TAPER_RATIO_THRESHOLD,  # noqa: F821
        "reference_path_um": tf.DEFAULT_REFERENCE_PATH_UM,        # noqa: F821
        "boundary_margin_um": tf.DEFAULT_MARGIN_UM,               # noqa: F821
        "n_cells_radius_suspect": int(
            (summary["resistance_trustworthy"] == False).sum())   # noqa: E712
        if "resistance_trustworthy" in summary.columns else None,
    }

manifest = {
    "module_versions": _module_versions,
    "metadata_csv": METADATA_CSV,                                # noqa: F821
    "n_references": int(len(metadata_df)),                       # noqa: F821
    "k_neighbors": K_NEIGHBORS,                                  # noqa: F821
    "segmentation": {"cm": CM_BASE, "Ra": RA, "lambda_f": 100.0,  # noqa: F821
                     "d_lambda": 0.1, "nsegs_method": "lambda_f"},
    "propagation_gate": {"Rm_ohm_cm2": RM_QC,                    # noqa: F821
                         "g_pas_S_cm2": 1.0 / RM_QC,             # noqa: F821
                         "amp_nA": hq.DEFAULT_AMP_NA,            # noqa: F821
                         "dur_ms": hq.DEFAULT_DUR_MS,            # noqa: F821
                         "dt_ms": hq.DEFAULT_DT_MS,              # noqa: F821
                         "monotone_rtol": hq.MONOTONE_RTOL,      # noqa: F821
                         "soma_window_mV": [hq.SOMA_DV_MIN_MV,   # noqa: F821
                                            hq.SOMA_DV_MAX_MV]},  # noqa: F821
    "domain_split": "retired -- every dendrite is 'dend'",
    "synapse_redirect": {"enabled": RUN_SYNAPSE_REDIRECT,        # noqa: F821
                         "synapses_dir": SYNAPSES_DIR,           # noqa: F821
                         "direction": SYNAPSE_DIRECTION,         # noqa: F821
                         "voxel_res_nm": list(VOXEL_RES_NM)},    # noqa: F821
    "syn_uid": ({str(k): v for k, v in syn_uid_reports.items()}  # noqa: F821
                if "syn_uid_reports" in dir() else None),
    "s1": _s1_manifest,
    "neuron_ids": list(NEURON_IDS),                              # noqa: F821
    "n_aligned": len(records),                                   # noqa: F821
    "gated_out": gated_out, "quarantined": quarantined,          # noqa: F821
    "failures": failures, "figures": saved,                      # noqa: F821
    "summary_csv": summary_path,
}
with open("%s/alignment_manifest.json" % FIGURE_DIR, "w",        # noqa: F821
          newline="\n") as fh:
    fh.write(json.dumps(manifest, indent=2, sort_keys=True, default=str))

if failures:                                                     # noqa: F821
    print("\nFAILURES:")
    for f in failures:                                           # noqa: F821
        print("  %s: %s" % (f["nid"], f["error"]))

# The one warning that must not be buried: a cell with flat or
# fallback-dominated radii yields R_neck values that look entirely plausible
# against the published range and mean nothing, because they are a function
# of neck LENGTH alone. Nothing else in this table distinguishes them.
if "resistance_trustworthy" in summary.columns:
    _bad = summary.loc[summary["resistance_trustworthy"] == False,  # noqa: E712
                       "nid"].tolist()
    if _bad:
        print("\n  [!] %d cell(s) with SUSPECT RADII -- every R_neck and "
              "d_neck_equiv column above is arithmetic, not measurement: %s"
               % (len(_bad), _bad))
    else:
        print("\n  radii OK on all %d cell(s); R_neck columns are usable"
               % len(summary))

print("\nmanifest: %s/alignment_manifest.json" % FIGURE_DIR)     # noqa: F821

