# -*- coding: utf-8 -*-
"""Transcriptomics_Proteomics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-qjgb5ruejNS6uHiyX06EbKGpYWDZw0
"""

import os
from google.colab import drive

# This will prompt you to authorize Colab to access your Drive
drive.mount('/content/drive',force_remount=True)



import pandas as pd
import numpy as np



path = '/content/drive/MyDrive/Colab Notebooks/MTG SMART Seq/human_MTG_gene_expression_matrices_2018-06-14/'


os.chdir(path)






# ==============================================================================
# Step 1: Define targets and load the metadata
# ==============================================================================
# Define the ion channels you want to investigate
target_genes = ['HCN1', 'SCN8A', 'KCNQ2', 'CACNA1C']

print("Loading metadata...")
# Load sample metadata (Columns = Nuclei)
meta_df = pd.read_csv('human_MTG_2018-06-14_samples-columns.csv', index_col='sample_name')

# Load gene metadata without forcing the index first, so we can see the exact column names
genes_df = pd.read_csv('human_MTG_2018-06-14_genes-rows.csv')

# Set the index to the correct column name based on your file
genes_df = genes_df.set_index('entrez_id')

# Find the Entrez IDs for our target genes (using the 'gene' column instead of 'gene_symbol')
target_entrez_ids = genes_df[genes_df['gene'].isin(target_genes)].index.astype(str)

# Create a dictionary to map the IDs back to the human-readable names later
gene_mapping = genes_df.loc[target_entrez_ids.astype(int), 'gene'].to_dict()

print(f"Successfully mapped target genes to Entrez IDs: {gene_mapping}")

# ==============================================================================
# Step 2: Filter for Neurons only
# ==============================================================================
# Keep only GABAergic and Glutamatergic cells
neurons_meta = meta_df[meta_df['class'].isin(['GABAergic', 'Glutamatergic'])]
neuron_sample_names = neurons_meta.index.astype(str)
print(f"Filtered down to {len(neuron_sample_names)} neurons.")

# ==============================================================================
# Step 3: Extract Raw Counts (Memory Efficiently)
# ==============================================================================
# The matrices have Genes as Rows and Cells as Columns.
# Loading the entire 2GB matrix takes a lot of RAM. We will use 'skiprows' to
# only load the rows corresponding to our target ion channels.

def get_target_counts(matrix_path, target_ids):
    # First, read just the header to get the column names (sample_names)
    header = pd.read_csv(matrix_path, nrows=0)

    # We need to find which row numbers correspond to our target Entrez IDs
    # In Allen data, the first column is the Entrez ID.
    all_entrez_ids = pd.read_csv(matrix_path, usecols=[0], dtype=str).iloc[:, 0]
    target_row_indices = all_entrez_ids[all_entrez_ids.isin(target_ids)].index + 1 # +1 for header

    # Now read only those specific rows
    counts = pd.read_csv(matrix_path, skiprows=lambda x: x not in [0] + target_row_indices.tolist(), index_col=0)

    # Keep only the columns that correspond to our filtered neurons
    valid_cols = [col for col in counts.columns if col in neuron_sample_names]
    return counts[valid_cols]

print("Extracting Exon counts...")
exon_counts = get_target_counts('human_MTG_2018-06-14_exon-matrix.csv', target_entrez_ids)

print("Extracting Intron counts...")
intron_counts = get_target_counts('human_MTG_2018-06-14_intron-matrix.csv', target_entrez_ids)

# Combine Exon and Intron counts
total_counts = exon_counts + intron_counts

# Rename the index from Entrez IDs back to readable Gene Symbols
total_counts.index = total_counts.index.astype(int).map(gene_mapping)

# Transpose so that Cells are Rows and Genes are Columns (standard data science format)
cell_gene_matrix = total_counts.T

# ==============================================================================
# Step 4: Calculate CPM and Merge with Metadata
# ==============================================================================
print("Calculating CPM...")
# To calculate true CPM, we need the total library size per cell.
# The metadata provides 'total_reads' and 'percent_aligned_reads_total'.
# Total Mapped Reads = total_reads * (percent_aligned_reads_total / 100)
library_sizes = neurons_meta['total_reads'] * (neurons_meta['percent_aligned_reads_total'] / 100)

# Calculate CPM: (Gene Count / Total Mapped Reads) * 1,000,000
cpm_matrix = cell_gene_matrix.div(library_sizes, axis=0) * 1e6

# Merge the CPM data with the layer and cluster metadata
analysis_df = neurons_meta[['brain_subregion', 'cluster', 'class']].join(cpm_matrix)

# ==============================================================================
# Updated Step 5: Summarize by Layer AND Cell Class
# ==============================================================================
print("Summarizing data by Layer and Class...")

def summarize(df, genes):
    summary = {}
    for gene in genes:
        cpm_values = df[gene]

        # 1. Penetrance (% Expressing)
        summary[f'{gene}_%_Expressing'] = (cpm_values > 0).mean() * 100

        # 2. Median CPM
        summary[f'{gene}_Median_CPM'] = cpm_values.median()

        # 3. Mean of Log2(CPM + 1)
        # We use np.log2(x + 1) to avoid log(0) errors
        summary[f'{gene}_Mean_Log2_CPM'] = np.log2(cpm_values + 1).mean()

    return pd.Series(summary)

# Group by BOTH 'brain_subregion' (Layer) and 'class' (Excitatory/Inhibitory)
layer_class_summary = analysis_df.groupby(['brain_subregion', 'class']).apply(
    lambda x: summarize(x, target_genes)
).reset_index()

# Drop rows where the combination doesn't exist
layer_class_summary = layer_class_summary.dropna()

print("Summary complete! Preview:")
print(layer_class_summary.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def create_faceted_dot_plot(summary_df, genes, color_metric='Log2'):
    """
    Transforms the summary dataframe and plots a split Dot Plot.

    Parameters:
    - summary_df: The aggregated dataframe from Step 5.
    - genes: List of target genes to plot.
    - color_metric: 'Log2' (uses Mean_Log2_CPM) or 'Median' (uses Median_CPM) for color saturation.
    """
    # Validate the metric choice
    if color_metric not in ['Log2', 'Median']:
        raise ValueError("color_metric must be either 'Log2' or 'Median'")

    # Set the target column based on the user's choice
    hue_target = 'Mean_Log2_CPM' if color_metric == 'Log2' else 'Median_CPM'

    # ==========================================
    # 1. Reshape Data (Wide to Long Format)
    # ==========================================
    records = []
    for index, row in summary_df.iterrows():
        layer = row['brain_subregion']
        cell_class = row['class']

        for gene in genes:
            if f'{gene}_Median_CPM' in row:
                records.append({
                    'Layer': layer,
                    'Cell_Class': cell_class,
                    'Gene': gene,
                    'Median_CPM': row[f'{gene}_Median_CPM'],
                    'Mean_Log2_CPM': row[f'{gene}_Mean_Log2_CPM'],
                    '%_Expressing': row[f'{gene}_%_Expressing']
                })

    long_df = pd.DataFrame(records)

    # Enforce anatomical layer order
    layer_order = ['L1', 'L2', 'L3', 'L4', 'L5', 'L6']
    long_df = long_df[long_df['Layer'].isin(layer_order)]
    long_df['Layer'] = pd.Categorical(long_df['Layer'], categories=layer_order, ordered=True)

    # Reverse the gene list so the first gene appears at the top
    long_df['Gene'] = pd.Categorical(long_df['Gene'], categories=list(reversed(genes)), ordered=True)

    # ==========================================
    # 2. Generate the Faceted Plot
    # ==========================================
    sns.set_theme(style="whitegrid")

    g = sns.relplot(
        data=long_df,
        x='Layer',
        y='Gene',
        size='%_Expressing',
        hue=hue_target,          # Driven by the chosen metric
        col='Cell_Class',
        palette='Blues',         # Updated to single-hue Blues palette
        sizes=(20, 600),
        alpha=0.9,               # Slight increase in opacity for Blues
        edgecolor='black',
        linewidth=0.5,
        height=5,
        aspect=0.8
    )

    # ==========================================
    # 3. Formatting and Aesthetics
    # ==========================================
    title_metric = "Log2(CPM + 1)" if color_metric == 'Log2' else "Median CPM"
    g.fig.suptitle(f'Ion Channel Expression (Color = {title_metric})', fontsize=16, y=1.05)

    g.set_titles(col_template="{col_name} Neurons", size=14, pad=10)
    g.set_axis_labels("Cortical Layer", "Target Genes")

    for ax in g.axes.flat:
        ax.margins(y=0.15, x=0.1)
        ax.xaxis.grid(False)
        ax.yaxis.grid(True, linestyle='--', alpha=0.7)

    sns.move_legend(g, "upper left", bbox_to_anchor=(1, 1), title="Metrics", frameon=True)

    plt.show()

# ==========================================
# Run the Function!
# ==========================================
target_genes = ['HCN1', 'SCN8A', 'KCNQ2', 'CACNA1C']
# target_genes = ['HCN1']
create_faceted_dot_plot(layer_class_summary, target_genes, color_metric='Log2')