# -*- coding: utf-8 -*-
"""Utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGZK3SXYwshXunpdbkvmEPcZtCHHB_gm
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)
import os
import pandas as pd
import plotly.graph_objects as go
import plotly.colors as pc
!pip install -q -U kaleido
def plot_centered_neuron_gallery(neuron_ids, input_dir='/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons', shift_nm=400000):
    """
    Loads, centers, and sequentially shifts neurons for visualization in a single Plotly 3D space.

    Args:
        neuron_ids (list): List of neuron IDs to process.
        input_dir (str): Folder path containing the reconstructed CSVs.
        shift_nm (float): Distance to shift each subsequent neuron (default 100,000 nm = 100 um).
    """
    fig = go.Figure()

    # Generate a robust color palette capable of handling many neurons
    colors = pc.qualitative.Alphabet * (len(neuron_ids) // 26 + 1)

    valid_count = 0

    for nid in neuron_ids:
        filepath = os.path.join(input_dir, f"neuron_{nid}.csv")

        if not os.path.exists(filepath):
            print(f"⚠️ File for neuron {nid} not found. Skipping.")
            continue

        df = pd.read_csv(filepath)
        root_rows = df[df['p'] == -1]

        if root_rows.empty:
            print(f"⚠️ No root node (p=-1) found for neuron {nid}. Skipping.")
            continue

        # 1. Center the neuron to (0,0,0)
        soma_x = root_rows.iloc[0]['x']
        soma_y = root_rows.iloc[0]['y']
        soma_z = root_rows.iloc[0]['z']

        df['x'] = df['x'] - soma_x
        df['y'] = df['y'] - soma_y
        df['z'] = df['z'] - soma_z

        # 2. Apply sequential shift (100 um = 100,000 nm along the X-axis)
        current_shift = valid_count * shift_nm
        df['x'] = df['x'] + current_shift

        # 3. Prepare fast line segments for Plotly
        node_map = df.set_index('id')[['x', 'y', 'z']].to_dict('index')
        x_lines, y_lines, z_lines = [], [], []

        # Filter for valid parent-child connections
        valid_segments = df[df['p'] != -1]

        for _, row in valid_segments.iterrows():
            pid = row['p']
            if pid in node_map:
                parent = node_map[pid]
                x_lines.extend([row['x'], parent['x'], None])
                y_lines.extend([row['y'], parent['y'], None])
                z_lines.extend([row['z'], parent['z'], None])

        neuron_color = colors[valid_count]

        # Add Skeleton Trace
        fig.add_trace(go.Scatter3d(
            x=x_lines, y=y_lines, z=z_lines,
            mode='lines',
            line=dict(color=neuron_color, width=2),
            name=f"Neuron {nid}",
            hoverinfo='name'
        ))



        print(f"✅ Neuron {nid} loaded, centered, shifted by {current_shift} nm, and plotted.")
        valid_count += 1

    if valid_count == 0:
        print("❌ No valid neurons were found to plot.")
        return

    # 4. Finalize Layout
    fig.update_layout(
        title=f"Gallery of {valid_count} Centered & Shifted Neurons (Shift: {shift_nm/1000} um)",
        scene=dict(
            xaxis_title='X (nm)',
            yaxis_title='Y (nm)',
            zaxis_title='Z (nm)',
            aspectmode='data', # Crucial to maintain true biological proportions
            bgcolor='white',
            xaxis=dict(showbackground=False),
            yaxis=dict(showbackground=False),
            zaxis=dict(showbackground=False)
        ),
        height=800,
        margin=dict(l=0, r=0, b=0, t=50),
        legend=dict(x=1.05, y=0.5)
    )

    fig.show()

"""# L3 INH"""

# --- Execution ---
target_ids = [38498268698, 38528200714, 39357639147] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L3 EXC"""

# --- Execution ---
target_ids = [3751741567, 3939175098, 4159197067] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L4 INH"""

# --- Execution ---
target_ids = [3371182357, 3384409625, 4724884080] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L4 EXC"""

# --- Execution ---
target_ids = [31758037617, 31889708867, 31932067838, 320930285767] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L5 INH"""

# --- Execution ---
target_ids = [5057874043, 6048143049, 6878633373] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L5 EXC"""

# --- Execution ---
target_ids = [4271363320, 6806154524, 25075056945] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L6 INH"""

# --- Execution ---
target_ids = [32757608869, 32787700968, 41318231330] # Your array here
plot_centered_neuron_gallery(target_ids)

"""L6 EXC"""

# --- Execution ---
target_ids = [33429005975, 32732918048, 5870930712] # Your array here
plot_centered_neuron_gallery(target_ids)

"""## Total lengths analysis"""

import os
import numpy as np
import pandas as pd

def calculate_total_arbor_lengths(neuron_ids, input_dir='/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons'):
    """
    Iteratively imports neurons and calculates their total arbor length.
    Uses vectorized NumPy operations for extremely fast Euclidean distance calculations.

    Args:
        neuron_ids (list): Array/List of neuron IDs to process.
        input_dir (str): Folder path containing the reconstructed CSVs.

    Returns:
        pd.DataFrame: A DataFrame containing the neuron IDs and their total lengths.
    """
    results = []

    print(f"📏 Calculating arbor lengths for {len(neuron_ids)} neurons...\n")

    for nid in neuron_ids:
        filepath = os.path.join(input_dir, f"neuron_{nid}.csv")

        # 1. Check if file exists
        if not os.path.exists(filepath):
            print(f"⚠️ File for neuron {nid} not found. Skipping.")
            results.append({'neuron_id': nid, 'total_length_nm': np.nan, 'total_length_um': np.nan})
            continue

        # 2. Load the DataFrame
        df = pd.read_csv(filepath)

        # Ensure required columns exist
        if not all(col in df.columns for col in ['id', 'p', 'x', 'y', 'z']):
            print(f"⚠️ Missing necessary coordinate/parent columns in {nid}. Skipping.")
            results.append({'neuron_id': nid, 'total_length_nm': np.nan, 'total_length_um': np.nan})
            continue

        # 3. Vectorized length calculation
        # Merge the dataframe with itself to align each node's coordinates with its parent's coordinates
        segments = df.merge(
            df[['id', 'x', 'y', 'z']],
            left_on='p',
            right_on='id',
            suffixes=('', '_parent')
        )

        # Calculate Euclidean distance for all valid segments at once
        distances = np.sqrt(
            (segments['x'] - segments['x_parent'])**2 +
            (segments['y'] - segments['y_parent'])**2 +
            (segments['z'] - segments['z_parent'])**2
        )

        # Sum all distances to get the total arbor length
        total_length_nm = distances.sum()
        total_length_um = total_length_nm / 1000  # Convert nanometers to micrometers

        print(f"✅ Neuron {nid}: {total_length_um:,.2f} μm")

        # 4. Store results
        results.append({
            'neuron_id': nid,
            'total_length_nm': total_length_nm,
            'total_length_um': total_length_um
        })

    # Return as a Pandas DataFrame for easy viewing and exporting
    return pd.DataFrame(results)


neuron_ids = [



  1539076840, 2776001292, 37173591638, 37581252436, 39052800624, 49331640536, 2616018803, 2892721051, 36590837294, 36955278084, 37463700916, 38776359040, 40218295373, 46634952610, 46899756812


              ]
results = calculate_total_arbor_lengths(neuron_ids)

import pandas as pd
import plotly.graph_objects as go

def plot_histogram_with_median(df, column='total_length_um', title="Distribution of Total Arbor Lengths"):
    """
    Constructs a histogram from a specified DataFrame column and overlays
    a vertical line representing the median value.

    Args:
        df (pd.DataFrame): The DataFrame containing the data.
        column (str): The name of the column to plot.
        title (str): The title of the plot.
    """
    if df is None or df.empty:
        print("❌ DataFrame is empty. Cannot plot.")
        return

    if column not in df.columns:
        print(f"❌ Column '{column}' not found in the DataFrame.")
        return

    # Drop any NaNs (e.g., from files that failed to load in the previous step)
    data = df[column].dropna()

    if data.empty:
        print("❌ No valid numeric data found to plot.")
        return

    # Calculate the median
    median_val = np.min(data)-(np.min(data)*0.1)

    # Initialize the Plotly figure
    fig = go.Figure()

    # Add the Histogram trace
    fig.add_trace(go.Histogram(
        x=data,
        nbinsx=20, # Adjust the number of bins as needed based on your array size
        marker_color='royalblue',
        opacity=0.75,
        name='Distribution'
    ))

    # Overlay the vertical line for the median
    fig.add_vline(
        x=median_val,
        line_width=3,
        line_dash="dash",
        line_color="firebrick",
        annotation_text=f"Median: {median_val:,.2f}",
        annotation_position="top right",
        annotation_font=dict(size=14, color="firebrick")
    )

    # Update the layout for a clean, academic look
    fig.update_layout(
        title=title,
        xaxis_title=f"{column.replace('_', ' ').title()}",
        yaxis_title="Number of Neurons",
        template="plotly_white",
        bargap=0.05, # Adds a small gap between bars
        height=500,
        width=800,
        showlegend=False
    )

    fig.show()

# --- Example Usage ---
# Assuming 'lengths_df' is the DataFrame generated by the previous function:
plot_histogram_with_median(results, column='total_length_um')

"""## Alighment analysis"""

import os
import numpy as np
import pandas as pd
import networkx as nx
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.spatial.transform import Rotation as R

def align_and_plot_neurons_to_z_by_com(neuron_ids, input_dir='/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons', percentile=95, show_plot=True):
    """
    Centers neurons, extracts the distal tail (>95th percentile), filters for Dendrites,
    reconstructs the hierarchy to isolate the largest single distal arbor,
    calculates the CoM alignment vector, rotates the neuron, and plots both
    the pre-rotation assessment and post-rotation result side-by-side.
    """
    aligned_neurons = {}

    print(f"📐 Aligning {len(neuron_ids)} neurons (Threshold: Top {100-percentile}% | Filter: Largest Dendritic Arbor | Vector: CoM only)...")

    for nid in neuron_ids:
        filepath = os.path.join(input_dir, f"neuron_{nid}.csv")

        if not os.path.exists(filepath):
            print(f"⚠️ File for neuron {nid} not found. Skipping.")
            continue

        df = pd.read_csv(filepath)

        # --- 1. Center the Neuron ---
        root_rows = df[df['p'] == -1]
        if root_rows.empty:
            print(f"⚠️ No root node (p=-1) found for {nid}. Skipping.")
            continue

        soma_id = root_rows.iloc[0]['id']
        soma_x, soma_y, soma_z = root_rows.iloc[0][['x', 'y', 'z']]
        df['x'] -= soma_x
        df['y'] -= soma_y
        df['z'] -= soma_z

        # --- 2. Calculate Distances & Isolate the 5% Tail ---
        coords = df[['x', 'y', 'z']].values
        distances = np.linalg.norm(coords, axis=1)
        distal_threshold = np.percentile(distances, percentile)
        distal_mask = distances >= distal_threshold

        # --- 3. Filter for Dendrites ---
        if 'annotated_type' not in df.columns:
            print(f"⚠️ 'annotated_type' missing for {nid}. Skipping.")
            continue

        dendrite_mask = df['annotated_type'].astype(str).str.contains('dendrite|apical|^1$', case=False, regex=True)
        candidate_nodes = set(df[distal_mask & dendrite_mask]['id'].values)

        if not candidate_nodes:
            print(f"⚠️ No distal dendrite points found for {nid}. Skipping.")
            continue

        # --- 4. Reconstruct Hierarchy (NetworkX) ---
        G = nx.DiGraph()
        G.add_nodes_from(df['id'])
        valid_edges = df[df['p'] != -1][['p', 'id']].values
        G.add_edges_from(valid_edges)

        primary_branches = list(G.successors(soma_id))
        largest_pool = []

        for pb in primary_branches:
            arbor_nodes = set(nx.descendants(G, pb))
            arbor_nodes.add(pb)
            pool = candidate_nodes.intersection(arbor_nodes)
            if len(pool) > len(largest_pool):
                largest_pool = list(pool)

        if len(largest_pool) < 5:
            print(f"⚠️ Not enough clustered points (<5) in the largest distal arbor for {nid}. Skipping.")
            continue

        pool_df = df[df['id'].isin(largest_pool)]
        distal_coords = pool_df[['x', 'y', 'z']].values

        # --- 5. Vector Calculation ---
        distal_center = np.mean(distal_coords, axis=0)
        v_com = distal_center / np.linalg.norm(distal_center)

        # --- 6. Calculate & Apply the Rotation ---
        z_axis = np.array([0.0, 0.0, 1.0])
        cross_prod = np.cross(v_com, z_axis)
        dot_prod = np.dot(v_com, z_axis)

        if np.linalg.norm(cross_prod) < 1e-6:
            rot_matrix = np.eye(3)
        else:
            angle = np.arccos(np.clip(dot_prod, -1.0, 1.0))
            rot_vec = (cross_prod / np.linalg.norm(cross_prod)) * angle
            rotation = R.from_rotvec(rot_vec)
            rot_matrix = rotation.as_matrix()

        rotated_coords = np.dot(coords, rot_matrix.T)

        # We also rotate the CoM vector itself so we can plot it in the new aligned space
        rotated_v_com = np.dot(v_com, rot_matrix.T)

        # --- 7. Plotting the Side-by-Side Assessment ---
        if show_plot:
            # Create a 1x2 subplot with 3D scenes
            fig = make_subplots(
                rows=1, cols=2,
                specs=[[{'type': 'scene'}, {'type': 'scene'}]],
                subplot_titles=(f"Pre-Rotation Assessment", f"Post-Rotation (Aligned to Z)")
            )

            # --- PANEL 1: PRE-ROTATION ---
            node_map = df.set_index('id')[['x', 'y', 'z']].to_dict('index')
            x_lines, y_lines, z_lines = [], [], []
            for _, row in df[df['p'] != -1].iterrows():
                pid = row['p']
                if pid in node_map:
                    parent = node_map[pid]
                    x_lines.extend([row['x'], parent['x'], None])
                    y_lines.extend([row['y'], parent['y'], None])
                    z_lines.extend([row['z'], parent['z'], None])

            fig.add_trace(go.Scatter3d(
                x=x_lines, y=y_lines, z=z_lines, mode='lines',
                line=dict(color='lightgrey', width=2), opacity=0.4, name='Original Skeleton', hoverinfo='skip'
            ), row=1, col=1)

            # Rejected Distal Points
            rejected_mask = distal_mask & (~df['id'].isin(largest_pool))
            rejected_df = df[rejected_mask]
            if not rejected_df.empty:
                fig.add_trace(go.Scatter3d(
                    x=rejected_df['x'], y=rejected_df['y'], z=rejected_df['z'],
                    mode='markers', marker=dict(size=2, color='orange', opacity=0.5),
                    name='Rejected Distal Points'
                ), row=1, col=1)

            # Chosen Distal Arbor Pool
            fig.add_trace(go.Scatter3d(
                x=pool_df['x'], y=pool_df['y'], z=pool_df['z'],
                mode='markers', marker=dict(size=4, color='crimson'),
                name=f'Target Arbor Pool (n={len(largest_pool)})'
            ), row=1, col=1)

            # Original CoM Vector
            scale = np.max(distances) * 0.95
            fig.add_trace(go.Scatter3d(
                x=[0, v_com[0]*scale], y=[0, v_com[1]*scale], z=[0, v_com[2]*scale],
                mode='lines+markers', line=dict(color='green', width=6),
                marker=dict(size=6, symbol='diamond'), name='Original CoM Vector'
            ), row=1, col=1)

            # --- PANEL 2: POST-ROTATION (ALIGNED) ---
            # Create a temporary dataframe just to easily map the rotated coordinates for Plotly
            df_rot = df.copy()
            df_rot['x'] = rotated_coords[:, 0]
            df_rot['y'] = rotated_coords[:, 1]
            df_rot['z'] = rotated_coords[:, 2]

            node_map_rot = df_rot.set_index('id')[['x', 'y', 'z']].to_dict('index')
            rx_lines, ry_lines, rz_lines = [], [], []
            for _, row in df_rot[df_rot['p'] != -1].iterrows():
                pid = row['p']
                if pid in node_map_rot:
                    parent = node_map_rot[pid]
                    rx_lines.extend([row['x'], parent['x'], None])
                    ry_lines.extend([row['y'], parent['y'], None])
                    rz_lines.extend([row['z'], parent['z'], None])

            fig.add_trace(go.Scatter3d(
                x=rx_lines, y=ry_lines, z=rz_lines, mode='lines',
                line=dict(color='royalblue', width=2), opacity=0.6, name='Aligned Skeleton', hoverinfo='skip'
            ), row=1, col=2)

            # Rotated CoM Vector (This should point perfectly straight up in the plot)
            fig.add_trace(go.Scatter3d(
                x=[0, rotated_v_com[0]*scale], y=[0, rotated_v_com[1]*scale], z=[0, rotated_v_com[2]*scale],
                mode='lines+markers', line=dict(color='green', width=6),
                marker=dict(size=6, symbol='diamond'), name='Aligned Z-Axis Vector'
            ), row=1, col=2)

            # Layout Setup for both subplots
            fig.update_layout(
                title=f"Neuron {nid} Alignment",
                scene=dict(
                    xaxis_title='X (nm)', yaxis_title='Y (nm)', zaxis_title='Z (nm)',
                    aspectmode='data', bgcolor='white'
                ),
                scene2=dict(
                    xaxis_title='X (nm)', yaxis_title='Y (nm)', zaxis_title='Z (nm)',
                    aspectmode='data', bgcolor='white'
                ),
                height=700, width=1400, margin=dict(l=0, r=0, b=0, t=50)
            )
            fig.show()

        # --- 8. Finalize Data Update ---
        df['x'] = rotated_coords[:, 0]
        df['y'] = rotated_coords[:, 1]
        df['z'] = rotated_coords[:, 2]

        aligned_neurons[nid] = df
        print(f"✅ Neuron {nid} successfully rotated to Z-axis using CoM.\n")

    return aligned_neurons




target_ids = [5629504348,4769650470, 42137844926, 42298018087]
aligned_data = align_and_plot_neurons_to_z_by_com(target_ids,percentile=90, show_plot=True)