#!/bin/bash

#PBS -S /bin/bash
#PBS -N "template_job"
#PBS -q cpu
#PBS -l select=1:ncpus=10,walltime=00:05:00
#PBS -k eo

##########################################################################

# Explanation of the various options:
#
# -S: select the shell to be used (BASH for us)
# -N: name of the job (used e.g. when launching qstat), max 15 character for visualization with qstat 
# -q: name of queue (cpu or gpu for DaVinci-1)
# -l: specifies requested resources
#     select  : number of computational nodes (max 32)
#     ncpus   : number of CPU cores per node  (max 48)
#     walltime: expected execution time (max 72:00:00)
# -k: keep error (e) and output (o) files generated by the job
#     (they will be saved under your HOME directory)

# If you need to use one or more GPUs,
# change the -q and -l options as follows:
#
# #PBS -q gpu
# #PBS -l select=1:ncpus=48:ngpus=4,walltime=12:00:00
#
#     ngpus: number of GPUs per node (max 4)

# For more info and options:
#
# 1) man qsub (from terminal)
# 2) https://pubs.opengroup.org/onlinepubs/9699919799/utilities/qsub.html

##########################################################################


# You can load any module you need

module load python3

# Run the Python script
python3 ./node_test.py


sleep 10s
