# -*- coding: utf-8 -*-
"""Jitter_neurons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmiizFQOYiZnWeXsbGKs5VAa7mm2hpV2
"""

from google.colab import drive

# This will prompt you to authorize Colab to access your Drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from scipy.spatial.transform import Rotation as R
import ast

def rototranslate_and_jitter(input_dir,nid, metadata_df, k_neighbors=3, max_tilt_deg=10.0):
    """
    Loads a raw neuron CSV, calculates the base rototranslation matrix from the
    k-nearest neighbors, applies the alignment, and generates a second version
    with biological jitter (apical tilt + yaw).

    Parameters:
    - filepath: str, path to the raw neuron .csv file.
    - metadata_df: DataFrame, the alignment metadata loaded from CSV.
    - k_neighbors: int, number of nearest neighbors to average for alignment.
    - max_tilt_deg: float, maximum deflection angle for the apical trunk.

    Returns:
    - df_aligned: DataFrame, the strictly aligned neuron (scaled to um).
    - df_jittered: DataFrame, the aligned + jittered neuron (scaled to um).
    """

    # 1. Load the raw data
    filepath = os.path.join(input_dir, f"neuron_{nid}.csv")
    df = pd.read_csv(filepath)
    root_rows = df[df['p'] == -1]

    if root_rows.empty:
        raise ValueError(f"No root node (p == -1) found in {filepath}.")

    # Extract the target soma position in nanometers
    soma_pos = root_rows.iloc[0][['x', 'y', 'z']].values.astype(float)

    # ---------------------------------------------------------
    # STEP 1: CALCULATE THE NEIGHBORHOOD BASE ROTATION
    # ---------------------------------------------------------
    # Ensure rotation matrices in the metadata are properly formatted as arrays
    if isinstance(metadata_df['rotation_matrix'].iloc[0], str):
        metadata_df['rotation_matrix'] = metadata_df['rotation_matrix'].apply(ast.literal_eval)

    # Extract all reference somas from metadata
    reference_somas = metadata_df[['soma_x', 'soma_y', 'soma_z']].values

    # Calculate Euclidean distances to find the nearest neighbors
    distances = np.linalg.norm(reference_somas - soma_pos, axis=1)
    k_actual = min(k_neighbors, len(metadata_df))
    nearest_indices = np.argsort(distances)[:k_actual]
    nearest_metadata = metadata_df.iloc[nearest_indices]

    # Average the rotation matrices of the nearest neighbors
    matrices = np.array(nearest_metadata['rotation_matrix'].tolist())
    mean_matrix = R.from_matrix(matrices).mean().as_matrix()
    base_rotation_matrix = mean_matrix

    # ---------------------------------------------------------
    # STEP 2: BASE ROTOTRANSLATION (Strict Alignment)
    # ---------------------------------------------------------
    # Center the coordinates to the soma
    centered_coords = df[['x', 'y', 'z']].values - soma_pos

    # Apply the base alignment rotation matrix
    aligned_coords = np.dot(centered_coords, base_rotation_matrix.T)

    # Scale from nanometers to micrometers
    aligned_coords_um = aligned_coords / 1000.0

    # Create the strictly aligned DataFrame
    df_aligned = df.copy()
    df_aligned['x'] = aligned_coords_um[:, 0]
    df_aligned['y'] = aligned_coords_um[:, 1]
    df_aligned['z'] = aligned_coords_um[:, 2]

    # ---------------------------------------------------------
    # STEP 3: APPLY BIOLOGICAL JITTER
    # ---------------------------------------------------------
    # Convert max tilt to radians
    max_tilt_rad = np.radians(max_tilt_deg)

    # Draw random rotation angles
    tilt_x = np.random.uniform(-max_tilt_rad, max_tilt_rad)  # Pitch
    tilt_y = np.random.uniform(-max_tilt_rad, max_tilt_rad)  # Roll
    spin_z = np.random.uniform(0, 2 * np.pi)                 # Yaw

    # Construct a Scipy Rotation object using intrinsic Euler angles
    jitter_rot = R.from_euler('xyz', [tilt_x, tilt_y, spin_z], degrees=False)
    jitter_matrix = jitter_rot.as_matrix()

    # Apply the jitter matrix to the ALIGNED coordinates.
    jittered_coords_um = np.dot(aligned_coords_um, jitter_matrix.T)

    # Create the jittered DataFrame
    df_jittered = df.copy()
    df_jittered['x'] = jittered_coords_um[:, 0]
    df_jittered['y'] = jittered_coords_um[:, 1]
    df_jittered['z'] = jittered_coords_um[:, 2]

    # CRITICAL CHANGE: Now returning the matrix as well!
    return df_aligned, df_jittered, jitter_matrix
import plotly.graph_objects as go
import numpy as np

import plotly.graph_objects as go
import numpy as np

def plot_aligned_vs_jittered(df_aligned, df_jittered, jitter_matrix, x_offset=300.0):
    """
    Creates an interactive 3D plot comparing the aligned and jittered neuron skeletons.
    The jittered skeleton and its axis are displaced along the X dimension for clarity.
    """
    fig = go.Figure()

    # ---------------------------------------------------------
    # HELPER: Build Plotly Line Segments
    # ---------------------------------------------------------
    def build_segments(df):
        """Extracts parent-child nodes into a single list separated by None."""
        node_map = df.set_index('id')[['x', 'y', 'z']].to_dict('index')
        seg_x, seg_y, seg_z = [], [], []

        for _, row in df[df['p'] != -1].iterrows():
            pid = row['p']
            if pid in node_map:
                parent = node_map[pid]
                seg_x.extend([row['x'], parent['x'], None])
                seg_y.extend([row['y'], parent['y'], None])
                seg_z.extend([row['z'], parent['z'], None])

        return seg_x, seg_y, seg_z

    # ---------------------------------------------------------
    # TRACE 1: Strictly Aligned Skeleton (Original Position)
    # ---------------------------------------------------------
    ax, ay, az = build_segments(df_aligned)
    fig.add_trace(go.Scatter3d(
        x=ax, y=ay, z=az,
        mode='lines',
        line=dict(color='royalblue', width=2),
        opacity=0.5,
        name='Strictly Aligned',
        hoverinfo='skip'
    ))

    # ---------------------------------------------------------
    # TRACE 2: Jittered Skeleton (Displaced)
    # ---------------------------------------------------------
    jx, jy, jz = build_segments(df_jittered)

    # Apply the spatial offset to the X coordinates (ignoring 'None' separators)
    jx_offset = [x + x_offset if x is not None else None for x in jx]

    fig.add_trace(go.Scatter3d(
        x=jx_offset, y=jy, z=jz,
        mode='lines',
        line=dict(color='crimson', width=3),
        opacity=0.9,
        name='Jittered Morphology',
        hoverinfo='skip'
    ))

    # ---------------------------------------------------------
    # TRACE 3 & 4: The Axes
    # ---------------------------------------------------------
    # Find a good scale length based on the neuron's apical height
    axis_length = df_aligned['z'].max() if not np.isnan(df_aligned['z'].max()) else 500.0

    # True Z-Axis (Vertical, at origin)
    fig.add_trace(go.Scatter3d(
        x=[0, 0], y=[0, 0], z=[0, axis_length],
        mode='lines',
        line=dict(color='black', width=6, dash='dash'),
        name='True Z-Axis (0,0,1)'
    ))

    # Jittered Z-Axis (Displaced to match the jittered neuron)
    # We apply the exact same jitter matrix to the vertical unit vector
    j_z_vector = np.dot(np.array([0, 0, axis_length]), jitter_matrix.T)

    fig.add_trace(go.Scatter3d(
        x=[x_offset, x_offset + j_z_vector[0]], # Start at offset, point towards jittered trajectory
        y=[0, j_z_vector[1]],
        z=[0, j_z_vector[2]],
        mode='lines',
        line=dict(color='orange', width=6),
        name='Jittered Z-Axis'
    ))

    # ---------------------------------------------------------
    # LAYOUT
    # ---------------------------------------------------------
    fig.update_layout(
        title=f"Biological Jitter Validation (Offset: {x_offset} µm)",
        scene=dict(
            xaxis_title="X (um)",
            yaxis_title="Y (um)",
            zaxis_title="Z (um)",
            aspectmode='data',  # CRITICAL: Ensures 1:1:1 physical scaling
            bgcolor='white'
        ),
        width=1200,
        height=800,
        margin=dict(l=0, r=0, b=0, t=50),
        legend=dict(
            x=0.02, y=0.98,
            bgcolor="rgba(255, 255, 255, 0.8)",
            bordercolor="Black",
            borderwidth=1
        )
    )

    fig.show()


import os


synapses_dir = '/content/drive/MyDrive/Colab Notebooks/Synapse database'
output_directory = '/content/drive/MyDrive/Colab Notebooks/Reconstructed neurons'
output_filename = 'alignment_metadata_L5.csv'

metadata_filepath = os.path.join(output_directory, output_filename)

metadata_df = pd.read_csv(metadata_filepath)

nid = 29977695430
df_aligned, df_jittered, j_matrix = rototranslate_and_jitter(output_directory,nid, metadata_df)
plot_aligned_vs_jittered(df_aligned, df_jittered, j_matrix)
