# -*- coding: utf-8 -*-
"""Phase1Fitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2eMIkBx5bamdu5EdHZuUQDV6ThkWFE-
"""

!pip install -q condacolab
import condacolab
condacolab.install()

# Install Python 3.9 (which is perfectly compatible with the AllenSDK's requirements)
!conda install -y python=3.9

# Now pip install will find the correct pre-built wheels without crashing!
!pip install -q allensdk neuron scikit-optimize

"""
phase1_data_loader.py
=====================
Phase 1 of the human-cortex passive-property optimisation pipeline.

This module:
  1. Discovers human cells in the Allen Cell Types Database matching a set
     of layer / dendrite-type / protocol / (optional) Patch-seq subtype filters.
  2. Loads experimental electrophysiology and morphology for one chosen cell.
  3. Builds a NEURON compartmental model with a Hay-style stub axon and
     per-segment spine-area F multiplier on dendrites > 60 µm from the soma.
  4. Packages everything for Phase-2 Bayesian optimisation with scikit-optimize.

Key references
--------------
- Eyal et al. (2016) eLife 5:e16553                    — passive-fit methodology
- Allen Cell Types Database (Technical White Paper, v5) — Square Subthreshold and
                                                          Long Square protocols
- Hay et al. (2011) PLoS Comp Biol 7:e1002107           — axon-stub convention
- Internal pipeline document `passive_properties_summary.docx`

Notes for users
---------------
* This file is laid out in `# %%` cells so it pastes one-to-one into Colab
  cells, but it also runs end-to-end as `python phase1_data_loader.py` after
  the demo block at the bottom is uncommented.
* AllenSDK field names occasionally drift between releases; defensive code
  paths are flagged with `# DEFENSIVE:` so you can swap them out if a future
  release breaks the loader.
* Liquid-junction-potential correction (+14 mV) is applied at LOAD time,
  per the project pipeline document.  All voltages downstream of this module
  live in the LJP-corrected convention.
"""


# %% Cell 1 — Colab installs (skip on HPC) =====================================
# Uncomment these lines in a fresh Colab session.  On HPC, manage your env
# manually.  AllenSDK pulls in pynwb, h5py, and a fairly fat dependency tree;
# allow ~3 minutes for the install.
#
# !pip install -q allensdk neuron scikit-optimize


# %% Cell 2 — Imports & constants ==============================================
from __future__ import annotations
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, List, Dict, Any, Literal, Tuple

import numpy as np
import pandas as pd

# AllenSDK
from allensdk.core.cell_types_cache import CellTypesCache
from allensdk.api.queries.cell_types_api import CellTypesApi

# NEURON
from neuron import h
h.load_file("stdrun.hoc")
h.load_file("import3d.hoc")

# scikit-optimize
from skopt.space import Real

# --- Constants from the pipeline document -----------------------------------
LJP_CORRECTION_MV = 14.0          # add to recorded Vm to get true membrane V
SPINE_PROXIMAL_CUTOFF_UM = 60.0   # F applied to dendritic segments beyond this
DEFAULT_F = 1.9                   # Eyal 2016 average for human L2/3

# Square Subthreshold protocol (Allen Core 1):
SQ_SUB_DURATION_S        = 5e-4   # 0.5 ms nominal
SQ_SUB_DURATION_TOL_S    = 5e-4   # ±0.5 ms tolerance (catches "Short Square" variants)
SQ_SUB_AMPLITUDE_PA      = 200.0  # ±200 pA nominal
SQ_SUB_AMPLITUDE_TOL_PA  = 30.0   # ±30 pA tolerance

# Long Square subthreshold cutoff (used for Rin / τm validation target):
LONG_SQUARE_MAX_ABS_AMPLITUDE_PA = 100.0

# Passive parameter bounds (pipeline doc, mirrored from Eyal/Markram):
DEFAULT_CM_BOUNDS = (0.3, 3.0)            # µF/cm²
DEFAULT_RM_BOUNDS = (1_000.0, 100_000.0)  # Ω·cm²
DEFAULT_RA_BOUNDS = (50.0, 1_000.0)       # Ω·cm


# %% Cell 2b — Custom exceptions ===============================================
class IncompleteDataError(Exception):
    """Raised by ``load_allen_data`` when ``require_complete_data=True`` and
    either the training (Square Subthreshold) or validation (Long Square)
    bundle list is empty for the requested specimen.

    The :class:`CellData` object that triggered the error is attached as the
    ``cell_data`` attribute, so callers that catch the exception can still
    inspect what was loaded.
    """

    def __init__(self, message: str, cell_data: Optional["CellData"] = None):
        super().__init__(message)
        self.cell_data = cell_data



# %% Cell 3 — Dataclasses ======================================================
@dataclass
class SweepBundle:
    """
    One averaged sweep (or one group of K averaged repeats from the same
    polarity).  Time starts at 0; voltages are LJP-corrected mV; current is pA.
    """
    polarity: Literal["dep", "hyp"]
    amplitude_pA: float
    t: np.ndarray              # seconds
    v_mV: np.ndarray           # LJP-corrected
    i_pA: np.ndarray
    stim_onset_s: float
    stim_duration_s: float
    n_repeats_averaged: int
    sweep_numbers: List[int]
    sampling_rate_Hz: float
    stimulus_name: str = ""    # original Allen stimulus_name (debug aid)


@dataclass
class CellData:
    """Everything the optimiser will ever need from one Allen cell."""
    specimen_id: int
    metadata: Dict[str, Any]               # layer, dendrite_type, donor_id, ...
    swc_path: Path

    # Primary fitting data — from Square Subthreshold sweeps
    square_subthreshold: List[SweepBundle]

    # Held-out validation data — from Long Square subthreshold sweeps
    long_square_subthreshold: List[SweepBundle]

    # Reference scalars from the Allen Cell Feature Summary (LJP-corrected here)
    rin_MOhm: float
    tau_ms: float
    v_rest_mV: float

    ljp_correction_mV: float
    n_avg_groups: int


@dataclass
class PassiveSearchSpace:
    cm_bounds: Tuple[float, float] = DEFAULT_CM_BOUNDS
    rm_bounds: Tuple[float, float] = DEFAULT_RM_BOUNDS
    ra_bounds: Tuple[float, float] = DEFAULT_RA_BOUNDS

    def as_skopt_dimensions(self) -> List[Real]:
        # Rm spans two orders of magnitude → log-uniform prior is appropriate.
        return [
            Real(*self.cm_bounds, name="Cm"),
            Real(*self.rm_bounds, name="Rm", prior="log-uniform"),
            Real(*self.ra_bounds, name="Ra"),
        ]


@dataclass
class OptimiserInputs:
    search_space: PassiveSearchSpace
    skopt_dimensions: List[Real]

    train_bundles: List[SweepBundle]
    train_window_ms: Tuple[float, float] = (1.0, 100.0)   # post-stim, Eyal-style

    validation_bundles: List[SweepBundle] = field(default_factory=list)

    rin_MOhm: float = np.nan
    tau_ms: float = np.nan
    v_rest_mV: float = np.nan


# %% Cell 4 — Helper: list_human_cells_with_morphology =========================
def list_human_cells_with_morphology(
    layer: Optional[str] = None,
    dendrite_type: Optional[Literal["spiny", "aspiny", "sparsely spiny"]] = None,
    require_square_subthreshold: bool = True,
    require_long_square: bool = True,
    patchseq_ttype_csv: Optional[str] = None,
    interneuron_subtype: Optional[Literal["SST", "PV", "VIP"]] = None,
    n_cells: Optional[int] = None,
    ctc: Optional[CellTypesCache] = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Discover human Allen cells matching the requested filters.

    Parameters
    ----------
    layer
        e.g. ``"2/3"``, ``"4"``, ``"5"``, ``"6a"`` — matched against
        ``structure_layer_name``.
    dendrite_type
        ``"spiny"`` / ``"aspiny"`` / ``"sparsely spiny"``.
    require_square_subthreshold, require_long_square
        Whether to drop cells that lack the named Allen protocols.
    patchseq_ttype_csv
        Optional path to a CSV with at least columns ``specimen_id`` and
        ``t_type`` mapping each cell to its Patch-seq transcriptomic type.
        If absent, all aspiny cells are returned with subtype ``"unknown"``.
    interneuron_subtype
        ``"SST"`` / ``"PV"`` / ``"VIP"``.  Honoured only when
        ``patchseq_ttype_csv`` is supplied; otherwise a warning is raised
        and the filter is ignored.
    n_cells
        If set, truncate the returned DataFrame to the first ``n_cells`` rows.
    ctc
        Optional pre-built ``CellTypesCache``.  If ``None`` one is created
        with manifest at ``cell_types/manifest.json`` (Colab-friendly default).

    Returns
    -------
    DataFrame with columns including ``specimen_id``, ``structure_layer_name``,
    ``dendrite_type``, ``donor_id``, ``has_square_subthreshold``,
    ``has_long_square``, and ``subtype``.
    """
    if ctc is None:
        ctc = CellTypesCache(manifest_file="cell_types/manifest.json")

    cells = ctc.get_cells(
        species=[CellTypesApi.HUMAN],
        require_morphology=False,
        require_reconstruction=True,
    )
    df = pd.DataFrame(cells)
    if verbose:
        print(f"[list_human_cells] Found {len(df)} human cells with reconstructions")

    if layer is not None:
        df = df[df["structure_layer_name"] == layer]
        if verbose:
            print(f"[list_human_cells]   after layer={layer!r}: {len(df)} cells")

    if dendrite_type is not None:
        df = df[df["dendrite_type"] == dendrite_type]
        if verbose:
            print(f"[list_human_cells]   after dendrite_type={dendrite_type!r}: "
                  f"{len(df)} cells")

    # Protocol availability — needs one network round-trip per cell, so done last
    if require_square_subthreshold or require_long_square:
        ss_flags, ls_flags = [], []
        for sid in df["id"]:
            try:
                sweeps = ctc.get_ephys_sweeps(int(sid))
                names = {s.get("stimulus_name", "") for s in sweeps}
                # DEFENSIVE: Allen has used "Short Square - Subthreshold",
                # "Square - 0.5ms Subthreshold", "Square Subthreshold" across
                # releases.  Match anything that is BOTH "Square" AND
                # "Subthreshold" but NOT "Long Square".
                ss_flags.append(any(
                    ("Square" in n) and ("Subthreshold" in n) and ("Long" not in n)
                    for n in names
                ))
                ls_flags.append(any("Long Square" in n for n in names))
            except Exception as e:
                if verbose:
                    print(f"[list_human_cells]   sweep query failed for "
                          f"specimen {sid}: {e}")
                ss_flags.append(False)
                ls_flags.append(False)
        df = df.assign(has_square_subthreshold=ss_flags, has_long_square=ls_flags)
        if require_square_subthreshold:
            df = df[df["has_square_subthreshold"]]
        if require_long_square:
            df = df[df["has_long_square"]]
        if verbose:
            print(f"[list_human_cells]   after protocol filters: {len(df)} cells")

    # Patch-seq subtype overlay (optional)
    df = df.assign(subtype="unknown")
    if patchseq_ttype_csv is not None:
        ttype_df = pd.read_csv(patchseq_ttype_csv)
        ttype_df.columns = [c.lower() for c in ttype_df.columns]
        if not {"specimen_id", "t_type"} <= set(ttype_df.columns):
            warnings.warn(
                "patchseq_ttype_csv must contain 'specimen_id' and 't_type' "
                "columns; subtype assignment skipped.")
        else:
            sub_map: Dict[int, str] = {}
            for _, row in ttype_df.iterrows():
                ttype = str(row["t_type"]).upper()
                if "SST" in ttype:
                    sub_map[int(row["specimen_id"])] = "SST"
                elif "PVALB" in ttype or " PV " in f" {ttype} ":
                    sub_map[int(row["specimen_id"])] = "PV"
                elif "VIP" in ttype:
                    sub_map[int(row["specimen_id"])] = "VIP"
                else:
                    sub_map[int(row["specimen_id"])] = "other"
            df["subtype"] = df["id"].map(sub_map).fillna("unknown")

    if interneuron_subtype is not None:
        if patchseq_ttype_csv is None:
            warnings.warn(
                f"interneuron_subtype={interneuron_subtype!r} was requested but "
                f"no patchseq_ttype_csv was supplied — filter ignored.")
        else:
            df = df[df["subtype"] == interneuron_subtype]
            if verbose:
                print(f"[list_human_cells]   after subtype="
                      f"{interneuron_subtype!r}: {len(df)} cells")

    keep = ["id", "structure_layer_name", "dendrite_type", "donor_id",
            "structure_area_abbrev", "subtype",
            "has_square_subthreshold", "has_long_square"]
    out = df[[c for c in keep if c in df.columns]].copy()
    out = out.rename(columns={"id": "specimen_id"}).reset_index(drop=True)

    if n_cells is not None and len(out) > n_cells:
        out = out.iloc[:n_cells].copy()
        if verbose:
            print(f"[list_human_cells]   truncated to first {n_cells} cells")

    return out


# %% Cell 5 — Internal sweep selection & averaging =============================
def _to_pA_seconds(amp, dur) -> Tuple[float, float]:
    """Normalise Allen sweep metadata to (pA, seconds).

    Allen Cell Types data can show up with two unit conventions across SDK
    releases: SI (Amperes, seconds) or mixed (pA, ms).  We auto-detect by
    magnitude.  Missing / non-numeric values (None, NaN, strings) are mapped
    to NaN — callers must filter NaN before use.
    """
    # --- amplitude --------------------------------------------------------
    if amp is None:
        amp_pA: float = float("nan")
    else:
        try:
            a = float(amp)
        except (TypeError, ValueError):
            amp_pA = float("nan")
        else:
            if np.isnan(a):
                amp_pA = float("nan")
            else:
                # SI Amperes are tiny: |I| < 1 mA = 1e-3 A.  Otherwise pA.
                amp_pA = a * 1e12 if abs(a) < 1e-3 else a

    # --- duration ---------------------------------------------------------
    if dur is None:
        dur_s: float = float("nan")
    else:
        try:
            d = float(dur)
        except (TypeError, ValueError):
            dur_s = float("nan")
        else:
            if np.isnan(d):
                dur_s = float("nan")
            else:
                # Heuristic: seconds are < 10; bigger values are ms.
                dur_s = d if d < 10 else d * 1e-3

    return amp_pA, dur_s


def _select_square_subthreshold(sweeps_meta: List[Dict]) -> List[Dict]:
    """Find Square Subthreshold sweeps by ``stimulus_name`` only.

    The Square Subthreshold protocol stores all 20 ±200 pA pulses **inside a
    single sweep** (cf. Allen Cell Types Tech Paper, Appendix p. 15: "0.5 ms
    square current injections to +/- 200 pA, repeated 20 times (200 ms
    intervals). N/A (single sweep)").  This means duration- and amplitude-
    based filtering on the per-sweep metadata is meaningless here — the sweep
    duration covers all 20 repeats, and the polarity alternates within the
    sweep so the average amplitude is ~0.  Pulse identification therefore has
    to happen on the current waveform itself, by ``_detect_pulses_in_current``.
    """
    out = []
    for s in sweeps_meta:
        name = s.get("stimulus_name", "") or ""
        if ("Square" in name) and ("Subthreshold" in name) and ("Long" not in name):
            out.append(s)
    return out


def _select_long_square_subthreshold(sweeps_meta: List[Dict]) -> List[Dict]:
    """Select all Long Square sweeps, regardless of metadata amplitude.

    Allen's standard Long Square protocol starts at −110 pA (not −100 pA),
    and ``stimulus_amplitude`` is frequently ``None`` in the sweep metadata —
    both issues make metadata-level amplitude filtering unreliable.  We
    therefore return ALL Long Square sweeps and let the caller measure the
    actual step amplitude from the NWB waveform before deciding which sweep
    to use for τm / Rin validation.
    """
    return [
        s for s in sweeps_meta
        if "Long Square" in (s.get("stimulus_name", "") or "")
    ]


def _detect_step_amplitude(
    stimulus_pA: np.ndarray,
    sampling_rate_Hz: float,
    threshold_pA: float = 5.0,
    min_step_duration_s: float = 0.1,
) -> float:
    """Detect the commanded step amplitude in a Long-Square-style sweep.

    Subtracts a baseline (median of the first 5 % of the trace), thresholds at
    ``threshold_pA`` (well below the smallest standard Long Square step of
    10 pA but well above acquisition noise), finds the longest contiguous
    above-threshold region, and returns the **median** current within that
    region (signed).  Returns NaN if no region of duration
    ``min_step_duration_s`` is found.
    """
    n = len(stimulus_pA)
    if n == 0:
        return float("nan")
    baseline = float(np.median(stimulus_pA[:max(10, n // 20)]))
    delta = stimulus_pA - baseline
    above = np.abs(delta) > threshold_pA
    if not above.any():
        return float("nan")
    # First-edge-to-last-edge of the above-threshold region:
    on = int(np.argmax(above))
    off = n - int(np.argmax(above[::-1]))
    if (off - on) < int(min_step_duration_s * sampling_rate_Hz):
        return float("nan")
    return float(np.median(delta[on:off]))


def _detect_pulses_in_current(
    current_pA: np.ndarray,
    sampling_rate_Hz: float,
    threshold_pA: float = 50.0,
    min_pulse_duration_s: float = 1e-4,
) -> List[Tuple[int, int, float]]:
    """Detect rectangular pulse events in a current waveform.

    Subtracts a baseline (median of the first 5% of the trace) before
    thresholding, so that bias currents up to ~tens of pA do not disrupt
    detection.  Returns a list of ``(start_idx, end_idx, peak_pA_signed)``
    tuples, one per detected pulse.
    """
    n = len(current_pA)
    if n == 0:
        return []
    baseline = float(np.median(current_pA[: max(10, n // 20)]))
    delta = current_pA - baseline
    above = np.abs(delta) > threshold_pA
    if not above.any():
        return []
    # Contiguous runs of `above`
    diff = np.diff(above.astype(np.int8))
    starts = list((np.where(diff == 1)[0] + 1).astype(int))
    ends = list((np.where(diff == -1)[0] + 1).astype(int))
    if above[0]:
        starts = [0] + starts
    if above[-1]:
        ends = ends + [n]

    pulses: List[Tuple[int, int, float]] = []
    min_samples = max(2, int(min_pulse_duration_s * sampling_rate_Hz))
    for s_i, e_i in zip(starts, ends):
        if (e_i - s_i) < min_samples:
            continue
        seg = delta[s_i:e_i]
        peak_signed = float(seg[int(np.argmax(np.abs(seg)))])
        pulses.append((s_i, e_i, peak_signed))
    return pulses


def _extract_windows_around_pulses(
    voltage_mV: np.ndarray,
    current_pA: np.ndarray,
    sampling_rate_Hz: float,
    pulses: List[Tuple[int, int, float]],
    pre_ms: float = 10.0,
    post_ms: float = 200.0,
) -> List[Dict[str, Any]]:
    """For each pulse, cut a window from ``-pre_ms`` to ``+post_ms`` around
    the pulse onset.  Returns dicts with keys ``t``, ``v``, ``i``,
    ``stim_duration_s``, ``peak_pA``, ``polarity``.  Pulses too close to
    a trace boundary are silently skipped.
    """
    pre_n = int(round(pre_ms * 1e-3 * sampling_rate_Hz))
    post_n = int(round(post_ms * 1e-3 * sampling_rate_Hz))
    n_total = pre_n + post_n
    out = []
    for s_i, e_i, peak in pulses:
        win_start = s_i - pre_n
        win_end = s_i + post_n
        if win_start < 0 or win_end > len(voltage_mV):
            continue
        v_win = np.asarray(voltage_mV[win_start:win_end], dtype=float).copy()
        i_win = np.asarray(current_pA[win_start:win_end], dtype=float).copy()
        # Ensure all windows have the same length (defensive against rounding).
        if len(v_win) != n_total:
            v_win = v_win[:n_total]
            i_win = i_win[:n_total]
        # Time axis with t = 0 at pulse onset.
        t_win = (np.arange(len(v_win)) - pre_n) / sampling_rate_Hz
        out.append({
            "t": t_win,
            "v": v_win,
            "i": i_win,
            "stim_duration_s": (e_i - s_i) / sampling_rate_Hz,
            "peak_pA": peak,
            "polarity": "dep" if peak > 0 else "hyp",
        })
    return out


def _build_subthreshold_bundles(
    data_set,
    sweep_meta_list: List[Dict],
    n_avg_groups: int,
    ljp_correction_mV: float,
    pre_ms: float = 10.0,
    post_ms: float = 200.0,
    pulse_threshold_pA: float = 50.0,
    expected_amplitude_pA: float = SQ_SUB_AMPLITUDE_PA,
    amplitude_tol_pA: float = SQ_SUB_AMPLITUDE_TOL_PA,
    expected_duration_s: float = SQ_SUB_DURATION_S,
    duration_tol_s: float = SQ_SUB_DURATION_TOL_S,
    verbose: bool = True,
) -> List[SweepBundle]:
    """
    For Square-Subthreshold-style sweeps, where each sweep contains many brief
    pulses, extract every individual pulse, classify by polarity, validate
    its amplitude/duration, and average within polarity into ``n_avg_groups``
    bundles per polarity.

    The Eyal / pipeline-document fitting window is 1–100 ms post-stimulus,
    so ``post_ms = 200`` gives Phase 2 a comfortable margin (you can crop the
    last 100 ms if you want).  ``pre_ms`` is used to estimate / re-zero the
    pre-pulse baseline; it is NOT stripped from the returned bundle.
    """
    if not sweep_meta_list:
        return []

    all_dep: List[Dict[str, Any]] = []
    all_hyp: List[Dict[str, Any]] = []
    sweep_numbers_used: List[int] = []
    sampling_rate_Hz: Optional[float] = None
    stim_name = sweep_meta_list[0].get("stimulus_name", "")

    for sm in sweep_meta_list:
        sn = int(sm["sweep_number"])
        sw = data_set.get_sweep(sn)
        idx = sw.get("index_range", (0, len(sw["response"]) - 1))
        v_full = np.asarray(sw["response"][idx[0]: idx[1] + 1], dtype=float) * 1e3
        v_full = v_full + ljp_correction_mV                  # mV, LJP-corrected
        i_full = np.asarray(sw["stimulus"][idx[0]: idx[1] + 1], dtype=float) * 1e12  # pA
        sr = float(sw["sampling_rate"])
        if sampling_rate_Hz is None:
            sampling_rate_Hz = sr

        pulses = _detect_pulses_in_current(
            i_full, sr, threshold_pA=pulse_threshold_pA)

        # Amplitude / duration QC on each detected pulse: keep only those whose
        # peak |I| matches the expected ±200 pA within tolerance, and whose
        # duration matches the expected 0.5 ms within tolerance.  This guards
        # against accidental matches in protocols whose name happens to
        # contain "Square" + "Subthreshold" but with different parameters.
        pulses_qc = []
        for s_i, e_i, peak in pulses:
            dur = (e_i - s_i) / sr
            if abs(abs(peak) - expected_amplitude_pA) > amplitude_tol_pA:
                continue
            if abs(dur - expected_duration_s) > duration_tol_s:
                continue
            pulses_qc.append((s_i, e_i, peak))

        windows = _extract_windows_around_pulses(
            v_full, i_full, sr, pulses_qc, pre_ms=pre_ms, post_ms=post_ms)
        for w in windows:
            (all_dep if w["polarity"] == "dep" else all_hyp).append(w)
        sweep_numbers_used.append(sn)

        if verbose:
            n_dep = sum(1 for w in windows if w["polarity"] == "dep")
            n_hyp = sum(1 for w in windows if w["polarity"] == "hyp")
            print(f"[load_allen_data]   sweep {sn} ({stim_name!r}): "
                  f"{len(pulses)} pulses detected, "
                  f"{len(pulses_qc)} pass QC "
                  f"(dep={n_dep}, hyp={n_hyp})")

    if verbose:
        print(f"[load_allen_data]   total dep pulses: {len(all_dep)}, "
              f"total hyp pulses: {len(all_hyp)}")

    bundles: List[SweepBundle] = []
    for polarity_label, group in (("dep", all_dep), ("hyp", all_hyp)):
        if not group:
            continue
        n_groups = max(1, min(n_avg_groups, len(group)))
        partitions = np.array_split(np.arange(len(group)), n_groups)
        for part in partitions:
            if len(part) == 0:
                continue
            v_stack = np.stack([group[i]["v"] for i in part])
            i_stack = np.stack([group[i]["i"] for i in part])
            t_ref = group[part[0]]["t"]
            stim_dur = float(np.mean([group[i]["stim_duration_s"] for i in part]))
            amp = float(np.mean([group[i]["peak_pA"] for i in part]))
            # By construction t = 0 is the pulse onset.
            bundles.append(SweepBundle(
                polarity=polarity_label,
                amplitude_pA=amp,
                t=t_ref,
                v_mV=v_stack.mean(axis=0),
                i_pA=i_stack.mean(axis=0),
                stim_onset_s=0.0,
                stim_duration_s=stim_dur,
                n_repeats_averaged=int(len(part)),
                sweep_numbers=sweep_numbers_used,
                sampling_rate_Hz=float(sampling_rate_Hz),
                stimulus_name=stim_name,
            ))
    return bundles


def _build_bundles_from_group(
    data_set,
    sweep_meta_group: List[Dict],
    n_avg_groups: int,
    polarity_label: str,
    ljp_correction_mV: float,
) -> List[SweepBundle]:
    """
    Split ``sweep_meta_group`` into ``n_avg_groups`` equal partitions, average
    raw repeats inside each partition, and return one SweepBundle per partition.
    """
    if not sweep_meta_group:
        return []
    sweep_numbers = [s["sweep_number"] for s in sweep_meta_group]
    n_avg_groups = max(1, min(n_avg_groups, len(sweep_numbers)))
    partitions = np.array_split(np.array(sweep_numbers), n_avg_groups)
    stim_name = sweep_meta_group[0].get("stimulus_name", "")

    bundles: List[SweepBundle] = []
    for part in partitions:
        v_traces, i_traces, sample_rates = [], [], []
        for sn in part:
            sw = data_set.get_sweep(int(sn))
            # index_range clips out the test pulse that Allen prepends to every
            # sweep — as shown in the official AllenSDK notebook example.
            # Default to (0, end) if the key is absent for robustness.
            idx = sw.get("index_range", (0, len(sw["response"]) - 1))
            v_traces.append(sw["response"][idx[0]: idx[1] + 1])   # Volts
            i_traces.append(sw["stimulus"][idx[0]: idx[1] + 1])   # Amps
            sample_rates.append(sw["sampling_rate"])
        n_min = min(len(v) for v in v_traces)
        V = np.mean([v[:n_min] for v in v_traces], axis=0) * 1e3 + ljp_correction_mV
        I = np.mean([i[:n_min] for i in i_traces], axis=0) * 1e12
        sr = float(sample_rates[0])
        t = np.arange(n_min) / sr

        # Detect onset/duration from the averaged current waveform
        thr = 0.5 * np.max(np.abs(I))
        active = np.abs(I) > thr
        if active.any():
            on_idx = int(np.argmax(active))
            off_idx = len(active) - int(np.argmax(active[::-1]))
            stim_onset_s = float(t[on_idx])
            stim_duration_s = float(t[off_idx - 1] - t[on_idx])
            amp_pA = float(np.sign(I[on_idx]) * np.max(np.abs(I)))
        else:
            stim_onset_s = stim_duration_s = amp_pA = 0.0

        bundles.append(SweepBundle(
            polarity=polarity_label,
            amplitude_pA=amp_pA,
            t=t, v_mV=V, i_pA=I,
            stim_onset_s=stim_onset_s,
            stim_duration_s=stim_duration_s,
            n_repeats_averaged=len(part),
            sweep_numbers=[int(x) for x in part],
            sampling_rate_Hz=sr,
            stimulus_name=stim_name,
        ))
    return bundles


# %% Cell 6 — load_allen_data ==================================================
def load_allen_data(
    specimen_id: int,
    ljp_correction_mV: float = LJP_CORRECTION_MV,
    n_avg_groups: int = 1,
    cache_dir: str = "cell_types",
    ctc: Optional[CellTypesCache] = None,
    require_complete_data: bool = True,
    verbose: bool = True,
) -> CellData:
    """
    Pull ephys NWB, SWC morphology, and Cell Feature Summary scalars for one
    Allen specimen.  Returns a fully-populated ``CellData``.

    Parameters
    ----------
    cache_dir
        Root directory where AllenSDK will store downloaded files.  Must match
        the directory prefix used when constructing ``ctc`` (default
        ``"cell_types"``).  Ignored if ``ctc`` is supplied externally.
    require_complete_data
        If ``True`` (default), raise :class:`IncompleteDataError` when the cell
        does not yield BOTH at least one Square Subthreshold bundle AND at
        least one Long Square subthreshold bundle.  This keeps Phase 2's
        validation step (Rin/τm against the held-out Long Square sweep)
        well-defined for every cell that propagates downstream.  Set to
        ``False`` to return ``CellData`` regardless — useful when you want to
        proceed with Allen's scalar Rin/τm features only and skip the
        waveform-level validation.

    Notes
    -----
    Multi-sweep pooling.  When the cell has more than one Square Subthreshold
    sweep recorded (Allen sometimes runs the protocol several times per cell),
    pulses from **all** sweeps are pooled before averaging.  ``n_avg_groups``
    then partitions the pooled pool into K equal groups, yielding K averaged
    bundles per polarity (default K = 1, i.e. one super-clean trace).  The
    same pooling logic applies to multiple Long Square sweeps that share the
    chosen target amplitude.
    """
    if ctc is None:
        ctc = CellTypesCache(manifest_file=f"{cache_dir}/manifest.json")

    # --- Metadata -----------------------------------------------------------
    cells = ctc.get_cells(species=[CellTypesApi.HUMAN])
    meta = next((c for c in cells if c["id"] == specimen_id), None)
    if meta is None:
        raise ValueError(f"Specimen {specimen_id} not found among human cells.")

    # --- Morphology ---------------------------------------------------------
    # BUG-FIX: CellTypesCache has no public `manifest_file` attribute.
    # Instead, we supply an explicit file_name to get_reconstruction() so we
    # always know exactly where the SWC lands on disk.
    swc_file = Path(cache_dir) / f"specimen_{specimen_id}" / "reconstruction.swc"
    swc_file.parent.mkdir(parents=True, exist_ok=True)
    ctc.get_reconstruction(specimen_id, file_name=str(swc_file))
    if verbose:
        print(f"[load_allen_data] specimen {specimen_id}: SWC at {swc_file}")

    # --- Ephys --------------------------------------------------------------
    data_set = ctc.get_ephys_data(specimen_id)
    sweeps_meta = ctc.get_ephys_sweeps(specimen_id)

    # --- Square Subthreshold: many pulses per sweep -------------------------
    # All 20 ±200 pA pulses live inside a SINGLE sweep (Allen Tech Paper
    # appendix p.15: "N/A (single sweep)").  We therefore find candidate
    # sweeps by name, then identify each individual pulse by thresholding the
    # current waveform.
    ss_meta = _select_square_subthreshold(sweeps_meta)
    if verbose:
        print(f"[load_allen_data]   Square-Subthreshold candidate sweeps: "
              f"{len(ss_meta)}")
    ss_bundles = _build_subthreshold_bundles(
        data_set,
        ss_meta,
        n_avg_groups=n_avg_groups,
        ljp_correction_mV=ljp_correction_mV,
        verbose=verbose,
    )

    # --- Long Square: one step amplitude per sweep --------------------------
    # NOTE: Loading Long Square waveforms is OPTIONAL.  Phase 2's Rin/τm
    # validation uses the scalar features cd.rin_MOhm and cd.tau_ms (computed
    # by Allen's vetted feature extractor), simulating a synthetic step on the
    # model and comparing the resulting Rin/τm to those scalars.  We load the
    # actual waveforms here only as a diagnostic / optional second RMSD
    # validation target.  If detection fails for a cell, Phase 2 still works.
    ls_meta = _select_long_square_subthreshold(sweeps_meta)
    ls_bundles: List[SweepBundle] = []
    if ls_meta:
        # Robust step detection per sweep — find the step region first, then
        # measure amplitude only inside it (avoids dilution by pre/post baseline).
        sweep_amps: List[Tuple[Dict, float]] = []
        for sm in ls_meta:
            try:
                sn = int(sm["sweep_number"])
                sw = data_set.get_sweep(sn)
                idx = sw.get("index_range", (0, len(sw["response"]) - 1))
                i_full = (np.asarray(sw["stimulus"][idx[0]: idx[1] + 1],
                                     dtype=float) * 1e12)
                sr = float(sw["sampling_rate"])
                amp = _detect_step_amplitude(i_full, sr)
                sweep_amps.append((sm, amp))
            except Exception as e:
                if verbose:
                    print(f"[load_allen_data]   Long-Square sweep "
                          f"{sm.get('sweep_number')}: read failed ({e})")

        if verbose:
            valid = [(sm, a) for sm, a in sweep_amps if not np.isnan(a)]
            if valid:
                amps_str = ", ".join(f"{a:+.0f}" for _, a in
                                     sorted(valid, key=lambda x: x[1]))
                print(f"[load_allen_data]   Long-Square detected step "
                      f"amplitudes (pA): [{amps_str}]")
            else:
                print(f"[load_allen_data]   Long-Square: 0/{len(ls_meta)} "
                      f"sweeps yielded a detectable step")

        # Keep clearly hyperpolarising sweeps.  Two-tier cutoff:
        #   Strict  ≤ 100 pA : Allen's own cutoff for τm/Rin computation.
        #   Fallback ≤ 300 pA: covers low-Rin cells and non-standard protocols.
        hyp_sweeps = [(sm, a) for sm, a in sweep_amps
                      if (not np.isnan(a)) and a < -5.0
                      and abs(a) <= LONG_SQUARE_MAX_ABS_AMPLITUDE_PA]
        if not hyp_sweeps:
            hyp_sweeps = [(sm, a) for sm, a in sweep_amps
                          if (not np.isnan(a)) and a < -5.0
                          and abs(a) <= 300.0]

        # --- Build ONE bundle per distinct amplitude -------------------------
        # Rationale: Ih activates more at larger hyperpolarisations (smaller
        # Ih activation at −10/−30 pA vs −90 pA).  Storing all amplitudes as
        # separate bundles lets Phase 2 choose:
        #   • smallest amplitude  → minimal Ih, cleanest passive τm estimate
        #   • all amplitudes      → linear-fit Rin (matches Allen methodology)
        # `amplitude_pA` on each bundle tags which step it corresponds to.
        if hyp_sweeps:
            # Group sweeps by their rounded amplitude (nearest 10 pA).
            amp_groups: Dict[int, List[Dict]] = {}
            for sm, a in hyp_sweeps:
                key = int(round(a / 10.0) * 10)   # −93 → −90, −107 → −110
                amp_groups.setdefault(key, []).append(sm)

            # Sort smallest-to-largest magnitude so ls_bundles[0] is the
            # Ih-cleanest step (Phase 2 default for τm validation).
            for amp_key in sorted(amp_groups.keys(), key=abs):
                sel = amp_groups[amp_key]
                bndls = _build_bundles_from_group(
                    data_set, sel, n_avg_groups=1,
                    polarity_label="hyp", ljp_correction_mV=ljp_correction_mV)
                ls_bundles.extend(bndls)

            if verbose:
                amp_keys_str = ", ".join(
                    f"{k:+d}" for k in sorted(amp_groups.keys(), key=abs))
                print(f"[load_allen_data]   Long-Square bundles loaded "
                      f"({len(ls_bundles)} total): [{amp_keys_str}] pA\n"
                      f"[load_allen_data]   → ls_bundles[0] "
                      f"({ls_bundles[0].amplitude_pA:+.0f} pA) "
                      f"is Ih-cleanest; use for τm validation.")
        else:
            if verbose:
                print("[load_allen_data]   No usable hyperpolarising "
                      "Long Square sweeps — Phase 2 will validate Rin/τm "
                      "against the Allen scalar features only.")

    # --- Reference scalars --------------------------------------------------
    # BUG-FIX: get_ephys_features() takes no specimen_id argument — it returns
    # a list of feature dicts for ALL cells.  We call it bare and filter.
    all_feats = ctc.get_ephys_features()   # list of dicts, one per cell
    feats = next(
        (f for f in all_feats if f.get("specimen_id") == specimen_id), {}
    )
    rin = float(feats.get("input_resistance_mohm", np.nan))
    tau = float(feats.get("tau", np.nan))
    if 0 < tau < 1:                      # Allen reports τ in seconds in some releases
        tau *= 1e3
    vrest = float(feats.get("vrest", np.nan))
    if not np.isnan(vrest):
        vrest += ljp_correction_mV       # apply LJP to the reference too

    if verbose:
        print(f"[load_allen_data] specimen {specimen_id}: "
              f"Rin={rin:.1f} MΩ  τm={tau:.1f} ms  "
              f"Vrest={vrest:.1f} mV (LJP-corrected)")
        # Pooling summary — show explicit sweep + pulse counts
        n_ss_sweeps = len(ss_meta) if 'ss_meta' in locals() else 0
        n_dep = sum(b.n_repeats_averaged for b in ss_bundles if b.polarity == "dep")
        n_hyp = sum(b.n_repeats_averaged for b in ss_bundles if b.polarity == "hyp")
        print(f"[load_allen_data]   Square Subthreshold: {len(ss_bundles)} bundle(s) "
              f"pooled from {n_ss_sweeps} sweep(s) "
              f"({n_dep} dep + {n_hyp} hyp pulses, n_avg_groups={n_avg_groups})")
        n_ls_pulses = sum(b.n_repeats_averaged for b in ls_bundles)
        print(f"[load_allen_data]   Long Square subthreshold: "
              f"{len(ls_bundles)} bundle(s) pooled from {n_ls_pulses} sweep(s)")

    cell_data = CellData(
        specimen_id=specimen_id,
        metadata=meta,
        swc_path=swc_file,
        square_subthreshold=ss_bundles,
        long_square_subthreshold=ls_bundles,
        rin_MOhm=rin,
        tau_ms=tau,
        v_rest_mV=vrest,
        ljp_correction_mV=ljp_correction_mV,
        n_avg_groups=n_avg_groups,
    )

    # --- Completeness gate -------------------------------------------------
    if require_complete_data:
        missing = []
        if not ss_bundles:
            missing.append("Square Subthreshold (training)")
        if not ls_bundles:
            missing.append("Long Square subthreshold (validation)")
        if missing:
            raise IncompleteDataError(
                f"Specimen {specimen_id} lacks {' AND '.join(missing)} data; "
                f"set require_complete_data=False to load anyway.",
                cell_data=cell_data,
            )

    return cell_data


# %% Cell 7 — NEURON model: PassiveCell + builder ==============================
class PassiveCell:
    """
    Compartmental passive model of one Allen morphology.

    * SWC imported via NEURON's ``Import3d_SWC_read``.
    * Original axon optionally replaced by a Hay-style two-section stub
      (each 30 µm × 1 µm, 5 segments) attached at soma(1.0).
    * The passive ``pas`` mechanism is inserted globally.
    * For each segment in dendritic sections (``dend`` + ``apic``), a
      multiplicative factor ``F`` is applied to ``cm`` and ``g_pas`` if the
      segment's path distance from the soma centre exceeds
      ``spine_proximal_cutoff_um``.  All other segments use a multiplier of 1.

    The optimiser only ever has to call ``set_passive(Cm, Rm, Ra)``; the
    F-scaling is precomputed once and applied per-segment automatically.
    """

    def __init__(
        self,
        swc_path: Path,
        F: float = DEFAULT_F,
        spine_proximal_cutoff_um: float = SPINE_PROXIMAL_CUTOFF_UM,
        axon_replacement: Literal["hay_stub", "none"] = "hay_stub",
    ):
        self.swc_path = Path(swc_path)
        self.F = float(F)
        self.cutoff_um = float(spine_proximal_cutoff_um)
        self.axon_replacement = axon_replacement

        self.soma: List[h.Section] = []
        self.dend: List[h.Section] = []
        self.apic: List[h.Section] = []
        self.axon: List[h.Section] = []

        self._import_swc()
        self._categorise_sections()
        if axon_replacement == "hay_stub":
            self._replace_axon_hay_stub()
        self._insert_passive()
        self._precompute_F_per_segment()

        # IClamp lives at the soma centre and is reconfigured per simulation.
        self._iclamp = h.IClamp(self.soma[0](0.5))
        self._iclamp.delay = 0
        self._iclamp.dur = 0
        self._iclamp.amp = 0

        # Permanent recording vectors for soma centre.
        self._t_vec = h.Vector()
        self._v_vec = h.Vector()
        self._t_vec.record(h._ref_t)
        self._v_vec.record(self.soma[0](0.5)._ref_v)

    # ---- Construction helpers ---------------------------------------------
    def _import_swc(self) -> None:
        reader = h.Import3d_SWC_read()
        reader.input(str(self.swc_path))
        gui = h.Import3d_GUI(reader, 0)
        gui.instantiate(None)

    def _categorise_sections(self) -> None:
        for sec in h.allsec():
            n = sec.name().lower()
            if "soma" in n:
                self.soma.append(sec)
            elif "apic" in n:
                self.apic.append(sec)
            elif "dend" in n:
                self.dend.append(sec)
            elif "axon" in n:
                self.axon.append(sec)
        if not self.soma:
            raise RuntimeError("No soma section found after SWC import.")

    def _replace_axon_hay_stub(self) -> None:
        for sec in list(self.axon):
            h.delete_section(sec=sec)
        self.axon = []
        for i in range(2):
            ax = h.Section(name=f"axon[{i}]")
            ax.L = 30.0
            ax.diam = 1.0
            ax.nseg = 5
            self.axon.append(ax)
        self.axon[0].connect(self.soma[0](1.0), 0)
        self.axon[1].connect(self.axon[0](1.0), 0)

    def _insert_passive(self) -> None:
        for sec in h.allsec():
            sec.insert("pas")

    def _precompute_F_per_segment(self) -> None:
        """Path-distance-based F multiplier, computed once at construction."""
        h.distance(0, self.soma[0](0.5))
        self._F_multiplier: Dict[Tuple[str, float], float] = {}
        for sec in self.dend + self.apic:
            for seg in sec:
                d = h.distance(seg.x, sec=sec)
                self._F_multiplier[(sec.name(), seg.x)] = (
                    self.F if d > self.cutoff_um else 1.0)
        for sec in self.soma + self.axon:
            for seg in sec:
                self._F_multiplier[(sec.name(), seg.x)] = 1.0

    # ---- Public API used by Phase 2 ---------------------------------------
    def set_passive(self, Cm: float, Rm: float, Ra: float) -> None:
        """Apply (Cm, Rm, Ra); dendrites > cutoff are auto-scaled by F."""
        g_pas_base = 1.0 / float(Rm)
        for sec in h.allsec():
            sec.Ra = float(Ra)
            for seg in sec:
                m = self._F_multiplier[(sec.name(), seg.x)]
                seg.cm = float(Cm) * m
                seg.g_pas = g_pas_base * m
                # e_pas left alone here; Phase 2 sets it to match Vrest.

    def set_e_pas(self, e_pas_mV: float) -> None:
        for sec in h.allsec():
            for seg in sec:
                seg.e_pas = float(e_pas_mV)

    def simulate(
        self,
        stim_amp_pA: float,
        stim_delay_ms: float,
        stim_dur_ms: float,
        tstop_ms: float,
        v_init_mV: float = -70.0,
        dt_ms: float = 0.025,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Inject one IClamp pulse at the soma centre and return the somatic
        voltage trace.

        Returns
        -------
        (t_ms, v_mV) — both 1-D arrays, sampled every ``dt_ms``.
        """
        self._iclamp.delay = float(stim_delay_ms)
        self._iclamp.dur = float(stim_dur_ms)
        self._iclamp.amp = float(stim_amp_pA) * 1e-3   # NEURON IClamp amp is in nA
        h.dt = float(dt_ms)
        h.tstop = float(tstop_ms)
        h.v_init = float(v_init_mV)
        h.finitialize(h.v_init)
        h.run()
        return np.array(self._t_vec), np.array(self._v_vec)


def build_neuron_model(
    swc_path: Path | str,
    F: float = DEFAULT_F,
    spine_proximal_cutoff_um: float = SPINE_PROXIMAL_CUTOFF_UM,
    axon_replacement: Literal["hay_stub", "none"] = "hay_stub",
) -> PassiveCell:
    """Thin wrapper around :class:`PassiveCell` for symmetric API."""
    return PassiveCell(
        swc_path=Path(swc_path),
        F=F,
        spine_proximal_cutoff_um=spine_proximal_cutoff_um,
        axon_replacement=axon_replacement,
    )


# %% Cell 8 — prepare_optimiser_inputs =========================================
def prepare_optimiser_inputs(
    cell_data: CellData,
    fit_target: Literal["dep", "hyp", "both"] = "hyp",
    train_window_ms: Tuple[float, float] = (1.0, 100.0),
    long_square_validation_amp: Optional[float] = None,
) -> OptimiserInputs:
    """
    Assemble training and validation bundles for Phase 2's gp_minimize loop.

    Parameters
    ----------
    fit_target
        * ``"hyp"`` (default) — fit on hyperpolarising Square Subthreshold
          sweeps only.  Ih contamination is minimal here (the doc explicitly
          flags Ih bias on Cm), so this is the recommended default.
        * ``"dep"`` — fit on depolarising sweeps only (Eyal 2016 Fig 1a).
        * ``"both"`` — sum RMSD over both polarities.
    train_window_ms
        Post-stimulus window for RMSD computation.  Default 1–100 ms matches
        Eyal 2016.
    long_square_validation_amp
        Commanded step amplitude (pA, negative) of the Long Square bundle to
        use as the validation target.  If ``None`` (default), selects the
        **smallest available absolute amplitude** (i.e. ``ls_bundles[0]``),
        which has the least Ih contamination and is the cleanest target for
        comparing the passive model's τm against Allen's reported value.
        Pass e.g. ``-90.0`` to request a specific amplitude; a warning is
        issued if the exact amplitude is not found.

    Notes on Ih and validation amplitude choice
    -------------------------------------------
    Ih (HCN current) is partially active at rest and activates further upon
    hyperpolarisation.  Larger hyperpolarising steps → more Ih → larger sag
    in the Long Square trace → slight distortion of the measured τm.  For
    waveform-level validation the smallest available step (default) minimises
    this confound.  For Rin validation via a linear fit across all amplitudes
    the distortion is less critical (passive linear model is amplitude-
    independent), so Phase 2 may expose all bundles for that use.
    """
    if fit_target == "dep":
        train = [b for b in cell_data.square_subthreshold if b.polarity == "dep"]
    elif fit_target == "hyp":
        train = [b for b in cell_data.square_subthreshold if b.polarity == "hyp"]
    elif fit_target == "both":
        train = list(cell_data.square_subthreshold)
    else:
        raise ValueError(
            f"fit_target must be 'dep', 'hyp', or 'both' — got {fit_target!r}")

    if not train:
        warnings.warn(f"No training bundles for fit_target={fit_target!r}; "
                      f"check that Square Subthreshold sweeps were loaded.")

    # Long Square validation: pick the Ih-cleanest (smallest |amplitude|) by
    # default, or the user-requested amplitude.
    if cell_data.long_square_subthreshold:
        if long_square_validation_amp is None:
            # ls_bundles are sorted smallest |amp| first by load_allen_data.
            val_bundle = [cell_data.long_square_subthreshold[0]]
        else:
            target = float(long_square_validation_amp)
            matches = [
                b for b in cell_data.long_square_subthreshold
                if abs(b.amplitude_pA - target) < 10.0
            ]
            if not matches:
                available = [b.amplitude_pA for b in cell_data.long_square_subthreshold]
                warnings.warn(
                    f"No Long Square bundle found near {target:+.0f} pA. "
                    f"Available: {[f'{a:+.0f}' for a in available]}. "
                    f"Falling back to smallest amplitude.")
                val_bundle = [cell_data.long_square_subthreshold[0]]
            else:
                val_bundle = matches
    else:
        val_bundle = []

    space = PassiveSearchSpace()
    space = PassiveSearchSpace()
    return OptimiserInputs(
        search_space=space,
        skopt_dimensions=space.as_skopt_dimensions(),
        train_bundles=train,
        train_window_ms=train_window_ms,
        validation_bundles=val_bundle,
        rin_MOhm=cell_data.rin_MOhm,
        tau_ms=cell_data.tau_ms,
        v_rest_mV=cell_data.v_rest_mV,
    )


# %% Cell 8b — Batch helper: keep only cells with complete training+validation
def load_complete_cells(
    candidates: pd.DataFrame,
    *,
    n_avg_groups: int = 1,
    cache_dir: str = "cell_types",
    ctc: Optional[CellTypesCache] = None,
    max_cells: Optional[int] = None,
    verbose: bool = True,
) -> List[CellData]:
    """
    Iterate the rows of a ``list_human_cells_with_morphology`` DataFrame,
    call :func:`load_allen_data` on each, and return only those cells that
    successfully yield BOTH a Square Subthreshold (training) AND a Long
    Square (validation) bundle.  Cells that raise :class:`IncompleteDataError`
    are silently dropped (with a one-line note when ``verbose=True``).

    ``max_cells`` caps the number of *complete* cells returned (early-exits
    the iteration once the cap is reached).
    """
    if ctc is None:
        ctc = CellTypesCache(manifest_file=f"{cache_dir}/manifest.json")

    complete: List[CellData] = []
    n_dropped = 0
    for _, row in candidates.iterrows():
        sid = int(row["specimen_id"])
        if verbose:
            print(f"\n[load_complete_cells] === specimen {sid} ===")
        try:
            cd = load_allen_data(
                sid,
                n_avg_groups=n_avg_groups,
                cache_dir=cache_dir,
                ctc=ctc,
                require_complete_data=True,
                verbose=verbose,
            )
            complete.append(cd)
            if max_cells is not None and len(complete) >= max_cells:
                break
        except IncompleteDataError as e:
            n_dropped += 1
            if verbose:
                print(f"[load_complete_cells]   DROPPED: {e}")
        except Exception as e:
            n_dropped += 1
            if verbose:
                print(f"[load_complete_cells]   DROPPED (unexpected): "
                      f"{type(e).__name__}: {e}")

    if verbose:
        print(f"\n[load_complete_cells] kept {len(complete)} cell(s), "
              f"dropped {n_dropped}")
    return complete


# %% Cell 8c — Plot helper for one cell ========================================
def plot_example_traces(
    cell_data: CellData,
    figsize: Tuple[float, float] = (11.0, 6.0),
    show: bool = True,
):
    """Plot example Square Subthreshold and Long Square traces for one cell.

    Layout: 2 × 2 grid.

        ┌─────────────────────────┬─────────────────────────┐
        │ V (mV)  Square Sub.     │ V (mV)  Long Square     │
        ├─────────────────────────┼─────────────────────────┤
        │ I (pA)  Square Sub.     │ I (pA)  Long Square     │
        └─────────────────────────┴─────────────────────────┘

    Square Subthreshold panel overlays the depolarising and hyperpolarising
    averaged bundles (one trace each — if ``n_avg_groups > 1`` the FIRST group
    is plotted; the others are equivalent up to noise).  Long Square panel
    plots the chosen hyperpolarising step bundle.

    Returns ``(fig, axes)``.
    """
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 2, figsize=figsize)
    (ax_v_ss, ax_v_ls), (ax_i_ss, ax_i_ls) = axes

    # --- Column 1: Square Subthreshold -------------------------------------
    if cell_data.square_subthreshold:
        # First bundle of each polarity (representative if K > 1)
        dep = next(
            (b for b in cell_data.square_subthreshold if b.polarity == "dep"),
            None,
        )
        hyp = next(
            (b for b in cell_data.square_subthreshold if b.polarity == "hyp"),
            None,
        )
        for b, color, label in [
            (dep, "tab:red",  f"dep  ({dep.amplitude_pA:+.0f} pA)" if dep else None),
            (hyp, "tab:blue", f"hyp  ({hyp.amplitude_pA:+.0f} pA)" if hyp else None),
        ]:
            if b is None:
                continue
            ax_v_ss.plot(b.t * 1e3, b.v_mV, color=color, lw=1.0, label=label)
            ax_i_ss.plot(b.t * 1e3, b.i_pA, color=color, lw=1.0)
        ax_v_ss.legend(loc="best", fontsize=8, frameon=False)
        ax_v_ss.set_title(
            f"Square Subthreshold — cell {cell_data.specimen_id}\n"
            f"averaged over {sum(b.n_repeats_averaged for b in cell_data.square_subthreshold)} "
            f"pulses"
        )
    else:
        ax_v_ss.text(0.5, 0.5, "no Square Subthreshold data",
                     transform=ax_v_ss.transAxes, ha="center", va="center",
                     color="grey")
        ax_v_ss.set_title(f"Square Subthreshold — cell {cell_data.specimen_id}")

    ax_v_ss.set_ylabel("V (mV)")
    ax_i_ss.set_ylabel("I (pA)")
    ax_i_ss.set_xlabel("Time from pulse onset (ms)")
    ax_i_ss.axhline(0, color="0.7", lw=0.5)

    # --- Column 2: Long Square ---------------------------------------------
    if cell_data.long_square_subthreshold:
        b = cell_data.long_square_subthreshold[0]
        ax_v_ls.plot(b.t, b.v_mV, color="tab:purple", lw=1.0,
                     label=f"hyp  ({b.amplitude_pA:+.0f} pA)")
        ax_i_ls.plot(b.t, b.i_pA, color="tab:purple", lw=1.0)
        ax_v_ls.legend(loc="best", fontsize=8, frameon=False)
        ax_v_ls.set_title(
            f"Long Square — cell {cell_data.specimen_id}\n"
            f"averaged over {b.n_repeats_averaged} sweep(s)"
        )
    else:
        ax_v_ls.text(0.5, 0.5, "no Long Square data",
                     transform=ax_v_ls.transAxes, ha="center", va="center",
                     color="grey")
        ax_v_ls.set_title(f"Long Square — cell {cell_data.specimen_id}")

    ax_v_ls.set_ylabel("V (mV)")
    ax_i_ls.set_ylabel("I (pA)")
    ax_i_ls.set_xlabel("Time from sweep start (s)")
    ax_i_ls.axhline(0, color="0.7", lw=0.5)

    # Reference V_rest line on both V panels
    if not np.isnan(cell_data.v_rest_mV):
        for ax in (ax_v_ss, ax_v_ls):
            ax.axhline(cell_data.v_rest_mV, color="0.7",
                       lw=0.5, linestyle=":")

    fig.tight_layout()
    if show:
        plt.show()
    return fig, axes


# %% Cell 9 — Demo (uncomment to run end-to-end) ===============================
# if __name__ == "__main__":
#     # 1) Browse human L4 spiny cells
#     candidates = list_human_cells_with_morphology(
#         layer="4", dendrite_type="spiny", n_cells=10, verbose=True,
#     )
#
#     # 2) Iterate; keep only cells with BOTH training and validation data.
#     #    `max_cells=3` early-exits once 3 complete cells are found.
#     complete = load_complete_cells(candidates, n_avg_groups=1, max_cells=3)
#     print(f"\nGot {len(complete)} cells with full passive-fit data.")
#
#     # 3) Pick the first complete cell and visualise its data
#     cd = complete[0]
#     plot_example_traces(cd)
#
#     # 4) Build NEURON model with F=1.9 (Eyal default; replace per layer later)
#     cell = build_neuron_model(cd.swc_path, F=1.9)
#
#     # 5) Smoke-test: simulate the hyperpolarising Square-Subthreshold pulse
#     cell.set_passive(Cm=0.5, Rm=30_000.0, Ra=200.0)
#     cell.set_e_pas(cd.v_rest_mV)
#     b = next(b for b in cd.square_subthreshold if b.polarity == "hyp")
#     t_sim, v_sim = cell.simulate(
#         stim_amp_pA=b.amplitude_pA,
#         stim_delay_ms=b.stim_onset_s * 1e3,
#         stim_dur_ms=b.stim_duration_s * 1e3,
#         tstop_ms=(b.t[-1]) * 1e3,
#         v_init_mV=cd.v_rest_mV,
#     )
#
#     # 6) Build optimiser inputs (Phase 2 will consume this)
#     opt_in = prepare_optimiser_inputs(cd, fit_target="hyp")
#     print("skopt dimensions :", opt_in.skopt_dimensions)
#     print("train bundles    :", len(opt_in.train_bundles))
#     print("validation bundles:", len(opt_in.validation_bundles))

#%% Cell 9 — Demo (uncomment to run end-to-end) ===============================
if __name__ == "__main__":
    # 1) Browse human L4 spiny cells
    candidates = list_human_cells_with_morphology(
        layer="4", dendrite_type="spiny", n_cells=10, verbose=True,
    )

    # 2) Iterate; keep only cells with BOTH training and validation data.
    #    `max_cells=3` early-exits once 3 complete cells are found.
    complete = load_complete_cells(candidates, n_avg_groups=1, max_cells=3)
    print(f"\nGot {len(complete)} cells with full passive-fit data.")

    # 3) Pick the first complete cell and visualise its data
    cd = complete[0]
    plot_example_traces(cd)

    # 4) Build NEURON model with F=1.9 (Eyal default; replace per layer later)
    cell = build_neuron_model(cd.swc_path, F=1.9)

    # 5) Smoke-test: simulate the hyperpolarising Square-Subthreshold pulse
    cell.set_passive(Cm=0.5, Rm=30_000.0, Ra=200.0)
    cell.set_e_pas(cd.v_rest_mV)
    b = next(b for b in cd.square_subthreshold if b.polarity == "hyp")
    t_sim, v_sim = cell.simulate(
        stim_amp_pA=b.amplitude_pA,
        stim_delay_ms=b.stim_onset_s * 1e3,
        stim_dur_ms=b.stim_duration_s * 1e3,
        tstop_ms=(b.t[-1]) * 1e3,
        v_init_mV=cd.v_rest_mV,
    )

    # 6) Build optimiser inputs (Phase 2 will consume this)
    opt_in = prepare_optimiser_inputs(cd, fit_target="hyp")
    print("skopt dimensions :", opt_in.skopt_dimensions)
    print("train bundles    :", len(opt_in.train_bundles))
    print("validation bundles:", len(opt_in.validation_bundles))

