"""Smoke test for SWC reading and format-preserving writing -- Block 8 (loading half).

Checks
    test_known_answer   a hand-written file parses to the expected arrays;
                        frustum areas of a cylinder (2 pi r h) and of a cone
                        (pi (r1 + r2) sqrt(h^2 + (r1 - r2)^2)) are exact
    test_reference      arrays agree with allen_image_plot.read_swc (the
                        2026-09-23 module) on a synthetic file
    test_convergence    skipped: no discretisation
    test_invariants     writing without new radii is byte-identical; writing
                        with new radii changes ONLY the radius token of data
                        lines (comments, blank lines, separators, CRLF,
                        the other six fields all preserved); re-reading gives
                        the new radii at the file's precision
    test_contract       shapes, dtypes, finiteness, dendrite mask
    test_determinism    two reads of the same file are equal
    test_edge_cases     short data line, non-numeric field, non-positive or
                        mis-shaped radii are refused with ValueError

Run
    cd "Passive Features/Diameter Re-measurement"
    python tests/smoke/test_smoke_swc_io.py

Keep this file pure ASCII (hpc-python-compat).
"""
from __future__ import annotations

import importlib.metadata
import os
import platform
import sys
import tempfile
import time
import traceback
import unittest
from pathlib import Path

import numpy as np
from numpy.testing import assert_allclose, assert_array_equal

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from allen_diameter.loading import swc_io  # noqa: E402

SEED = 12345
REPORT_PACKAGES = ("numpy",)

# A file with every awkward feature: comment lines, a blank line, tabs and
# runs of spaces as separators, different radius precisions, a trailing
# space, and CRLF on one line. Fields: id type x y z radius parent.
SAMPLE = (
    "# generated by test_smoke_swc_io\n"
    "# id type x y z radius parent\n"
    "1 1 0.0 0.0 0.0 5.0 -1\n"
    "\n"
    "2 3 1.0000 0.0000 0.0000 0.2500 1\n"
    "3\t3\t2.0\t0.0\t0.0\t0.25\t2\r\n"
    "4  4   2.0  1.5  0.0  0.5  3 \n"
    "5 4 2.0 3.5 0.0 0.1 4\n"
    "6 2 -1.0 0.0 0.0 0.3 1\n"
)


def _write(tmp, text, name="s.swc"):
    p = os.path.join(tmp, name)
    with open(p, "w", encoding="ascii", newline="") as f:
        f.write(text)
    return p


# ---------------------------------------------------------------- checks ---

def test_known_answer():
    with tempfile.TemporaryDirectory() as tmp:
        s = swc_io.read_swc(_write(tmp, SAMPLE))
        assert len(s) == 6
        assert_array_equal(s.ids, [1, 2, 3, 4, 5, 6])
        assert_array_equal(s.types, [1, 3, 3, 4, 4, 2])
        assert_array_equal(s.parent, [-1, 1, 2, 3, 4, 1])
        assert_allclose(s.radius, [5.0, 0.25, 0.25, 0.5, 0.1, 0.3], rtol=0, atol=0)
        assert_allclose(s.xyz[3], [2.0, 1.5, 0.0], rtol=0, atol=0)
        assert s.data_rows == [2, 4, 5, 6, 7, 8]
        # frustum areas: node 3 to node 2 is a cylinder r = 0.25, h = 1 -> 2 pi r h
        area = swc_io.frustum_areas_um2(s)
        assert_allclose(area[2], 2 * np.pi * 0.25 * 1.0, rtol=1e-12)
        # node 4 to node 3: h = 1.5, r1 = 0.5, r2 = 0.25 -> pi (r1 + r2) sqrt(h^2 + (r1 - r2)^2)
        assert_allclose(area[3], np.pi * 0.75 * np.sqrt(1.5 ** 2 + 0.25 ** 2), rtol=1e-12)
        assert area[0] == 0.0  # the root
        seg = swc_io.segment_lengths_um(s)
        assert_allclose(seg, [0.0, 1.0, 1.0, 1.5, 2.0, 1.0], rtol=1e-12)


def test_reference():
    sys.path.insert(0, str(SRC))
    import allen_image_plot as aip  # the 2026-09-23 module, flat in src/
    with tempfile.TemporaryDirectory() as tmp:
        p = _write(tmp, SAMPLE)
        s = swc_io.read_swc(p)
        df = aip.read_swc(p)
        assert_array_equal(s.ids, df["id"].to_numpy())
        assert_array_equal(s.types, df["type"].to_numpy())
        assert_array_equal(s.parent, df["parent"].to_numpy())
        assert_allclose(s.radius, df["r"].to_numpy(), rtol=0, atol=0)
        assert_allclose(s.xyz, df[["x", "y", "z"]].to_numpy(), rtol=0, atol=0)


def test_convergence():
    raise unittest.SkipTest("no discretisation in a file reader")


def test_invariants():
    with tempfile.TemporaryDirectory() as tmp:
        p = _write(tmp, SAMPLE)
        s = swc_io.read_swc(p)
        q = os.path.join(tmp, "copy.swc")
        swc_io.write_swc(s, q)
        assert open(q, "rb").read() == open(p, "rb").read(), "write without new radii is not byte-identical"
        new_r = s.radius * 2.0
        swc_io.write_swc(s, q, radius=new_r)
        a = open(p, "rb").read().decode("ascii").splitlines(keepends=True)
        b = open(q, "rb").read().decode("ascii").splitlines(keepends=True)
        assert len(a) == len(b)
        for k, (la, lb) in enumerate(zip(a, b)):
            if k not in s.data_rows:
                assert la == lb, "non-data line %d changed" % (k + 1)
                continue
            ta, tb = swc_io._split_keep(la), swc_io._split_keep(lb)
            assert len(ta) == len(tb) == 8, (k + 1, len(ta), len(tb))
            for j in range(8):
                assert ta[j][0] == tb[j][0], "separator %d of line %d changed" % (j, k + 1)
                if j != 5:
                    assert ta[j][1] == tb[j][1], "field %d of line %d changed" % (j, k + 1)
        s2 = swc_io.read_swc(q)
        assert_allclose(s2.radius, new_r, rtol=0, atol=0.5e-4)   # written with >= 4 decimals
        # the precision convention of each token is kept: '0.2500' -> 4 decimals, '5.0' -> 4 (minimum)
        assert "0.5000" in b[4] and "10.0000" in b[2], (b[4], b[2])
        # CRLF survives on the line that had it
        assert b[5].endswith("\r\n") and not b[4].endswith("\r\n")


def test_contract():
    with tempfile.TemporaryDirectory() as tmp:
        s = swc_io.read_swc(_write(tmp, SAMPLE))
        assert s.xyz.shape == (6, 3) and s.xyz.dtype == np.float64
        assert s.radius.shape == (6,) and s.radius.dtype == np.float64
        for arr in (s.ids, s.types, s.parent):
            assert arr.shape == (6,) and arr.dtype.kind == "i"
        assert np.all(np.isfinite(s.xyz)) and np.all(np.isfinite(s.radius))
        assert_array_equal(s.dendrite_mask((3, 4)), [False, True, True, True, True, False])
        assert_array_equal(s.parent_index(), [-1, 0, 1, 2, 3, 0])
        assert_allclose(s.diameter, 2 * s.radius)


def test_determinism():
    with tempfile.TemporaryDirectory() as tmp:
        p = _write(tmp, SAMPLE)
        a, b = swc_io.read_swc(p), swc_io.read_swc(p)
        assert a.lines == b.lines and a.data_rows == b.data_rows
        assert_array_equal(a.radius, b.radius)
        assert_array_equal(a.xyz, b.xyz)


def test_edge_cases():
    with tempfile.TemporaryDirectory() as tmp:
        for bad in ("1 1 0 0 0 1\n", "1 1 0 0 x 1 -1\n", "1 1 0 0 0 1 -1\n2 3 1 0 0 0.2\n"):
            try:
                swc_io.read_swc(_write(tmp, bad, "bad.swc"))
            except ValueError as exc:
                assert "line" in str(exc), str(exc)
            else:
                raise AssertionError("accepted a malformed file: %r" % bad)
        s = swc_io.read_swc(_write(tmp, SAMPLE))
        for r in (np.zeros(6), np.full(6, np.nan), np.ones(5), -np.ones(6)):
            try:
                swc_io.rewrite_radius_lines(s, r)
            except ValueError:
                pass
            else:
                raise AssertionError("accepted bad radii %r" % (r,))


# ---------------------------------------------------------------- runner ---

def _environment():
    parts = ["python %s" % platform.python_version()]
    for package in REPORT_PACKAGES:
        try:
            parts.append("%s %s" % (package, importlib.metadata.version(package)))
        except importlib.metadata.PackageNotFoundError:
            parts.append("%s (not installed)" % package)
    parts.append(platform.platform())
    parts.append("seed %d" % SEED)
    return " | ".join(parts)


def main():
    checks = [(name, obj) for name, obj in globals().items()
              if name.startswith("test_") and callable(obj)]
    print("== %s" % Path(__file__).name)
    print(_environment())
    results = []
    for name, func in checks:
        start = time.perf_counter()
        try:
            func()
            status, detail = "PASS", ""
        except unittest.SkipTest as exc:
            status, detail = "SKIP", str(exc)
        except NotImplementedError as exc:
            status, detail = "TODO", str(exc)
        except AssertionError as exc:
            status, detail = "FAIL", str(exc)
        except Exception:
            status, detail = "ERROR", traceback.format_exc()
        results.append((name, status, time.perf_counter() - start, detail))
    width = max([len(n) for n, _, _, _ in results] + [4])
    for name, status, seconds, detail in results:
        lines = detail.strip().splitlines()
        headline = lines[0] if lines else ""
        print(("%-5s  %-" + str(width) + "s  %8.3fs  %s") % (status, name, seconds, headline))
    for name, status, _s, detail in results:
        if status in ("FAIL", "ERROR"):
            print("\n---- %s: %s\n%s" % (status, name, detail.strip()))
    counts = {s: sum(1 for r in results if r[1] == s) for s in ("PASS", "FAIL", "ERROR", "TODO", "SKIP")}
    print("\n-- " + ", ".join("%d %s" % (n, s.lower()) for s, n in counts.items()))
    return 1 if (counts["FAIL"] + counts["ERROR"] + counts["TODO"]) else 0


if __name__ == "__main__":
    sys.exit(main())
