# -*- coding: utf-8 -*-
"""Connectivity_buildup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qm7NlaK_2ymnP5eMoo8NeCE3xn8Pkcun
"""

import os
from google.colab import drive

# This will prompt you to authorize Colab to access your Drive
drive.mount('/content/drive',force_remount=True)

"""# Download the .pkl file"""

import pickle


connectomics_path = '/content/drive/MyDrive/Colab Notebooks/Connectomics/'
os.chdir(connectomics_path)
# Define the path to your file (update this if the file is in a different folder)
file_path = 'conn.pkl'

# Open the file in 'read-binary' mode and load the data
with open(file_path, 'rb') as f:
    conn_data = pickle.load(f)

# --- Quick Verification ---
print("Successfully loaded conn.pkl!")
print(f"Available keys in the data: {list(conn_data.keys())[:5]}...") # Print a few keys to check

# Example: Accessing the mean connection probability between L23_PC and L4_SS
pmat_example = conn_data['pmat']['L23_PC']['L4_SS']
print(f"Mean connection probability (L23_PC -> L4_SS): {pmat_example}")



"""# Construct the lookup table"""

import os

# Master Dictionary mapping acronyms to (Full Name, Type)
acronym_map = {
    # Excitatory Types
    'PC': ('Pyramidal Cell', 'Excitatory'),
    'SS': ('Spiny Stellate', 'Excitatory'),
    'SP': ('Star Pyramidal', 'Excitatory'),
    'TTPC1': ('Thick Tufted Pyramidal Cell 1', 'Excitatory'),
    'TTPC2': ('Thick Tufted Pyramidal Cell 2', 'Excitatory'),
    'STPC': ('Slender Tufted Pyramidal Cell', 'Excitatory'),
    'UTPC': ('Untufted Pyramidal Cell', 'Excitatory'),
    'BPC': ('Bipolar Pyramidal Cell', 'Excitatory'),
    'IPC': ('Inverted Pyramidal Cell', 'Excitatory'),
    'TPC_L1': ('Tufted Pyramidal Cell (L1)', 'Excitatory'),
    'TPC_L4': ('Tufted Pyramidal Cell (L4)', 'Excitatory'),

    # Standard Inhibitory Types
    'LBC': ('Large Basket Cell', 'Inhibitory'),
    'NBC': ('Nest Basket Cell', 'Inhibitory'),
    'SBC': ('Small Basket Cell', 'Inhibitory'),
    'ChC': ('Chandelier Cell', 'Inhibitory'),
    'MC': ('Martinotti Cell', 'Inhibitory'),
    'BTC': ('Bitufted Cell', 'Inhibitory'),
    'DBC': ('Double Bouquet Cell', 'Inhibitory'),
    'BP': ('Bipolar Cell', 'Inhibitory'),
    'NGC': ('Neurogliaform Cell', 'Inhibitory'),
    'HAC': ('Horizontal Axon Cell', 'Inhibitory'),
    'DAC': ('Descending Axon Cell', 'Inhibitory'),
    'SAC': ('Small Axon Cell', 'Inhibitory'),

    # --- ADDED: L1 Specific Inhibitory Types ---
    'NGC-DA': ('Neurogliaform Cell with Dense Axonal Arborization', 'Inhibitory'),
    'NGC-SA': ('Neurogliaform Cell with Sparse Axonal Arborization', 'Inhibitory'),
    'DLAC': ('Deiters-Like Axon Cell', 'Inhibitory'),
    'SLAC': ('Single-Layer Axon Cell', 'Inhibitory')
}

file_path = 'S1-cells-distributions-Rat.txt'
valid_layers = {"L1", "L23", "L4", "L5", "L6"}

# Initialize the fast-readable variable
mtype_fast_lookup = {}

if not os.path.exists(file_path):
    print(f"Error: '{file_path}' not found. Please upload it to the 'anatomy' folder.")
else:
    with open(file_path, 'r') as f:
        for line in f.read().split('\n'):
            if line.strip():
                parts = line.split()
                if len(parts) >= 5:
                    metype, mtype, etype, n, m = parts[:5]

                    # Split the mtype to determine layer and acronym
                    mtype_parts = mtype.split('_', 1)
                    target_layer = mtype_parts[0]
                    acronym = mtype_parts[1] if len(mtype_parts) > 1 else mtype

                    # Handle acronym exceptions
                    if acronym == 'TPC' and len(mtype_parts) > 2:
                        acronym = f"TPC_{mtype_parts[2]}"

                    # Look up the biological type
                    _, bio_type = acronym_map.get(acronym, (acronym, 'Unknown'))

                    # If valid, populate the fast lookup dictionary directly
                    if target_layer in valid_layers and bio_type in ["Excitatory", "Inhibitory"]:
                        mtype_fast_lookup[mtype] = (target_layer, bio_type)


# --- Quick Test ---
test_cells = ['L23_LBC', 'L1_DLAC']
for cell in test_cells:
    if cell in mtype_fast_lookup:
        layer, cell_type = mtype_fast_lookup[cell]
        print(f"Success! {cell:<10} -> Layer: {layer:<4}, Type: {cell_type}")
    else:
        print(f"Failed! {cell} is still missing.")

"""# Construct the adjecency matrix"""

import numpy as np
from scipy.spatial.distance import cdist

import numpy as np
from scipy.spatial.distance import cdist
from scipy import sparse

def build_adjacency_matrix(cell_mtypes, cell_coords, conn_data, mtype_fast_lookup):
    """
    Optimized builder for massive 3D microcircuits using sparse matrices.
    Now also determines genetic markers based on emergent connectivity.
    """
    N = len(cell_mtypes)
    unique_mtypes = np.unique(cell_mtypes)

    all_rows = []
    all_cols = []

    mtype_indices = {m: np.where(cell_mtypes == m)[0] for m in unique_mtypes}

    for pre_mtype in unique_mtypes:
        pre_idx = mtype_indices[pre_mtype]
        coords_pre = cell_coords[pre_idx]

        for post_mtype in unique_mtypes:
            if post_mtype not in conn_data.get('best_fit', {}).get(pre_mtype, {}):
                continue

            post_idx = mtype_indices[post_mtype]
            coords_post = cell_coords[post_idx]
            d_sub = cdist(coords_pre, coords_post, metric='euclidean')
            fit_type = conn_data['best_fit'][pre_mtype][post_mtype]

            if fit_type == 'exp':
                a0 = float(conn_data['a0mat_exp'][pre_mtype][post_mtype])
                l = float(conn_data['lmat_exp'][pre_mtype][post_mtype])
                d0 = float(conn_data['d0_exp'][pre_mtype][post_mtype])
                p_sub = a0 * np.exp(-np.maximum(d_sub - d0, 0) / l)

            elif fit_type == 'gauss':
                a0 = float(conn_data['a0mat_gauss'][pre_mtype][post_mtype])
                l = float(conn_data['lmat_gauss'][pre_mtype][post_mtype])
                x0 = float(conn_data['x0_gauss'][pre_mtype][post_mtype])
                p_sub = a0 * np.exp(-((d_sub - x0)**2) / (l**2))

            else:
                p_sub = np.zeros_like(d_sub)
                dist_bins = [
                    (12.5, 'pmat12um'), (25.0, 'pmat25um'), (50.0, 'pmat50um'),
                    (75.0, 'pmat75um'), (100.0, 'pmat100um'), (125.0, 'pmat125um'),
                    (150.0, 'pmat150um'), (175.0, 'pmat175um'), (200.0, 'pmat200um'),
                    (225.0, 'pmat225um'), (250.0, 'pmat250um'), (275.0, 'pmat275um'),
                    (300.0, 'pmat300um'), (325.0, 'pmat325um'), (350.0, 'pmat350um'),
                    (375.0, 'pmat375um')
                ]
                prev_d = -1.0
                for max_d, bin_key in dist_bins:
                    try:
                        bin_prob = float(conn_data[bin_key][pre_mtype][post_mtype])
                    except (KeyError, ValueError, TypeError):
                        bin_prob = 0.0
                    mask = (d_sub > prev_d) & (d_sub <= max_d)
                    p_sub[mask] = bin_prob
                    prev_d = max_d

            trial = np.random.rand(*p_sub.shape) < p_sub
            local_rows, local_cols = np.where(trial)

            if len(local_rows) > 0:
                global_rows = pre_idx[local_rows]
                global_cols = post_idx[local_cols]

                mask_autapse = global_rows != global_cols
                all_rows.extend(global_rows[mask_autapse])
                all_cols.extend(global_cols[mask_autapse])

            del d_sub, p_sub, trial

    data = np.ones(len(all_rows), dtype=np.uint8)
    adj_matrix = sparse.csr_matrix((data, (all_rows, all_cols)), shape=(N, N))

    # ==========================================
    # ASSIGN GENETIC MARKERS BASED ON CONNECTIVITY
    # ==========================================
    cell_genetics = np.empty(N, dtype=object)

    # 1. Create a boolean mask of which cells are Excitatory
    is_exc = np.array([mtype_fast_lookup[m][1] == 'Excitatory' for m in cell_mtypes])
    is_inh = ~is_exc

    # Excitatory cells are 'PY'
    cell_genetics[is_exc] = 'PY'

    # 2. Count how many Excitatory targets each cell connects to
    # adj_matrix dot product with the boolean 'is_exc' array calculates
    # the sum of excitatory connections along each row efficiently.
    targets_exc_count = adj_matrix.dot(is_exc.astype(int))

    # 3. Inhibitory cells targeting NO excitatory cells -> VIP
    is_vip = is_inh & (targets_exc_count == 0)
    cell_genetics[is_vip] = 'VIP'

    # 4. Inhibitory cells targeting at least 1 excitatory cell -> SST (3/5) or PV (2/5)
    is_sst_pv = is_inh & (targets_exc_count > 0)
    num_sst_pv = is_sst_pv.sum()

    if num_sst_pv > 0:
        cell_genetics[is_sst_pv] = np.random.choice(
            ['SST', 'PV'],
            size=num_sst_pv,
            p=[3/5, 2/5]
        )

    return adj_matrix, cell_genetics




import numpy as np

import os
import numpy as np

def generate_microcolumn_cells(input_dict, bbp_results, verbose=True, output_folder=None):
    """
    Generates cell m-types and 3D coordinates based on top-level densities
    and biological percentage breakdowns.
    """
    radius = input_dict['Geometry']['radius']

    base_mtypes_list = []
    coords_list = []

    area = np.pi * (radius ** 2)

    if verbose:
        print("BUILDING MICROCIRCUIT...")
        print("="*40)

    for layer, bio_types in input_dict['Cells'].items():
        if layer not in input_dict['Layers']:
            if verbose: print(f"Warning: Z-boundaries for '{layer}' not defined. Skipping.")
            continue

        bounds = input_dict['Layers'][layer]
        z_min, z_max = min(bounds), max(bounds)
        layer_height = z_max - z_min
        volume_um3 = area * layer_height

        if verbose:
            print(f"\n--- {layer} (Height: {layer_height} um) ---")

        for raw_bio_type, density_mm3 in bio_types.items():
            if density_mm3 <= 0:
                continue

            bio_type = 'Inhibitory' if raw_bio_type.lower().startswith('inh') else 'Excitatory'
            density_um3 = density_mm3 / 1e9
            total_group_count = int(np.round(density_um3 * volume_um3))

            if total_group_count <= 0:
                continue

            if layer not in bbp_results or bio_type not in bbp_results[layer]:
                if verbose: print(f"  Warning: BBP results for {layer} {bio_type} not found. Skipping.")
                continue

            if verbose:
                print(f"  {bio_type} (Target Total: ~{total_group_count} cells):")

            mtype_data = bbp_results[layer][bio_type]

            for mtype, data in mtype_data.items():
                percentage = data['percentage']
                count = int(np.round(total_group_count * (percentage / 100.0)))

                if count <= 0:
                    continue

                if verbose:
                    print(f"    -> {mtype:<12}: {count:>5} cells ({percentage:>5.2f}%)")

                r_random = radius * np.sqrt(np.random.rand(count))
                theta_random = np.random.rand(count) * 2 * np.pi

                x = r_random * np.cos(theta_random)
                y = r_random * np.sin(theta_random)
                z = np.random.uniform(z_min, z_max, count)

                coords = np.column_stack((x, y, z))
                coords_list.append(coords)

                base_mtypes = np.full(count, mtype, dtype=object)
                base_mtypes_list.append(base_mtypes)

    if base_mtypes_list:
        cell_mtypes = np.concatenate(base_mtypes_list)
        cell_coords = np.vstack(coords_list)
        if verbose:
            print("="*40)
            print(f"SUCCESS: Generated {len(cell_mtypes)} total neurons.")
    else:
        cell_mtypes = np.array([], dtype=object)
        cell_coords = np.empty((0, 3))
        if verbose:
            print("WARNING: No cells were generated. Check your input dictionary.")

    if output_folder:
        os.makedirs(output_folder, exist_ok=True)
        mtypes_path = os.path.join(output_folder, 'cell_mtypes.npy')
        coords_path = os.path.join(output_folder, 'cell_coords.npy')

        np.save(mtypes_path, cell_mtypes)
        np.save(coords_path, cell_coords)

        if verbose:
            print(f"Data saved to: {output_folder}")

    return cell_mtypes, cell_coords


import matplotlib.pyplot as plt
import numpy as np


import numpy as np
import plotly.graph_objects as go
from scipy import sparse

def plot_interactive_adjacency_matrix(adj_matrix, cell_mtypes=None, max_cells=3000):
    """
    Plots a highly interactive, WebGL-accelerated microcircuit adjacency matrix using Plotly.
    Supports zooming, panning, and hover-tooltips to identify specific synaptic pathways.
    """

    N = adj_matrix.shape[0]

    # 1. Subsample if necessary
    if N > max_cells:
        print(f"Notice: Matrix too large ({N}x{N}). Subsampling to a {max_cells}x{max_cells} block.")
        plot_matrix = adj_matrix[:max_cells, :max_cells]
        plot_mtypes = cell_mtypes[:max_cells] if cell_mtypes is not None else None
    else:
        plot_matrix = adj_matrix
        plot_mtypes = cell_mtypes

    # 2. Sort by m-type to reveal pathway structures
    if plot_mtypes is not None:
        sort_idx = np.argsort(plot_mtypes)
        plot_matrix = plot_matrix[sort_idx, :][:, sort_idx]
        plot_mtypes = plot_mtypes[sort_idx]

    # 3. Extract Coordinates for the Scatter Plot
    # We only plot the '1's (connections) to save massive amounts of memory
    if sparse.issparse(plot_matrix):
        rows, cols = plot_matrix.nonzero()
    else:
        rows, cols = np.where(plot_matrix > 0)

    # 4. Generate Hover Text
    if plot_mtypes is not None:
        # Vectorized string concatenation is much faster than a loop
        hover_text = "Pre: " + plot_mtypes[rows].astype(str) + "<br>Post: " + plot_mtypes[cols].astype(str)
    else:
        hover_text = [f"Pre: {r}<br>Post: {c}" for r, c in zip(rows, cols)]

    # 5. Build the WebGL Scatter Plot
    # Scattergl uses the GPU, which is mandatory for >10,000 points
    fig = go.Figure(data=go.Scattergl(
        x=cols,
        y=rows,
        mode='markers',
        marker=dict(size=2, color='#001933', opacity=0.7),
        text=hover_text,
        hoverinfo='text'
    ))

    # 6. Advanced Labeling and Layer Highlighting
    if plot_mtypes is not None:
        unique_mtypes, indices = np.unique(plot_mtypes, return_index=True)
        sort_order = np.argsort(indices)
        boundaries = indices[sort_order]
        ordered_mtypes = unique_mtypes[sort_order]

        layer_bounds = []
        current_layer = None

        # --- NEW: Filtered lists for labels ---
        filtered_centers = []
        filtered_ticktext = []
        N_plot = plot_matrix.shape[0]

        # Threshold: Population must be at least 1.5% of the displayed matrix to get a text label
        min_width_threshold = N_plot * 0.015

        for i in range(len(boundaries)):
            start = boundaries[i]
            end = boundaries[i+1] if i+1 < len(boundaries) else N_plot
            width = end - start
            center = (start + end) / 2.0

            # Track layer boundaries for shading
            layer_prefix = ordered_mtypes[i].split('_')[0]
            if layer_prefix != current_layer:
                layer_bounds.append((start, layer_prefix))
                current_layer = layer_prefix

            # Draw subtle dashed dividers for EVERY population (even the tiny ones)
            if start > 0:
                fig.add_hline(y=start, line_dash="dash", line_color="#2b2b2b", opacity=0.3, line_width=1)
                fig.add_vline(x=start, line_dash="dash", line_color="#2b2b2b", opacity=0.3, line_width=1)

            # ONLY add the text label if the population block is wide enough
            if width >= min_width_threshold:
                filtered_centers.append(center)
                filtered_ticktext.append(ordered_mtypes[i])

        # Pastel Layer Colors
        layer_colors = {
            'L1':  '#FF9999', 'L23': '#FFCC99',
            'L4':  '#99FF99', 'L5':  '#99CCFF', 'L6':  '#CC99FF'
        }

        # Apply the colored shading as background rectangles
        for i in range(len(layer_bounds)):
            start_l = layer_bounds[i][0]
            layer_name = layer_bounds[i][1]
            end_l = layer_bounds[i+1][0] if i+1 < len(layer_bounds) else N_plot

            rect_color = layer_colors.get(layer_name, '#E0E0E0')

            fig.add_vrect(x0=start_l, x1=end_l, fillcolor=rect_color, opacity=0.2, layer="below", line_width=0)
            fig.add_hrect(y0=start_l, y1=end_l, fillcolor=rect_color, opacity=0.2, layer="below", line_width=0)

        # Apply the dynamically filtered Subpopulation Labels to Axes
        fig.update_xaxes(tickvals=filtered_centers, ticktext=filtered_ticktext, tickangle=90, side='bottom', tickfont=dict(size=10))
        fig.update_yaxes(tickvals=filtered_centers, ticktext=filtered_ticktext, tickfont=dict(size=10))

    # 7. Final Layout Adjustments
    fig.update_layout(
        title=dict(text="Interactive Microcircuit Adjacency Matrix", font=dict(size=24), x=0.5),
        xaxis_title="Post-Synaptic Population",
        yaxis_title="Pre-Synaptic Population",
        yaxis=dict(autorange="reversed"), # Reverses Y axis so (0,0) is top-left like Matplotlib spy
        width=1000,
        height=1000,
        plot_bgcolor='white',
        margin=dict(l=150, b=150, t=80, r=40) # Add margin room for the rotated text labels
    )

    fig.show()

# If using in a local script (not Jupyter), you might want to save it as an HTML file instead:
# fig.write_html("interactive_matrix.html")

# ==========================================
# Example Usage
# ==========================================
'''

Density values taken from: A petavoxel fragment of human cerebral cortex reconstructed at nanoscale resolution

Layer depths taken from: Dendritic and Axonal Architecture of Individual  Pyramidal Neurons across Layers of Adult Human  Neocortex




'''
import json

# Define the path to your saved file
json_path = 'bbp_composition.json'

with open(json_path, 'r') as f:
    bbp_results = json.load(f)




# 1. Build the convergence dictionary from the text file
convergence_Th = {
    'VPM_sTC': {},
    'VPL_sTC': {},
    'POm_sTC_s1': {}
}

with open('convergence_Th_S1.txt', 'r') as f:
    for line in f:
        if not line.strip():
            continue
        # The file columns: Target_mtype, VPM_count, POm_count, Group
        parts = line.split()
        mtype = parts[0]
        preFO = int(parts[1]) # First-Order (VPM/VPL)
        preHO = int(parts[2]) # Higher-Order (POm)

        # Populate the dictionary
        convergence_Th['VPM_sTC'][mtype] = preFO
        convergence_Th['VPL_sTC'][mtype] = preFO
        convergence_Th['POm_sTC_s1'][mtype] = preHO





print("Successfully loaded bbp_results from JSON!")
# Example: Check L23 Inhibitory percentage for LBCs
print(f"L23_LBC presence: {bbp_results['L23']['Inhibitory']['L23_LBC']['percentage']:.2f}%")

column_input = {
    'Layers': {
        'L1':  [-250.0, 0.0],
        'L23': [-1200.0, -250.0],
        'L4':  [-1580.0, -1200.0],
        'L5':  [-2175.0, -1580.0],
        'L6':  [-2770.0, -2175.0]
    },
    'Cells': {
        'L1':  {'inh': 5145.9},                        # L1 only has inhibitory cells
        'L23': {'exc': 21466.6+8927.3, 'inh': 11655.3 + 5118.9},
        'L4':  {'exc': 23201.8, 'inh': 5502.3},           # Your example format
        'L5':  {'Excitatory': 10297.6, 'Inhibitory': 3249.9}, # Explicit keys work too
        'L6':  {'exc': 9823.0, 'inh': 1427.2}
    },
    'Geometry': {
        'radius': 300.0 # micrometers
    }
}


mtypes, coords = generate_microcolumn_cells(column_input, bbp_results, verbose=True,output_folder='/content/drive/MyDrive/Colab Notebooks/Connectomics/')


print(f"Generated {len(mtypes)} total cells.")
print(f"First 5 coords:\n{coords[:5]}")

# 3. Generate the matrix
adj_matrix,gtypes = build_adjacency_matrix(mtypes, coords, conn_data,mtype_fast_lookup)





plot_interactive_adjacency_matrix(adj_matrix, cell_mtypes=mtypes, max_cells=20000)

"""# Construct connectivity dictionaries and test"""

import numpy as np
from scipy import sparse

def rebuild_and_verify_matrix(original_matrix, pre_to_post):
    """
    Rebuilds the adjacency matrix from a dictionary and verifies exact equality.

    Parameters:
    - original_matrix: scipy.sparse.csr_matrix (The ground truth matrix)
    - pre_to_post: Dict (Efferent connections generated previously)

    Returns:
    - rebuilt_matrix: scipy.sparse.csr_matrix (The reconstructed matrix)
    - is_identical: Boolean (True if perfectly matched, False otherwise)
    """
    # 1. Get the original dimensions to ensure the rebuilt matrix is exactly the same size.
    # (This prevents dimension mismatches if the very last neurons had 0 connections).
    N = original_matrix.shape[0]

    rows = []
    cols = []

    # 2. Extract the coordinates from the dictionary
    for pre_id, post_ids in pre_to_post.items():
        rows.extend([pre_id] * len(post_ids))
        cols.extend(post_ids)

    # 3. Create the data array (all 1s for our unweighted connections)
    data = np.ones(len(rows), dtype=np.uint8)

    # 4. Reconstruct the sparse CSR matrix
    rebuilt_matrix = sparse.csr_matrix((data, (rows, cols)), shape=(N, N))

    # 5. The Verification Step
    # Subtracting/comparing sparse matrices natively returns another sparse matrix.
    # If they are perfectly identical, the resulting boolean matrix will have zero 'True' values.
    difference = (original_matrix != rebuilt_matrix)
    is_identical = (difference.nnz == 0)

    return rebuilt_matrix, is_identical



import os
import pickle
import numpy as np
from scipy import sparse

def extract_connectivity_dicts(adj_matrix, output_folder=None):
    """
    Extracts pre-to-post and post-to-pre connectivity dictionaries from a sparse adjacency matrix.
    Optionally saves them as high-efficiency pickle files if an output folder is provided.

    Parameters:
    - adj_matrix: scipy.sparse.csr_matrix (Shape: N x N)
    - output_folder: str, path to the directory where files should be saved (optional).

    Returns:
    - post_to_pre: Dict where Key = Post-synaptic ID, Value = List of Pre-synaptic IDs
    - pre_to_post: Dict where Key = Pre-synaptic ID, Value = List of Post-synaptic IDs
    """
    N = adj_matrix.shape[0]

    # 1. Pre-synaptic focus (Outputs / Efferent connections)
    pre_to_post = {}
    for i in range(N):
        start_idx = adj_matrix.indptr[i]
        end_idx = adj_matrix.indptr[i+1]

        if start_idx != end_idx:
            pre_to_post[i] = adj_matrix.indices[start_idx:end_idx].tolist()

    # 2. Post-synaptic focus (Inputs / Afferent connections)
    csc_matrix = adj_matrix.tocsc()
    post_to_pre = {}
    for j in range(N):
        start_idx = csc_matrix.indptr[j]
        end_idx = csc_matrix.indptr[j+1]

        if start_idx != end_idx:
            post_to_pre[j] = csc_matrix.indices[start_idx:end_idx].tolist()


    # Check that the dictionaries are reliable
    zzzz, success = rebuild_and_verify_matrix(adj_matrix, pre_to_post)
    if success:
        print("Verification Passed! The dictionaries perfectly represent the adjacency matrix.")
    else:
        print("Verification Failed! Discrepancy detected.")

    # 3. Save to disk if requested
    if output_folder and success:
        # Ensure the target directory exists
        os.makedirs(output_folder, exist_ok=True)

        pre_to_post_path = os.path.join(output_folder, 'pre_to_post.pkl')
        post_to_pre_path = os.path.join(output_folder, 'post_to_pre.pkl')

        # Save using the highest protocol for maximum compression and speed
        with open(pre_to_post_path, 'wb') as f:
            pickle.dump(pre_to_post, f, protocol=pickle.HIGHEST_PROTOCOL)

        with open(post_to_pre_path, 'wb') as f:
            pickle.dump(post_to_pre, f, protocol=pickle.HIGHEST_PROTOCOL)

        print(f"Dictionaries successfully saved to:")
        print(f" - {pre_to_post_path}")
        print(f" - {post_to_pre_path}")

    return post_to_pre, pre_to_post






post_to_pre_dict, pre_to_post_dict = extract_connectivity_dicts(adj_matrix,output_folder = '/content/drive/MyDrive/Colab Notebooks/Connectomics/')


rebuilt_adj, success = rebuild_and_verify_matrix(adj_matrix, pre_to_post_dict)

if success:
    print("Verification Passed! The dictionaries perfectly represent the adjacency matrix.")
else:
    print("Verification Failed! Discrepancy detected.")

"""# Add thalamic connections"""

import numpy as np
import math

import numpy as np
import math

def add_independent_thalamic_sources(mtypes, gtypes, post_to_pre, convergence_data):
    """
    Appends independent virtual thalamic sources to the cortical network.
    Handles mtypes and gtypes as NumPy arrays.
    """
    # 1. Convert NumPy arrays to Python lists for efficient appending
    mtypes_list = mtypes.tolist() if isinstance(mtypes, np.ndarray) else list(mtypes)
    gtypes_list = gtypes.tolist() if isinstance(gtypes, np.ndarray) else list(gtypes)

    # 2. Find the starting ID for virtual cells
    # In an array, the cell IDs are exactly the indices (0 to N-1)
    # Therefore, the next available ID is simply the current length of the array
    current_virtual_id = len(mtypes_list)
    original_num_cells = len(mtypes_list)

    synapses_per_source = 9.0

    # Iterate only over the original cortical cells (from index 0 to original_num_cells - 1)
    for post_id in range(original_num_cells):
        cortical_mtype = mtypes_list[post_id]

        # Ensure the cell exists in the post_to_pre structure
        if post_id not in post_to_pre:
            post_to_pre[post_id] = []

        # Add VPM, VPL, and POm sources
        for th_pop in ['VPM', 'VPL', 'POm']:

            # Map the clean label to the dictionary keys
            th_key = th_pop + '_sTC' if th_pop in ['VPM', 'VPL'] else 'POm_sTC_s1'

            if th_key not in convergence_data or cortical_mtype not in convergence_data[th_key]:
                continue

            raw_target = convergence_data[th_key][cortical_mtype]
            if raw_target <= 0:
                continue

            # Calculate how many independent virtual sources this cell needs
            required_sources = int(np.ceil(raw_target / synapses_per_source))

            # Generate the specific unique IDs for these sources
            for _ in range(required_sources):
                # Append the generic 'TC' label
                mtypes_list.append('TC')

                # Append the specific thalamic nucleus
                gtypes_list.append(th_pop)

                # Attach the new pre-synaptic ID to the cortical neuron
                post_to_pre[post_id].append(current_virtual_id)

                # Increment the global counter to guarantee independence
                current_virtual_id += 1

    # 3. Convert back to NumPy arrays before returning
    return np.array(mtypes_list), np.array(gtypes_list), post_to_pre


mtypes_, gtypes_, post_to_pre_= add_independent_thalamic_sources(mtypes, gtypes, post_to_pre_dict, convergence_Th)

# import numpy as np

# def validate_thalamic_sources(original_cortical_ids, mtypes, gtypes, post_to_pre, convergence_data):
#     """
#     Validates the integrity of the thalamic connectivity builder.
#     Handles mtypes and gtypes as NumPy arrays.
#     """
#     errors = []
#     synapses_per_source = 9.0

#     # 1. Check Strict Independence
#     all_assigned_thalamic_ids = []
#     for post_id in original_cortical_ids:
#         pre_list = post_to_pre.get(post_id, [])

#         # CORRECTED: Check if the index is within bounds, then check its value
#         thalamic_pres = [
#             pre_id for pre_id in pre_list
#             if pre_id < len(gtypes) and str(gtypes[pre_id]) in ['VPM', 'VPL', 'POm']
#         ]
#         all_assigned_thalamic_ids.extend(thalamic_pres)

#     if len(all_assigned_thalamic_ids) != len(set(all_assigned_thalamic_ids)):
#         errors.append("INDEPENDENCE BUG: Some cortical cells are sharing the same virtual thalamic source ID.")

#     # 2. Check Dictionary/Array Consistency
#     for th_id in all_assigned_thalamic_ids:
#         if th_id >= len(mtypes):
#             errors.append(f"CONSISTENCY BUG: Thalamic ID {th_id} is out of bounds for mtypes array.")
#         elif str(mtypes[th_id]) != 'TC':
#             errors.append(f"CONSISTENCY BUG: Thalamic ID {th_id} has mtype '{mtypes[th_id]}' instead of 'TC'.")

#         if th_id >= len(gtypes):
#             errors.append(f"CONSISTENCY BUG: Thalamic ID {th_id} is out of bounds for gtypes array.")
#         elif str(gtypes[th_id]) not in ['VPM', 'VPL', 'POm']:
#             errors.append(f"CONSISTENCY BUG: Thalamic ID {th_id} has invalid gtype '{gtypes[th_id]}'.")

#     # 3. Check Mathematical Accuracy (Convergence)
#     error_limit = 10
#     math_errors = 0

#     for post_id in original_cortical_ids:
#         cortical_mtype = str(mtypes[post_id])

#         # Count actual assigned sources
#         actual_counts = {'VPM': 0, 'VPL': 0, 'POm': 0}
#         for pre_id in post_to_pre.get(post_id, []):
#             # CORRECTED: Safe array indexing
#             if pre_id < len(gtypes):
#                 th_nuc = str(gtypes[pre_id])
#                 if th_nuc in actual_counts:
#                     actual_counts[th_nuc] += 1

#         # Calculate expected sources
#         for th_pop in ['VPM', 'VPL', 'POm']:
#             th_key = th_pop + '_sTC' if th_pop in ['VPM', 'VPL'] else 'POm_sTC_s1'

#             if th_key in convergence_data and cortical_mtype in convergence_data[th_key]:
#                 raw_target = convergence_data[th_key][cortical_mtype]
#                 expected_count = int(np.ceil(max(0, raw_target) / synapses_per_source))
#             else:
#                 expected_count = 0

#             if actual_counts[th_pop] != expected_count:
#                 math_errors += 1
#                 if math_errors <= error_limit:
#                     errors.append(f"MATH BUG for Cell {post_id} ({cortical_mtype}): "
#                                   f"Expected {expected_count} {th_pop} sources, but found {actual_counts[th_pop]}.")

#     if math_errors > error_limit:
#         errors.append(f"... and {math_errors - error_limit} more math errors suppressed.")

#     # --- Final Report ---
#     if not errors:
#         print("✅ VALIDATION PASSED: All thalamic sources are mathematically accurate, perfectly independent, and properly typed.")
#         return True
#     else:
#         print("❌ VALIDATION FAILED with the following hidden bugs:")
#         for error in errors:
#             print(f"  - {error}")
#         return False







# # Create a list of the original IDs [0, 1, 2, ..., N-1]
# original_cortical_ids = list(range(len(mtypes)))



# # 3. Run the validator
# is_safe = validate_thalamic_sources(
#     original_cortical_ids,
#     mtypes_,
#     gtypes_,
#     post_to_pre_,
#     convergence_Th
# )

# if not is_safe:
#     raise RuntimeError("Thalamic connection buildup contains errors. Halting simulation prep.")

print(gtypes_)

import numpy as np
import matplotlib.pyplot as plt

def plot_genetic_distribution(cell_mtypes,cells_gtypes):
    """
    Plots the distribution of genetic types (PY, SST, PV, VIP) across cortical layers.

    Parameters:
    - cell_mtypes: 2D numpy array of shape (N, 2) containing (m-type, genetic_type).
    """
    if cell_mtypes.size == 0:
        print("Error: The cell_mtypes array is empty.")
        return

    # 1. Extract layers and genetic markers
    # The layer is the prefix before the first underscore in the m-type (column 0)
    layers = np.array([m.split('_')[0] for m in cell_mtypes])
    genetic_types = cells_gtypes

    # Define the ordered categories we want to plot
    unique_layers = ['L1', 'L23', 'L4', 'L5', 'L6']
    target_genetics = ['PY', 'SST', 'PV', 'VIP']

    # 2. Count occurrences for each genetic type per layer
    counts = {g: [] for g in target_genetics}

    for layer in unique_layers:
        layer_mask = (layers == layer)
        layer_genetics = genetic_types[layer_mask]

        for g in target_genetics:
            counts[g].append(np.sum(layer_genetics == g))

    # 3. Build the grouped bar chart
    x = np.arange(len(unique_layers))  # the label locations
    width = 0.2  # the width of the bars

    fig, ax = plt.subplots(figsize=(10, 6), dpi=100)

    # Distinct colors for Excitatory (Blue) and Inhibitory (Warm colors)
    colors = {'PY': '#1f77b4', 'SST': '#ff7f0e', 'PV': '#2ca02c', 'VIP': '#d62728'}

    # Plot bars iteratively
    for i, g in enumerate(target_genetics):
        # Calculate the offset to group bars side-by-side
        offset = (i - 1.5) * width

        # Replace 0s with a tiny number just for the log scale to render properly
        safe_counts = [c if c > 0 else 0.1 for c in counts[g]]

        bars = ax.bar(x + offset, safe_counts, width, label=g, color=colors[g], zorder=3)

        # Optional: Add text labels on top of the bars for exact numbers
        for bar, raw_count in zip(bars, counts[g]):
            if raw_count > 0:
                yval = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2, yval * 1.1, int(raw_count),
                        ha='center', va='bottom', fontsize=8, rotation=90)

    # 4. Formatting
    ax.set_ylabel('Number of Cells (Log Scale)', fontsize=12)
    ax.set_xlabel('Cortical Layer', fontsize=12)
    ax.set_title('Distribution of Genetic Subpopulations across Layers', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(unique_layers)

    # Using a log scale because PY cells vastly outnumber PV/SST/VIP
    ax.set_yscale('log')
    ax.set_ylim(bottom=1) # Set bottom to 1 to avoid log(0) distortion

    ax.legend(title='Genetic Type')
    ax.grid(axis='y', linestyle='--', alpha=0.7, zorder=0)

    plt.tight_layout()
    plt.show()


import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict

def plot_thalamic_distribution(mtypes, gtypes, post_to_pre, filename='thalamic_distribution_per_layer.png'):
    """
    Calculates and plots the distribution of independent thalamic sources
    ('VPM', 'VPL', 'POm') per cortical layer.
    Handles mtypes and gtypes as NumPy arrays.
    """

    layer_counts = defaultdict(lambda: {'VPM': 0, 'VPL': 0, 'POm': 0})

    # 1. Aggregate the Data
    for post_id, pre_list in post_to_pre.items():
        # Safe array indexing instead of .get()
        if post_id >= len(mtypes):
            continue

        post_mtype = str(mtypes[post_id])

        # Skip if the post_id doesn't have a valid mtype (or is a thalamic cell itself)
        if not post_mtype or post_mtype == 'TC' or post_mtype == 'nan':
            continue

        # Extract the layer prefix from the mtype (e.g., 'L4_PC' -> 'L4')
        layer = post_mtype.split('_')[0]

        # Count the sources attached to this specific cell
        for pre_id in pre_list:
            # Safe array indexing for the pre-synaptic genetic type
            if pre_id < len(gtypes):
                th_nucleus = str(gtypes[pre_id])
                if th_nucleus in ['VPM', 'VPL', 'POm']:
                    layer_counts[layer][th_nucleus] += 1

    # 2. Prepare Data for Plotting
    ordered_layers = ['L1', 'L23', 'L4', 'L5', 'L6']
    active_layers = [l for l in ordered_layers if l in layer_counts]

    if not active_layers:
        print("Warning: No valid cortical layers found to plot.")
        return

    vpm_counts = [layer_counts[l]['VPM'] for l in active_layers]
    vpl_counts = [layer_counts[l]['VPL'] for l in active_layers]
    pom_counts = [layer_counts[l]['POm'] for l in active_layers]

    # 3. Create the Grouped Bar Chart
    x = np.arange(len(active_layers))
    width = 0.25

    fig, ax = plt.subplots(figsize=(10, 6))

    rects1 = ax.bar(x - width, vpm_counts, width, label='VPM (First-Order)', color='#1f77b4')
    rects2 = ax.bar(x, vpl_counts, width, label='VPL (First-Order)', color='#2ca02c')
    rects3 = ax.bar(x + width, pom_counts, width, label='POm (Higher-Order)', color='#d62728')

    # Add Text, Labels, and Formatting
    ax.set_ylabel('Total Independent Thalamic Sources')
    ax.set_xlabel('Cortical Layer')
    ax.set_title('Distribution of Thalamic Independent Sources per Layer')
    ax.set_xticks(x)
    ax.set_xticklabels(active_layers)
    ax.legend()

    ax.set_axisbelow(True)
    ax.yaxis.grid(True, linestyle='--', alpha=0.7)

    # # Save and close
    # plt.tight_layout()
    # plt.savefig(filename, dpi=300)
    # plt.close(fig)

    print(f"Plot successfully generated and saved as '{filename}'.")
# ==========================================
# Example Usage
# ==========================================
plot_genetic_distribution(mtypes,gtypes)


plot_thalamic_distribution(mtypes_, gtypes_, post_to_pre_)

def add_independent_background_sources(mtypes, gtypes, post_to_pre):
        """
        Appends independent virtual background (BG) sources to the cortical network.
        Adds exactly 10 independent sources (5 excitatory, 5 inhibitory) to every
        original cortical cell. Handles mtypes and gtypes as NumPy arrays.
        """


        # Protect against adding background noise to Thalamic cells if this is
        # called AFTER the thalamic function. We only want to target the original cortex.

        target_cells = list(range(len(mtypes)))


        # 1. Convert NumPy arrays to Python lists for efficient appending
        mtypes_list = mtypes.tolist() if isinstance(mtypes, np.ndarray) else list(mtypes)
        gtypes_list = gtypes.tolist() if isinstance(gtypes, np.ndarray) else list(gtypes)

        # 2. Find the starting ID for virtual cells
        current_virtual_id = len(mtypes_list)

        # Iterate only over the original cortical cells
        for post_id in target_cells:

            # Ensure the cell exists in the post_to_pre structure
            if post_id not in post_to_pre:
                post_to_pre[post_id] = []

            # --- Add 5 Excitatory Background Sources ---
            for _ in range(5):
                mtypes_list.append('BG')
                gtypes_list.append('BG_exc')
                post_to_pre[post_id].append(current_virtual_id)
                current_virtual_id += 1

            # --- Add 5 Inhibitory Background Sources ---
            for _ in range(5):
                mtypes_list.append('BG')
                gtypes_list.append('BG_inh')
                post_to_pre[post_id].append(current_virtual_id)
                current_virtual_id += 1

        # 3. Convert back to NumPy arrays
        return np.array(mtypes_list), np.array(gtypes_list),post_to_pre





mtypes__,gtypes__,post_to_pre__ = add_independent_background_sources(mtypes_, gtypes_, post_to_pre_)

"""# Check all"""

import numpy as np

def validate_all_virtual_sources(original_cortical_ids, mtypes, gtypes, post_to_pre, convergence_data):
    """
    Generalized validation function that checks the integrity of the network
    AFTER both Thalamic (TC) and Background (BG) virtual sources have been added.
    Handles mtypes and gtypes as NumPy arrays.
    """
    errors = []

    # Expected Constants based on your pipeline
    synapses_per_source = 9.0
    expected_bg_exc = 5
    expected_bg_inh = 5

    # 1. Check Strict Independence (Across EVERYTHING)
    all_assigned_virtual_ids = []
    for post_id in original_cortical_ids:
        pre_list = post_to_pre.get(post_id, [])

        # A virtual ID is any ID generated AFTER the original cortical network
        virtual_pres = [
            pre_id for pre_id in pre_list
            if pre_id >= len(original_cortical_ids)
        ]
        all_assigned_virtual_ids.extend(virtual_pres)

    # If there's a mismatch, it means two cortical cells share a virtual source
    if len(all_assigned_virtual_ids) != len(set(all_assigned_virtual_ids)):
        errors.append("INDEPENDENCE BUG: Some cortical cells are sharing the same virtual source ID (TC or BG collision).")

    # 2. Check Dictionary/Array Consistency
    for v_id in all_assigned_virtual_ids:
        if v_id >= len(mtypes) or v_id >= len(gtypes):
            errors.append(f"CONSISTENCY BUG: Virtual ID {v_id} is out of bounds for the arrays.")
            continue

        mtype_val = str(mtypes[v_id])
        gtype_val = str(gtypes[v_id])

        # Route checking for Thalamic Cells
        if gtype_val in ['VPM', 'VPL', 'POm']:
            if mtype_val != 'TC':
                errors.append(f"CONSISTENCY BUG: ID {v_id} is {gtype_val} but has mtype '{mtype_val}' instead of 'TC'.")

        # Route checking for Background Cells
        elif gtype_val in ['BG_exc', 'BG_inh']:
            if mtype_val != 'BG':
                errors.append(f"CONSISTENCY BUG: ID {v_id} is {gtype_val} but has mtype '{mtype_val}' instead of 'BG'.")

        else:
            errors.append(f"CONSISTENCY BUG: ID {v_id} has an unrecognized/invalid gtype '{gtype_val}'.")

    # 3. Check Mathematical Accuracy (Convergence)
    error_limit = 15
    math_errors = 0

    for post_id in original_cortical_ids:
        cortical_mtype = str(mtypes[post_id])

        # Count actual assigned sources for this specific cortical cell
        actual_counts = {'VPM': 0, 'VPL': 0, 'POm': 0, 'BG_exc': 0, 'BG_inh': 0}

        for pre_id in post_to_pre.get(post_id, []):
            if pre_id >= len(original_cortical_ids) and pre_id < len(gtypes):
                nuc = str(gtypes[pre_id])
                if nuc in actual_counts:
                    actual_counts[nuc] += 1

        # Calculate EXPECTED Thalamic sources
        for th_pop in ['VPM', 'VPL', 'POm']:
            th_key = th_pop + '_sTC' if th_pop in ['VPM', 'VPL'] else 'POm_sTC_s1'

            if th_key in convergence_data and cortical_mtype in convergence_data[th_key]:
                raw_target = convergence_data[th_key][cortical_mtype]
                expected_count = int(np.ceil(max(0, raw_target) / synapses_per_source))
            else:
                expected_count = 0

            if actual_counts[th_pop] != expected_count:
                math_errors += 1
                if math_errors <= error_limit:
                    errors.append(f"MATH BUG for Cell {post_id} ({cortical_mtype}): "
                                  f"Expected {expected_count} {th_pop} sources, but found {actual_counts[th_pop]}.")

        # Calculate EXPECTED Background sources
        if actual_counts['BG_exc'] != expected_bg_exc:
            math_errors += 1
            if math_errors <= error_limit:
                errors.append(f"MATH BUG for Cell {post_id} ({cortical_mtype}): "
                              f"Expected {expected_bg_exc} BG_exc sources, found {actual_counts['BG_exc']}.")

        if actual_counts['BG_inh'] != expected_bg_inh:
            math_errors += 1
            if math_errors <= error_limit:
                errors.append(f"MATH BUG for Cell {post_id} ({cortical_mtype}): "
                              f"Expected {expected_bg_inh} BG_inh sources, found {actual_counts['BG_inh']}.")

    if math_errors > error_limit:
        errors.append(f"... and {math_errors - error_limit} more math errors suppressed.")

    # --- Final Report ---
    if not errors:
        print("✅ FULL VALIDATION PASSED: All Thalamic and Background sources are mathematically accurate, perfectly independent, and properly typed.")
        return True
    else:
        print("❌ VALIDATION FAILED with the following hidden bugs:")
        for error in errors:
            print(f"  - {error}")
        return False


original_cortical_ids = list(range(len(mtypes)))
is_safe = validate_all_virtual_sources(
    original_cortical_ids,
    mtypes__,
    gtypes__,
    post_to_pre__,
    convergence_Th
)

import numpy as np
import plotly.graph_objects as go
from google.colab import output

def plot_3d_microcolumn_colab(cell_coords, cell_mtypes, radius=210.0, max_display=30000):
    """
    Plots an enlarged 3D visualization of the microcolumn with a pure black background.
    Optimized for high-contrast "Fluorescence" style visualization.
    """
    N = len(cell_coords)
    if N > max_display:
        idx = np.random.choice(N, max_display, replace=False)
        coords_to_plot, mtypes_to_plot = cell_coords[idx], cell_mtypes[idx]
    else:
        coords_to_plot, mtypes_to_plot = cell_coords, cell_mtypes

    layers = np.array([mtype.split('_')[0] for mtype in mtypes_to_plot])
    unique_layers = np.unique(layers)

    # Neon Fluorescence Palette
    layer_colors = {
        'L1': '#FF3366', 'L23': '#FFCC00', 'L4': '#33FF66',
        'L5': '#00CCFF', 'L6': '#B84DFF'
    }

    fig = go.Figure()

    # Add layer traces
    for layer in ['L1', 'L23', 'L4', 'L5', 'L6']:
        if layer not in unique_layers: continue
        mask = (layers == layer)
        fig.add_trace(go.Scatter3d(
            x=coords_to_plot[mask, 0], y=coords_to_plot[mask, 1], z=coords_to_plot[mask, 2],
            mode='markers', name=f"{layer} ({np.sum(mask)} cells)",
            text=[f"Type: {m}" for m in mtypes_to_plot[mask]], hoverinfo='text',
            marker=dict(size=2.5, color=layer_colors.get(layer, '#FFF'), opacity=0.9)
        ))

    # Boundary Wireframe (Transparent Cylinder)
    z_min, z_max = np.min(coords_to_plot[:, 2]), np.max(coords_to_plot[:, 2])
    theta = np.linspace(0, 2*np.pi, 50)
    z_cyl = np.linspace(z_min, z_max, 10)
    theta_grid, z_grid = np.meshgrid(theta, z_cyl)
    fig.add_trace(go.Surface(
        x=radius * np.cos(theta_grid), y=radius * np.sin(theta_grid), z=z_grid,
        colorscale=[[0, 'rgba(255,255,255,0.08)'], [1, 'rgba(255,255,255,0.08)']],
        showscale=False, hoverinfo='skip', name="Column Boundary"
    ))

    # Layout Optimization
    fig.update_layout(
        title=dict(text="S1 Microcolumn Culture", font=dict(size=26, color='white'), x=0.5),
        width=1100,
        height=900,
        paper_bgcolor='black', # True black outer background
        plot_bgcolor='black',  # True black inner plot background
        margin=dict(l=0, r=0, b=0, t=60),
        legend=dict(font=dict(color='white', size=14), x=0.85, y=0.9, bgcolor='rgba(0,0,0,0.5)'),

        scene_camera=dict(eye=dict(x=1.3, y=1.3, z=0.8)),

        scene=dict(
            xaxis=dict(
                title="X (µm)", color='white', gridcolor="#444",
                backgroundcolor='black', showbackground=True
            ),
            yaxis=dict(
                title="Y (µm)", color='white', gridcolor="#444",
                backgroundcolor='black', showbackground=True
            ),
            zaxis=dict(
                title="Depth (µm)", color='white', gridcolor="#444",
                backgroundcolor='black', showbackground=True
            ),
            aspectmode='data'
        )
    )

    fig.show(renderer="colab")

# --- Run the Plot ---
# plot_3d_microcolumn_colab(cell_coords, cell_mtypes, radius=210.0)

# Example Usage:
plot_3d_microcolumn_colab(coords, mtypes,radius=300)

"""# Evaluate fitting procedure"""

import numpy as np
import matplotlib.pyplot as plt

def plot_connection_probability(conn_data, pre_mtype, post_mtype, max_dist=500.0):
    """
    Plots the distance-dependent connection probability curve for a specific pathway.

    Parameters:
    - conn_data: Dictionary loaded from 'conn.pkl'.
    - pre_mtype: String, the pre-synaptic morphological type (e.g., 'L23_PC').
    - post_mtype: String, the post-synaptic morphological type (e.g., 'L4_SS').
    - max_dist: Float, the maximum distance in micrometers to plot on the x-axis.
    """

    # Check if the base pathway exists at all
    if pre_mtype not in conn_data.get('pmat', {}) or post_mtype not in conn_data['pmat'].get(pre_mtype, {}):
        print(f"Error: Pathway {pre_mtype} -> {post_mtype} not found in connectivity data.")
        return

    # Generate a high-resolution array of distances (X-axis)
    distances = np.linspace(0, max_dist, 1000)

    # Retrieve the fit type
    fit_type = conn_data.get('best_fit', {}).get(pre_mtype, {}).get(post_mtype, None)

    # Calculate probabilities (Y-axis) based on the fit type
    if fit_type == 'exp':
        a0 = float(conn_data['a0mat_exp'][pre_mtype][post_mtype])
        l  = float(conn_data['lmat_exp'][pre_mtype][post_mtype])
        d0 = float(conn_data['d0_exp'][pre_mtype][post_mtype])

        # P(d) = A0 * exp(-(d - d0)/lambda)
        probabilities = a0 * np.exp(-np.maximum(distances - d0, 0) / l)
        title_fit = "Exponential Decay"
        info_text = f"$A_0$ = {a0:.3f}\n$\lambda$ = {l:.1f} $\mu m$\n$d_0$ = {d0:.1f} $\mu m$"

    elif fit_type == 'gauss':
        a0 = float(conn_data['a0mat_gauss'][pre_mtype][post_mtype])
        l  = float(conn_data['lmat_gauss'][pre_mtype][post_mtype])
        x0 = float(conn_data['x0_gauss'][pre_mtype][post_mtype])

        # P(d) = A0 * exp(-((d - x0)^2) / lambda^2)
        probabilities = a0 * np.exp(-((distances - x0)**2) / (l**2))
        title_fit = "Gaussian Decay"
        info_text = f"$A_0$ = {a0:.3f}\n$\lambda$ = {l:.1f} $\mu m$\n$x_0$ = {x0:.1f} $\mu m$"

    else:
        # --- Fallback: Step-function empirical probability bins ---
        probabilities = np.zeros_like(distances)

        dist_bins = [
            (12.5, 'pmat12um'),   (25.0, 'pmat25um'),   (50.0, 'pmat50um'),
            (75.0, 'pmat75um'),   (100.0, 'pmat100um'), (125.0, 'pmat125um'),
            (150.0, 'pmat150um'), (175.0, 'pmat175um'), (200.0, 'pmat200um'),
            (225.0, 'pmat225um'), (250.0, 'pmat250um'), (275.0, 'pmat275um'),
            (300.0, 'pmat300um'), (325.0, 'pmat325um'), (350.0, 'pmat350um'),
            (375.0, 'pmat375um')
        ]

        prev_d = -1.0

        for max_d, bin_key in dist_bins:
            try:
                bin_prob = float(conn_data[bin_key][pre_mtype][post_mtype])
            except (KeyError, ValueError, TypeError):
                bin_prob = 0.0

            mask = (distances > prev_d) & (distances <= max_d)
            probabilities[mask] = bin_prob
            prev_d = max_d

        title_fit = "Empirical Step Function (No Spatial Fit)"

        try:
            mean_p = float(conn_data['pmat'][pre_mtype][post_mtype])
        except:
            mean_p = 0.0
        info_text = f"Binned Empirical Data\nGlobal Mean $P$ = {mean_p:.4f}"

    # --- Plotting ---
    plt.figure(figsize=(8, 5), dpi=100)

    # Plot the curve/steps
    plt.plot(distances, probabilities, color='crimson', linewidth=2.5, label=f'{pre_mtype} $\\rightarrow$ {post_mtype}')

    # Add a text box with the extracted mathematical parameters
    props = dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='gray')
    plt.gca().text(0.95, 0.95, info_text, transform=plt.gca().transAxes, fontsize=11,
                   verticalalignment='top', horizontalalignment='right', bbox=props)

    plt.title(f"Connection Probability: {pre_mtype} $\\rightarrow$ {post_mtype}\n({title_fit})", fontsize=14, pad=15)
    plt.xlabel(r"3D Euclidean Distance ($\mu m$)", fontsize=12)
    plt.ylabel("Probability of Connection $P(d)$", fontsize=12)

    # Scale Y axis gracefully
    y_max = max(probabilities) if max(probabilities) > 0 else 0.1
    plt.ylim(0, y_max * 1.2)
    plt.xlim(0, max_dist)

    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(loc='lower left')
    plt.tight_layout()
    plt.show()


# ==========================================
# Example Usage
# ==========================================
plot_connection_probability(conn_data, 'L1_DAC', 'L1_DAC', max_dist=400.0)

import os

def calculate_bbp_relative_presences(file_path='S1-cells-distributions-Rat.txt'):
    """
    Parses the BBP S1 distribution file and calculates the relative percentage
    of each m-type among all neurons of the same biological type in its layer.
    """

    # Expanded acronym map to include L1-specific inhibitory cells from the BBP data
    acronym_map = {
        # Excitatory Types
        'PC': 'Excitatory', 'SS': 'Excitatory', 'SP': 'Excitatory',
        'TTPC1': 'Excitatory', 'TTPC2': 'Excitatory', 'STPC': 'Excitatory',
        'UTPC': 'Excitatory', 'BPC': 'Excitatory', 'IPC': 'Excitatory',
        'TPC_L1': 'Excitatory', 'TPC_L4': 'Excitatory',

        # Inhibitory Types
        'LBC': 'Inhibitory', 'NBC': 'Inhibitory', 'SBC': 'Inhibitory',
        'ChC': 'Inhibitory', 'MC': 'Inhibitory', 'BTC': 'Inhibitory',
        'DBC': 'Inhibitory', 'BP': 'Inhibitory', 'NGC': 'Inhibitory',
        'HAC': 'Inhibitory', 'DAC': 'Inhibitory', 'SAC': 'Inhibitory',

        # L1 Specific Inhibitory Types
        'NGC-DA': 'Inhibitory', 'NGC-SA': 'Inhibitory',
        'DLAC': 'Inhibitory', 'SLAC': 'Inhibitory'
    }

    if not os.path.exists(file_path):
        print(f"Error: Could not find {file_path}")
        return None

    mtype_raw_counts = {}

    # 1. Parse the BBP text file
    with open(file_path, 'r') as f:
        for line in f:
            if line.strip():
                parts = line.split()
                if len(parts) >= 5:
                    mtype = parts[1]
                    m_count = int(parts[4]) # Column 5 'm' is the total m-type count

                    # Since the file lists multiple e-types per m-type,
                    # we just overwrite with the same 'm_count' total for that m-type
                    mtype_raw_counts[mtype] = m_count

    # 2. Group into layers and sum up the totals for Excitatory/Inhibitory
    layer_totals = {}
    composition = {}

    for mtype, count in mtype_raw_counts.items():
        mtype_parts = mtype.split('_', 1)
        layer = mtype_parts[0]
        acronym = mtype_parts[1] if len(mtype_parts) > 1 else mtype

        # Handle the TPC exceptions (e.g. 'TPC_L1', 'TPC_L4')
        if acronym.startswith('TPC'):
            acronym = mtype.replace(f"{layer}_", "")

        bio_type = acronym_map.get(acronym, 'Unknown')

        if layer not in composition:
            composition[layer] = {'Excitatory': {}, 'Inhibitory': {}}
            layer_totals[layer] = {'Excitatory': 0, 'Inhibitory': 0}

        if bio_type in ['Excitatory', 'Inhibitory']:
            composition[layer][bio_type][mtype] = count
            layer_totals[layer][bio_type] += count

    # 3. Calculate the relative percentages
    results = {}
    for layer in composition:
        results[layer] = {'Excitatory': {}, 'Inhibitory': {}}

        for bio_type in ['Excitatory', 'Inhibitory']:
            total_cells = layer_totals[layer][bio_type]

            for mtype, count in composition[layer][bio_type].items():
                perc = (count / total_cells * 100) if total_cells > 0 else 0.0
                results[layer][bio_type][mtype] = {
                    'count': count,
                    'percentage': perc
                }

    return results, layer_totals
import json
import csv
import os

def save_composition_results(results, json_path='bbp_composition.json', csv_path='bbp_composition.csv'):
    """
    Saves the nested results dictionary into both JSON and flattened CSV formats.
    """
    # 1. Save as JSON (keeps the Layer -> BioType -> MType structure)
    with open(json_path, 'w') as f:
        json.dump(results, f, indent=4)
    print(f"Successfully saved hierarchical data to: {json_path}")

    # 2. Save as CSV (flattens the data for Excel/Pandas)
    # Define headers
    headers = ['Layer', 'Biological_Type', 'MType', 'Count', 'Percentage']

    with open(csv_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(headers)

        for layer, types in results.items():
            for bio_type, mtypes in types.items():
                for mtype, data in mtypes.items():
                    writer.writerow([
                        layer,
                        bio_type,
                        mtype,
                        data['count'],
                        f"{data['percentage']:.4f}"
                    ])
    print(f"Successfully saved flattened table to: {csv_path}")
# ==========================================
# Execution and Report Generator
# ==========================================

# Run the parser
bbp_results, bbp_totals = calculate_bbp_relative_presences('S1-cells-distributions-Rat.txt')
# 2. Save the results
if bbp_results:
    save_composition_results(bbp_results)
if bbp_results:
    print("BBP ORIGINAL MICROCIRCUIT COMPOSITION")
    print("="*45)

    # Sort layers (L1, L23, L4, L5, L6)
    for layer in sorted(bbp_results.keys()):
        print(f"\n--- {layer} ---")

        for bio_type in ['Excitatory', 'Inhibitory']:
            total = bbp_totals[layer][bio_type]
            if total > 0:
                print(f"  {bio_type} (Total: {total}):")

                # Sort m-types by percentage (highest to lowest)
                mtypes_data = bbp_results[layer][bio_type]
                sorted_mtypes = sorted(mtypes_data.items(), key=lambda item: item[1]['percentage'], reverse=True)

                for mtype, data in sorted_mtypes:
                    perc = data['percentage']
                    count = data['count']
                    print(f"    • {mtype:<12}: {perc:>6.2f}%  ({count} cells)")

# 1. The Updated Extraction Function (Now includes 'cell_mtypes' and 'cell_gtypes')
def extract_macro_populations(connectomics_data, name_list):
    """
    Extracts specific macro-populations using the fast lookup table,
    returning only spatial coordinates, mapping indices, the integrated synapse dictionary,
    and the genetic types.
    """
    # Unpack only the necessary data
    mtype_fast_lookup = connectomics_data['mtype_fast_lookup']
    cell_mtypes = connectomics_data['cell_mtypes']
    cell_coords = connectomics_data['cell_coords']

    # NEW: Only grab the integrated synapse_dict
    synapse_dict = connectomics_data['synapse_dict']

    # NEW: Grab the genetic types array
    cell_gtypes = connectomics_data['cell_gtypes']

    extracted_data = {}

    for name in name_list:
        # 1. Parse the macro-population string (e.g., "L23_exc" -> "L23", "exc")
        parts = name.split('_')
        target_layer = parts[0].upper()
        target_group = parts[1].lower()

        global_indices = []

        # 2. Iterate through the array using the FAST LOOKUP
        for raw_idx, mtype in enumerate(cell_mtypes):
            if mtype not in mtype_fast_lookup:
                continue

            layer, bio_type = mtype_fast_lookup[mtype]

            # 3. Matching Logic
            is_match = False
            if layer == target_layer:
                if target_group == 'exc' and bio_type == 'Excitatory':
                    # Ensure L4_exc doesn't swallow L4_ss if both are requested
                    if target_layer == 'L4' and 'L4_ss' in name_list and 'SS' in mtype:
                        is_match = False
                    else:
                        is_match = True
                elif target_group == 'inh' and bio_type == 'Inhibitory':
                    is_match = True
                elif target_group == 'ss' and 'SS' in mtype:
                    is_match = True

            if is_match:
                global_indices.append(raw_idx)

        # 4. Process the matched sub-population
        global_indices = np.array(global_indices)

        if len(global_indices) == 0:
            print(f"Warning: No cells found for macro-population '{name}'")
            continue

        # Extract Coordinates (Made compliant: converted to list of dicts)
        sub_coords_raw = cell_coords[global_indices]
        sub_coords = [{'x': row[0], 'y': row[1], 'z': row[2]} for row in sub_coords_raw]

        # NEW: Extract the genetic types for the matched sub-population
        sub_gtypes = cell_gtypes[global_indices]

        # Create Mapping: Local (0 to N) -> Raw Global Index
        local_to_raw_map = {local_idx: raw_idx for local_idx, raw_idx in enumerate(global_indices)}

        # NEW: Filter the single synapse_dict (Keys are LOCAL, Values are RAW)
        sub_synapse_dict = {
            local_idx: synapse_dict[raw_idx]
            for local_idx, raw_idx in enumerate(global_indices) if raw_idx in synapse_dict
        }

        # 5. Pack strictly the requested keys into the return dictionary
        extracted_data[name] = {
            'cell_coords': sub_coords,
            'local_to_raw_map': local_to_raw_map,
            'synapse_dict': sub_synapse_dict,
            'cell_gtypes': sub_gtypes
        }

    return extracted_data

def extract_multapses(dat_file_path,post_to_pre,cell_mtypes,mtype_fast_lookup):
        """
        Constructs a dictionary mapping post-synaptic IDs to an Nx2 matrix of
        pre-synaptic IDs and their calculated multapse counts, with macro-population
        averaging for missing structural pathways. Accommodates external thalamic ('TC') inputs.
        """


        # 1. Parse the synNumberperconex.dat file as a text file
        file_path = 'synNumberperconex.dat'
        full_path_conn = os.path.join(dat_file_path, file_path)

        from collections import defaultdict

        # Nested dictionary to store specific mean and std
        syn_stats = defaultdict(dict)

        with open(full_path_conn, 'r') as f:
            for line in f:
                parts = line.split()
                if len(parts) >= 6:
                    mean_val = float(parts[2])
                    std_val = float(parts[3])
                    proj = parts[5]

                    if ':' in proj:
                        pre_mtype_str, post_mtype_str = proj.split(':')
                        syn_stats[pre_mtype_str][post_mtype_str] = {
                            'mean': mean_val,
                            'std': std_val
                        }

        # ---------------------------------------------------------
        # NEW: Calculate Macro-Population Averages for Imputation
        # ---------------------------------------------------------
        # Accumulator: Key = ((PreLayer, PreBio), (PostLayer, PostBio))
        macro_stats_accumulator = defaultdict(lambda: {'sum_mean': 0.0, 'sum_std': 0.0, 'count': 0})

        for pre_m, post_dict in syn_stats.items():
            pre_macro = mtype_fast_lookup.get(pre_m)
            if not pre_macro: continue # Skip if mtype isn't in our circuit

            for post_m, stats in post_dict.items():
                post_macro = mtype_fast_lookup.get(post_m)
                if not post_macro: continue

                macro_key = (pre_macro, post_macro)
                macro_stats_accumulator[macro_key]['sum_mean'] += stats['mean']
                macro_stats_accumulator[macro_key]['sum_std'] += stats['std']
                macro_stats_accumulator[macro_key]['count'] += 1

        # Calculate final averages
        macro_averages = {}
        for macro_key, acc in macro_stats_accumulator.items():
            if acc['count'] > 0:
                macro_averages[macro_key] = {
                    'mean': acc['sum_mean'] / acc['count'],
                    'std': acc['sum_std'] / acc['count']
                }
        # ---------------------------------------------------------

        multapse_dict = {}

        for post_idx, pre_indices in post_to_pre.items():
            if not pre_indices:
                continue

            post_mtype = cell_mtypes[post_idx]
            post_macro = mtype_fast_lookup.get(post_mtype)

            pre_array = np.array(pre_indices, dtype=int)
            pre_mtypes = cell_mtypes[pre_array]

            n_pre = len(pre_array)
            means = np.zeros(n_pre)
            stds = np.zeros(n_pre)

            # Populate means and stds based on the pathway
            for i, pre_mtype in enumerate(pre_mtypes):

                # ---> NEW CHANGE: Intercept Thalamic Sources <---
                if pre_mtype == 'TC':
                    means[i] = 9.0
                    stds[i] = 3.0
                    continue
                # ------------------------------------------------

                # ---> NEW CHANGE: Intercept Background Sources <---
                if pre_mtype == 'BG':
                    means[i] = 1.0
                    stds[i] = 0.0
                    continue
                # ------------------------------------------------

                try:
                    # Strategy A: Exact structural pathway match
                    means[i] = syn_stats[pre_mtype][post_mtype]['mean']
                    stds[i] = syn_stats[pre_mtype][post_mtype]['std']

                except KeyError:
                    # Strategy B: Impute using macro-population average
                    pre_macro = mtype_fast_lookup.get(pre_mtype)
                    macro_key = (pre_macro, post_macro)

                    if macro_key in macro_averages:
                        means[i] = macro_averages[macro_key]['mean']
                        stds[i] = macro_averages[macro_key]['std']
                    else:
                        # Strategy C: Absolute last resort to prevent crashes
                        means[i] = 1.0
                        stds[i] = 0.0

            # 2. Draw from the Gaussian distribution
            sampled_synapses = np.random.normal(loc=means, scale=stds)

            # 3. Clean the data (ensure at least 1 synapse if connected)
            n_synapses = np.maximum(1, np.round(sampled_synapses)).astype(int)

            # 4. Construct the N_pre x 2 matrix
            result_matrix = np.column_stack((pre_array, n_synapses))

            multapse_dict[post_idx] = result_matrix

        return multapse_dict

import matplotlib.pyplot as plt
import numpy as np

import matplotlib.pyplot as plt
import numpy as np

def plot_synapse_layer_distribution_log(mtypes, synapse_dict, filename='synapse_layer_distribution_log.png'):
    """
    Plots the distribution of incoming synapses for each post-synaptic layer,
    categorized by their pre-synaptic layer of origin.
    Uses a grouped bar chart with a logarithmic Y-axis.
    UPDATED: Now includes both Thalamic ('th') and Background ('bg') sources.
    """

    ordered_post = ['L1', 'L23', 'L4', 'L5', 'L6']
    ordered_pre = ['L1', 'L23', 'L4', 'L5', 'L6', 'th', 'bg']

    # Initialize a nested dictionary to store synapse counts
    counts = {post: {pre: 0 for pre in ordered_pre} for post in ordered_post}

    # 1. Aggregate the Synapse Data
    for post_id, matrix in synapse_dict.items():
        if post_id >= len(mtypes): continue

        post_mtype = str(mtypes[post_id])

        # Skip Thalamic and Background cells (they don't receive inputs in this plot)
        if post_mtype in ['TC', 'BG', 'nan']:
            continue

        post_layer = post_mtype.split('_')[0]
        if post_layer not in counts:
            continue

        # Iterate over the Nx2 matrix
        for row in matrix:
            pre_id = int(row[0])
            num_syn = int(row[1])

            if pre_id >= len(mtypes): continue
            pre_mtype = str(mtypes[pre_id])

            # ---> NEW CHANGE: Map the pre-synaptic layer including BG <---
            if pre_mtype == 'TC':
                pre_layer = 'th'
            elif pre_mtype == 'BG':
                pre_layer = 'bg'
            else:
                pre_layer = pre_mtype.split('_')[0]

            if pre_layer in counts[post_layer]:
                counts[post_layer][pre_layer] += num_syn

    # 2. Plotting the Grouped Bar Chart
    fig, ax = plt.subplots(figsize=(14, 7)) # Made slightly wider for the 7th bar
    x = np.arange(len(ordered_post))

    # Calculate widths for the grouped layout
    num_pre = len(ordered_pre)
    total_width = 0.8
    width = total_width / num_pre

    # Colors: Added a 7th color (#7f7f7f / Gray) for the Background sources
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#7f7f7f']

    for i, pre_layer in enumerate(ordered_pre):
        values = [counts[post][pre_layer] for post in ordered_post]

        # Calculate the specific X offset for this bar group
        offset = x - (total_width / 2) + (i * width) + (width / 2)

        # Clean up the labels for the legend
        if pre_layer == 'th':
            label_name = 'From Thalamus (TC)'
        elif pre_layer == 'bg':
            label_name = 'From Background (BG)'
        else:
            label_name = f'From {pre_layer}'

        # Plot the grouped bar
        ax.bar(offset, values, width, label=label_name, color=colors[i], edgecolor='white', linewidth=0.5)

    # Formatting
    ax.set_xticks(x)
    ax.set_xticklabels(ordered_post, fontsize=12)
    ax.set_ylabel('Total Number of Synapses (Log Scale)', fontsize=12)
    ax.set_xlabel('Target (Post-Synaptic) Layer', fontsize=12)
    ax.set_title('Distribution of Incoming Synapses by Layer of Origin', fontsize=14, pad=15)

    # ---> Set Log Scale <---
    ax.set_yscale('log')
    # Set bottom limit to 1 so that layers with 0 connections don't break the log axis
    ax.set_ylim(bottom=1)

    # Move the legend outside the plot
    ax.legend(title='Pre-Synaptic Origin', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=11)

    ax.set_axisbelow(True)
    ax.yaxis.grid(True, linestyle='--', alpha=0.7)

    # # Clean up and save
    # plt.tight_layout()
    # plt.savefig(filename, dpi=300)
    # plt.close(fig)

    print(f"Plot successfully generated and saved as '{filename}'.")


multapse_dict = extract_multapses(connectomics_path,post_to_pre__,mtypes__,mtype_fast_lookup)


plot_synapse_layer_distribution_log(mtypes__, multapse_dict, filename='synapse_layer_distribution.png')